
function verClientes()
{
 objElemento.setiModoVisualizacion('1');
 objElemento.setviewedRows('5');
 objElemento.setstrTotalRegistros('0');
 objElemento.setstrGap('0');
 objElemento.setstrTableId('Clientes');   
 objElemento.setstrFunction('verClientes()');
 objElemento.setstrTituloLista('Lista de Clientes');
 objElemento.setstrTituloForm('Clientes');  
 objElemento.settableContentServlet('/instelec/Clientes/ClientesTableContentServlet'); 
 objElemento.setstrLinkAddServlet('/instelec/Clientes/AddClientesServlet');
 objElemento.setstrLinkDeleteServlet('/instelec/Clientes/DeleteClientesServlet'); 
 objElemento.setstrLinkDuplicarServlet('');
 objElemento.setstrLinkEditServlet('/instelec/Clientes/ClientesElementServlet');  
 objElemento.setstrLinkEditParam('clientes.IDCLIENTE='); 
 /*
 objElemento.setstrCampos('clientes.CIF;clientes.FECHAALTA;clientes.FECHABAJA;clientes.NOMBRE;clientes.RAZONSOCIAL;clientes.IDLOCALIDAD;clientes.DIRECCION;clientes.CP;clientes.TELEFONO;clientes.FAX;clientes.MOVIL;clientes.EMAIL;clientes.NUMEROCUENTA;clientes.OBSERVACIONES;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrTipoEditor('NORMAL;DATE;DATE;NORMAL;NORMAL;AUTO;NORMAL;NORMAL;NORMAL;NORMAL;NORMAL;NORMAL;NORMAL;NORMAL;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrCamposDec('Cif;Fechaalta;Fechabaja;Nombre;Razonsocial;Idlocalidad;Direccion;Cp;Telefono;Fax;Movil;Email;Numerocuenta;Observaciones;Hijos;Editar;Borrar');
 objElemento.setstrCamposWidth('6%;6%;6%;6%;6%;6%;6%;6%;6%;6%;6%;6%;6%;6%;5%;5%;5%');
 objElemento.setstrLinksUlContentServlet(';;;;;/instelec/Localidades/LocalidadesUlContentServlet;;;;;;;;;;;'); 
 objElemento.setstrMetodosController('CifClientesParsed;FechaaltaClientesParsed;FechabajaClientesParsed;NombreClientesParsed;RazonsocialClientesParsed;IdlocalidadClientesParsed;DireccionClientesParsed;CpClientesParsed;TelefonoClientesParsed;FaxClientesParsed;MovilClientesParsed;EmailClientesParsed;NumerocuentaClientesParsed;ObservacionesClientesParsed;HijosTrabajosClientes;EditClientes;DeleteClientes');
 objElemento.setstrLinksUpdateServlet('/instelec/Clientes/UpdateCifServlet;/instelec/Clientes/UpdateFechaaltaServlet;/instelec/Clientes/UpdateFechabajaServlet;/instelec/Clientes/UpdateNombreServlet;/instelec/Clientes/UpdateRazonsocialServlet;/instelec/Clientes/UpdateIdlocalidadServlet;/instelec/Clientes/UpdateDireccionServlet;/instelec/Clientes/UpdateCpServlet;/instelec/Clientes/UpdateTelefonoServlet;/instelec/Clientes/UpdateFaxServlet;/instelec/Clientes/UpdateMovilServlet;/instelec/Clientes/UpdateEmailServlet;/instelec/Clientes/UpdateNumerocuentaServlet;/instelec/Clientes/UpdateObservacionesServlet;hijos;editar;borrar'); 
 objElemento.setstrEsOrdenable('1;1;1;1;1;1;1;1;1;1;1;1;1;1;0;0;0');  
 objElemento.setstrEventos('dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;click;click;click');
 objElemento.setstrValidarColumnasGrid(' validation-max-10-es; validate-date-separador-es; validate-date-separador-es; validation-max-50-es; validation-max-50-es;; validation-max-50-es; validation-max-5-es; validation-max-9-es; validation-max-9-es; validation-max-9-es; validation-max-50-es; validation-max-20-es; validation-max-500-es;;;');
 */
 objElemento.setstrCampos('clientes.NOMBRE;clientes.RAZONSOCIAL;clientes.TELEFONO;clientes.FAX;clientes.MOVIL;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrTipoEditor('NORMAL;NORMAL;NORMAL;NORMAL;NORMAL;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrCamposDec('Nombre;Razón social;Teléfono;Fax;Móvil;Hijos;Editar;Borrar');
 objElemento.setstrCamposWidth('25%;24%;12%;12%;12%;5%;5%;5%');
 objElemento.setstrLinksUlContentServlet(';;;;;;;'); 
 objElemento.setstrMetodosController('NombreClientesParsed;RazonsocialClientesParsed;TelefonoClientesParsed;FaxClientesParsed;MovilClientesParsed;HijosTrabajosClientes;EditClientes;DeleteClientes');
 objElemento.setstrLinksUpdateServlet('/instelec/Clientes/UpdateNombreServlet;/instelec/Clientes/UpdateRazonsocialServlet;/instelec/Clientes/UpdateTelefonoServlet;/instelec/Clientes/UpdateFaxServlet;/instelec/Clientes/UpdateMovilServlet;hijos;editar;borrar'); 
 objElemento.setstrEsOrdenable('1;1;1;1;1;0;0;0');  
 objElemento.setstrEventos('dblclick;dblclick;dblclick;dblclick;dblclick;click;click;click');
 objElemento.setstrValidarColumnasGrid(' validation-max-50-es; validation-max-50-es; validation-max-9-es; validation-max-9-es; validation-max-9-es;;;'); 
 
 objElemento.setstrFormCampos('clientes.IDCLIENTE;clientes.CIF;clientes.FECHAALTA;clientes.FECHABAJA;clientes.NOMBRE;clientes.RAZONSOCIAL;clientes.IDLOCALIDAD;clientes.DIRECCION;clientes.CP;clientes.TELEFONO;clientes.FAX;clientes.MOVIL;clientes.EMAIL;clientes.NUMEROCUENTA;clientes.OBSERVACIONES'); 
 objElemento.setstrFormCamposOblig('1;1;1;;1;;1;;;;;;;;'); 
 objElemento.setstrFormTipoEditor('HIDDEN;NORMAL;DATE;DATE;NORMAL;NORMAL;AUTO_3;NORMAL;NORMAL;NORMAL;NORMAL;NORMAL;NORMAL;NORMAL;AREA');
 objElemento.setstrFormCamposDec('Idcliente;Cif;Fecha de alta;Fecha de baja;Nombre;Razón social;Localidad;Dirección;C.P.;Teléfono;Fax;Móvil;Email;Nº de cuenta;Observaciones');
 objElemento.setstrFormCamposWidth('250px;300px;250px;250px;300px;250px;300px;300px;250px;250px;300px;250px;250px;300px;800px'); 
 objElemento.setstrFormLinksUlContentServlet(';;;;;;/instelec/Localidades/LocalidadesUlContentServlet;;;;;;;;');
 objElemento.setstrFormLinksElementServlet(';;;;;;/instelec/Clientes/ClientesLocalidadesServlet;;;;;;;;'); 
 objElemento.setstrFormMetodosController('Idcliente;CifClientesParsed;FechaaltaClientesParsed;FechabajaClientesParsed;NombreClientesParsed;RazonsocialClientesParsed;IdlocalidadClientesParsed;DireccionClientesParsed;CpClientesParsed;TelefonoClientesParsed;FaxClientesParsed;MovilClientesParsed;EmailClientesParsed;NumerocuentaClientesParsed;ObservacionesClientesParsed');  
 objElemento.setstrValidarCamposForm(' requerido-es;requerido-es validation-max-10-es;requerido-es validate-date-separador-es; validate-date-separador-es;requerido-es validation-max-50-es; validation-max-50-es; requerido-es; validation-max-50-es; validation-max-5-es; validation-max-9-es; validation-max-9-es; validation-max-9-es; validation-max-50-es; validation-max-20-es; validation-max-500-es');
 objElemento.setstrFormCabeceraLinks('Trabajos');
 objElemento.setstrFormCabeceraFunctions('verTrabajos()'); 
 objElemento.setstrCabeceraLinks('Localidades');
 objElemento.setstrCabeceraFunctions('verLocalidades()');  
 objElemento.setstrCabeceraIds('localidades.IDLOCALIDAD');
 objElemento.setstrLinkDetallePdfServlet('/instelec/Clientes/GetClientesDetallePdfServlet'); 
 objElemento.setstrLinkDetallePdfServletDec('Imprimir');   
 objElemento.setstrLinkListaPdfServlet('/instelec/Clientes/ClientesTableContentPdfServlet');   
 objElemento.setstrLinkListaPdfServletDec('Imprimir');  
 objElemento.setstrFiltroLinks('');
 objElemento.setstrFiltroFunctions(''); 
 objElemento.setstrSeparadorFecha('-');
 objElemento.setstrSeparadorHora(':');    
 cargaQueryGrid();
 cargaGrid();
 crear();
 } 
 function verTrabajadores()
{
 objElemento.setiModoVisualizacion('1');
 objElemento.setviewedRows('5');
 objElemento.setstrTotalRegistros('0');
 objElemento.setstrGap('0');
 objElemento.setstrTableId('Trabajadores');   
 objElemento.setstrFunction('verTrabajadores()');
 objElemento.setstrTituloLista('Lista de Trabajadores');
 objElemento.setstrTituloForm('Trabajadores');  
 objElemento.settableContentServlet('/instelec/Trabajadores/TrabajadoresTableContentServlet'); 
 objElemento.setstrLinkAddServlet('/instelec/Trabajadores/AddTrabajadoresServlet');
 objElemento.setstrLinkDeleteServlet('/instelec/Trabajadores/DeleteTrabajadoresServlet'); 
 objElemento.setstrLinkDuplicarServlet('');
 objElemento.setstrLinkEditServlet('/instelec/Trabajadores/TrabajadoresElementServlet'); 
 objElemento.setstrLinkEditParam('trabajadores.IDTRABAJADOR='); 
/*
 objElemento.setstrCampos('trabajadores.IDCATEGORIA;trabajadores.NIF;trabajadores.NOMBRE;trabajadores.APELLIDOUNO;trabajadores.APELLIDODOS;trabajadores.FECHAALTA;trabajadores.FECHABAJA;trabajadores.NUMEROSS;trabajadores.DIRECCION;trabajadores.CP;trabajadores.IDLOCALIDAD;trabajadores.TELEFONO;trabajadores.MOVIL;trabajadores.EMAIL;trabajadores.OBSERVACIONES;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrTipoEditor('AUTO;NORMAL;NORMAL;NORMAL;NORMAL;DATE;DATE;NORMAL;NORMAL;NORMAL;AUTO;NORMAL;NORMAL;NORMAL;NORMAL;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrCamposDec('Idcategoria;Nif;Nombre;Apellidouno;Apellidodos;Fechaalta;Fechabaja;Numeross;Direccion;Cp;Idlocalidad;Telefono;Movil;Email;Observaciones;Hijos;Editar;Borrar');
 objElemento.setstrCamposWidth('5%;5%;5%;5%;5%;5%;5%;5%;5%;5%;5%;5%;5%;5%;5%;5%;5%;5%');
 objElemento.setstrLinksUlContentServlet('/instelec/Categorias/CategoriasUlContentServlet;;;;;;;;;;/instelec/Localidades/LocalidadesUlContentServlet;;;;;;;'); 
 objElemento.setstrMetodosController('IdcategoriaTrabajadoresParsed;NifTrabajadoresParsed;NombreTrabajadoresParsed;ApellidounoTrabajadoresParsed;ApellidodosTrabajadoresParsed;FechaaltaTrabajadoresParsed;FechabajaTrabajadoresParsed;NumerossTrabajadoresParsed;DireccionTrabajadoresParsed;CpTrabajadoresParsed;IdlocalidadTrabajadoresParsed;TelefonoTrabajadoresParsed;MovilTrabajadoresParsed;EmailTrabajadoresParsed;ObservacionesTrabajadoresParsed;HijosPartesTrabajadores;EditTrabajadores;DeleteTrabajadores');
 objElemento.setstrLinksUpdateServlet('/instelec/Trabajadores/UpdateIdcategoriaServlet;/instelec/Trabajadores/UpdateNifServlet;/instelec/Trabajadores/UpdateNombreServlet;/instelec/Trabajadores/UpdateApellidounoServlet;/instelec/Trabajadores/UpdateApellidodosServlet;/instelec/Trabajadores/UpdateFechaaltaServlet;/instelec/Trabajadores/UpdateFechabajaServlet;/instelec/Trabajadores/UpdateNumerossServlet;/instelec/Trabajadores/UpdateDireccionServlet;/instelec/Trabajadores/UpdateCpServlet;/instelec/Trabajadores/UpdateIdlocalidadServlet;/instelec/Trabajadores/UpdateTelefonoServlet;/instelec/Trabajadores/UpdateMovilServlet;/instelec/Trabajadores/UpdateEmailServlet;/instelec/Trabajadores/UpdateObservacionesServlet;hijos;editar;borrar'); 
 objElemento.setstrEsOrdenable('1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;0;0;0');  
 objElemento.setstrEventos('dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;click;click;click');
 objElemento.setstrValidarColumnasGrid('; validation-max-10-es; validation-max-50-es; validation-max-50-es; validation-max-50-es; validate-date-separador-es; validate-date-separador-es; validation-max-20-es; validation-max-50-es; validation-max-5-es;; validation-max-9-es; validation-max-9-es; validation-max-25-es; validation-max-500-es;;;');
*/
 objElemento.setstrCampos('trabajadores.IDCATEGORIA;trabajadores.NOMBRE;trabajadores.APELLIDOUNO;trabajadores.TELEFONO;trabajadores.MOVIL;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrTipoEditor('AUTO;NORMAL;NORMAL;NORMAL;NORMAL;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrCamposDec('Categoria;Nombre;Apellido;Teléfono;Móvil;Hijos;Editar;Borrar');
 objElemento.setstrCamposWidth('17%;20%;20%;14%;14%;5%;5%;5%');
 objElemento.setstrLinksUlContentServlet('/instelec/Categorias/CategoriasUlContentServlet;;;;;;;'); 
 objElemento.setstrMetodosController('IdcategoriaTrabajadoresParsed;NombreTrabajadoresParsed;ApellidounoTrabajadoresParsed;TelefonoTrabajadoresParsed;MovilTrabajadoresParsed;HijosPartesTrabajadores;EditTrabajadores;DeleteTrabajadores');
 objElemento.setstrLinksUpdateServlet('/instelec/Trabajadores/UpdateIdcategoriaServlet;/instelec/Trabajadores/UpdateNombreServlet;/instelec/Trabajadores/UpdateApellidounoServlet;/instelec/Trabajadores/UpdateTelefonoServlet;/instelec/Trabajadores/UpdateMovilServlet;hijos;editar;borrar'); 
 objElemento.setstrEsOrdenable('1;1;1;1;1;0;0;0');  
 objElemento.setstrEventos('dblclick;dblclick;dblclick;dblclick;dblclick;click;click;click');
 objElemento.setstrValidarColumnasGrid('; validation-max-50-es; validation-max-50-es; validation-max-9-es; validation-max-9-es;;;');
 
 objElemento.setstrFormCampos('trabajadores.IDTRABAJADOR;trabajadores.IDCATEGORIA;trabajadores.NIF;trabajadores.NOMBRE;trabajadores.APELLIDOUNO;trabajadores.APELLIDODOS;trabajadores.FECHAALTA;trabajadores.FECHABAJA;trabajadores.NUMEROSS;trabajadores.DIRECCION;trabajadores.CP;trabajadores.IDLOCALIDAD;trabajadores.TELEFONO;trabajadores.MOVIL;trabajadores.EMAIL;trabajadores.OBSERVACIONES'); 
 objElemento.setstrFormCamposOblig('1;1;1;1;1;;1;;1;;;1;;;;'); 
 objElemento.setstrFormTipoEditor('HIDDEN;AUTO;NORMAL;NORMAL;NORMAL;NORMAL;DATE;DATE;NORMAL;NORMAL;NORMAL;AUTO_3;NORMAL;NORMAL;NORMAL;AREA');
 objElemento.setstrFormCamposDec('Idtrabajador;Categoria;Nif;Nombre;1º Apellido;2º Apellido;Fecha de alta;Fecha de baja;Numero S.S.;Dirección;Cp;Localidad;Tfno;Móvil;E-mail;Observaciones');
 objElemento.setstrFormCamposWidth('250px;350px;200px;250px;300px;250px;250px;300px;250px;250px;300px;300px;200px;300px;250px;800px'); 
 objElemento.setstrFormLinksUlContentServlet(';/instelec/Categorias/CategoriasUlContentServlet;;;;;;;;;;/instelec/Localidades/LocalidadesUlContentServlet;;;;');
 objElemento.setstrFormLinksElementServlet(';/instelec/Trabajadores/TrabajadoresCategoriasServlet;;;;;;;;;;/instelec/Trabajadores/TrabajadoresLocalidadesServlet;;;;'); 
 objElemento.setstrFormMetodosController('Idtrabajador;IdcategoriaTrabajadoresParsed;NifTrabajadoresParsed;NombreTrabajadoresParsed;ApellidounoTrabajadoresParsed;ApellidodosTrabajadoresParsed;FechaaltaTrabajadoresParsed;FechabajaTrabajadoresParsed;NumerossTrabajadoresParsed;DireccionTrabajadoresParsed;CpTrabajadoresParsed;IdlocalidadTrabajadoresParsed;TelefonoTrabajadoresParsed;MovilTrabajadoresParsed;EmailTrabajadoresParsed;ObservacionesTrabajadoresParsed');  
 objElemento.setstrValidarCamposForm(' requerido-es; requerido-es; requerido-es validation-max-10-es; requerido-es validation-max-50-es; requerido-es validation-max-50-es; validation-max-50-es; requerido-es validate-date-separador-es; validate-date-separador-es; requerido-es validation-max-20-es; validation-max-50-es; validation-max-5-es; requerido-es; validation-max-9-es; validation-max-9-es; validation-max-25-es; validation-max-500-es');
 objElemento.setstrFormCabeceraLinks('Partes');
 objElemento.setstrFormCabeceraFunctions('verPartes()'); 
 objElemento.setstrCabeceraLinks('Categorias;Localidades');
 objElemento.setstrCabeceraFunctions('verCategorias();verLocalidades()');  
 objElemento.setstrCabeceraIds('categorias.IDCATEGORIA;localidades.IDLOCALIDAD');  
 objElemento.setstrLinkDetallePdfServlet('/instelec/Trabajadores/GetTrabajadoresDetallePdfServlet'); 
 objElemento.setstrLinkDetallePdfServletDec('Imprimir');   
 objElemento.setstrLinkListaPdfServlet('/instelec/Trabajadores/TrabajadoresTableContentPdfServlet');   
 objElemento.setstrLinkListaPdfServletDec('Imprimir');  
 objElemento.setstrFiltroLinks('');
 objElemento.setstrFiltroFunctions(''); 
 objElemento.setstrSeparadorFecha('-');
 objElemento.setstrSeparadorHora(':');    
 cargaQueryGrid();
 cargaGrid();
 crear();
 } 
 function verPartes()
{
 objElemento.setiModoVisualizacion('1');
 objElemento.setviewedRows('12');
 objElemento.setstrTotalRegistros('0');
 objElemento.setstrGap('0');
 objElemento.setstrTableId('Partes');   
 objElemento.setstrFunction('verPartes()');
 objElemento.setstrTituloLista('Lista de Partes');
 objElemento.setstrTituloForm('Partes');  
 objElemento.settableContentServlet('/instelec/Partes/PartesTableContentServlet'); 
 objElemento.setstrLinkAddServlet('/instelec/Partes/AddPartesServlet');
 objElemento.setstrLinkDeleteServlet('/instelec/Partes/DeletePartesServlet'); 
 objElemento.setstrLinkDuplicarServlet('');
 objElemento.setstrLinkEditServlet('/instelec/Partes/PartesElementServlet');  
 objElemento.setstrLinkEditParam('partes.IDPARTE='); 
 objElemento.setstrCampos('partes.IDORDEN;partes.IDTRABAJADOR;partes.OBSERVACIONES;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrTipoEditor('AUTO;AUTO;AREA;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrCamposDec('Orden;Trabajador;Descripción;Hijos;Editar;Borrar');
 objElemento.setstrCamposWidth('25%;25%;35%;5%;5%;5%');
 objElemento.setstrLinksUlContentServlet('/instelec/Ordenestrabajo/OrdenestrabajoUlContentServlet;/instelec/Trabajadores/TrabajadoresUlContentServlet;;;;'); 
 objElemento.setstrMetodosController('IdordenPartesParsed;IdtrabajadorPartesParsed;ObservacionesPartesParsed;HijosLineaspartePartes;EditPartes;DeletePartes');
 objElemento.setstrLinksUpdateServlet('/instelec/Partes/UpdateIdordenServlet;/instelec/Partes/UpdateIdtrabajadorServlet;/instelec/Partes/UpdateObservacionesServlet;hijos;editar;borrar'); 
 objElemento.setstrEsOrdenable('1;1;1;0;0;0');  
 objElemento.setstrEventos('dblclick;dblclick;dblclick;click;click;click');
 objElemento.setstrValidarColumnasGrid(';; validation-max-500-es;;;');
 objElemento.setstrFormCampos('partes.IDPARTE;partes.IDORDEN;partes.IDTRABAJADOR;partes.OBSERVACIONES'); 
 objElemento.setstrFormCamposOblig('1;1;1;1'); 
 objElemento.setstrFormTipoEditor('HIDDEN;AUTO;AUTO;AREA');
 objElemento.setstrFormCamposDec('Idparte;Orden;Trabajador;Descripción');
 objElemento.setstrFormCamposWidth('350px;400px;300px;850px'); 
 objElemento.setstrFormLinksUlContentServlet(';/instelec/Ordenestrabajo/OrdenestrabajoUlContentServlet;/instelec/Trabajadores/TrabajadoresUlContentServlet;');
 objElemento.setstrFormLinksElementServlet(';/instelec/Partes/PartesOrdenestrabajoServlet;/instelec/Partes/PartesTrabajadoresServlet;'); 
 objElemento.setstrFormMetodosController('Idparte;IdordenPartesParsed;IdtrabajadorPartesParsed;ObservacionesPartesParsed');  
 objElemento.setstrValidarCamposForm(' requerido-es;requerido-es;requerido-es;requerido-esrequerido-es validation-max-500-es');
 objElemento.setstrFormCabeceraLinks('Lineas de parte');
 objElemento.setstrFormCabeceraFunctions('verLineasparte()'); 
 objElemento.setstrCabeceraLinks('Trabajadores;Ordenes de trabajo');
 objElemento.setstrCabeceraFunctions('verTrabajadores();verOrdenestrabajo()');  
 objElemento.setstrCabeceraIds('trabajadores.IDTRABAJADOR;ordenestrabajo.IDORDEN');  
 objElemento.setstrLinkDetallePdfServlet('/instelec/Partes/GetPartesDetallePdfServlet;/instelec/Partes/GetPartesInformePdfServlet'); 
 objElemento.setstrLinkDetallePdfServletDec('Imprimir;Parte');   
 objElemento.setstrLinkListaPdfServlet('/instelec/Partes/PartesTableContentPdfServlet');  
 objElemento.setstrLinkListaPdfServletDec('Imprimir'); 
 objElemento.setstrFiltroLinks('');
 objElemento.setstrFiltroFunctions(''); 
 objElemento.setstrSeparadorFecha('-');
 objElemento.setstrSeparadorHora(':');   
 cargaQueryGrid();
 cargaGrid();
 crear();
 } 
 function verLineasparte()
{
 objElemento.setiModoVisualizacion('1');
 objElemento.setviewedRows('12');
 objElemento.setstrTotalRegistros('0');
 objElemento.setstrGap('0');
 objElemento.setstrTableId('Lineasparte');   
 objElemento.setstrFunction('verLineasparte()');
 objElemento.setstrTituloLista('Lista de Lineas de parte');
 objElemento.setstrTituloForm('Lineas de parte');  
 objElemento.settableContentServlet('/instelec/Lineasparte/LineasparteTableContentServlet'); 
 objElemento.setstrLinkAddServlet('/instelec/Lineasparte/AddLineasparteServlet');
 objElemento.setstrLinkDeleteServlet('/instelec/Lineasparte/DeleteLineasparteServlet'); 
 objElemento.setstrLinkDuplicarServlet('');
 objElemento.setstrLinkEditServlet('/instelec/Lineasparte/LineasparteElementServlet');  
 objElemento.setstrLinkEditParam('lineasparte.IDLINEAPARTE='); 
 objElemento.setstrCampos('lineasparte.IDPARTE;lineasparte.FECHA;lineasparte.HORAS;lineasparte.OBSERVACIONES;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrTipoEditor('AUTO;DATE;NORMAL;AREA;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrCamposDec('Parte;Fecha;Horas;Descripción;Editar;Borrar');
 objElemento.setstrCamposWidth('25%;15%;15%;35%;5%;5%');
 objElemento.setstrLinksUlContentServlet('/instelec/Partes/PartesUlContentServlet;;;;;'); 
 objElemento.setstrMetodosController('IdparteLineasparteParsed;FechaLineasparteParsed;HorasLineasparteParsed;ObservacionesLineasparteParsed;EditLineasparte;DeleteLineasparte');
 objElemento.setstrLinksUpdateServlet('/instelec/Lineasparte/UpdateIdparteServlet;/instelec/Lineasparte/UpdateFechaServlet;/instelec/Lineasparte/UpdateHorasServlet;/instelec/Lineasparte/UpdateObservacionesServlet;editar;borrar'); 
 objElemento.setstrEsOrdenable('1;1;1;1;0;0');  
 objElemento.setstrEventos('dblclick;dblclick;dblclick;dblclick;click;click');
 objElemento.setstrValidarColumnasGrid('; validate-date-separador-es; requerido-es validate-number-es; validation-max-500-es;;');
 objElemento.setstrFormCampos('lineasparte.IDLINEAPARTE;lineasparte.IDPARTE;lineasparte.FECHA;lineasparte.HORAS;lineasparte.OBSERVACIONES'); 
 objElemento.setstrFormCamposOblig('1;1;1;1;'); 
 objElemento.setstrFormTipoEditor('HIDDEN;AUTO;DATE;NORMAL;AREA');
 objElemento.setstrFormCamposDec('Idlineaparte;Parte;Fecha;Horas;Descripción');
 objElemento.setstrFormCamposWidth('250px;300px;200px;250px;750px'); 
 objElemento.setstrFormLinksUlContentServlet(';/instelec/Partes/PartesUlContentServlet;;;');
 objElemento.setstrFormLinksElementServlet(';/instelec/Lineasparte/LineaspartePartesServlet;;;'); 
 objElemento.setstrFormMetodosController('Idlineaparte;IdparteLineasparteParsed;FechaLineasparteParsed;HorasLineasparteParsed;ObservacionesLineasparteParsed');  
 objElemento.setstrValidarCamposForm(' requerido-es; requerido-es ; requerido-es validate-date-separador-es; requerido-es validate-number-es; validation-max-500-es');
 objElemento.setstrFormCabeceraLinks('');
 objElemento.setstrFormCabeceraFunctions(''); 
 objElemento.setstrCabeceraLinks('Partes');
 objElemento.setstrCabeceraFunctions('verPartes()');  
 objElemento.setstrCabeceraIds('partes.IDPARTE'); 
 objElemento.setstrLinkDetallePdfServlet('/instelec/Lineasparte/GetLineasparteDetallePdfServlet'); 
 objElemento.setstrLinkDetallePdfServletDec('Imprimir');   
 objElemento.setstrLinkListaPdfServlet('/instelec/Lineasparte/LineasparteTableContentPdfServlet');   
 objElemento.setstrLinkListaPdfServletDec('Imprimir');  
 objElemento.setstrFiltroLinks('');
 objElemento.setstrFiltroFunctions(''); 
 objElemento.setstrSeparadorFecha('-');
 objElemento.setstrSeparadorHora(':');   
 cargaQueryGrid();
 cargaGrid();
 crear();
 } 
 function verTrabajos()
{
 objElemento.setiModoVisualizacion('1');
 objElemento.setviewedRows('5');
 objElemento.setstrTotalRegistros('0');
 objElemento.setstrGap('0');
 objElemento.setstrTableId('Trabajos');   
 objElemento.setstrFunction('verTrabajos()');
 objElemento.setstrTituloLista('Lista de Trabajos');
 objElemento.setstrTituloForm('Trabajos');  
 objElemento.settableContentServlet('/instelec/Trabajos/TrabajosTableContentServlet'); 
 objElemento.setstrLinkAddServlet('/instelec/Trabajos/AddTrabajosServlet');
 objElemento.setstrLinkDeleteServlet('/instelec/Trabajos/DeleteTrabajosServlet'); 
 objElemento.setstrLinkDuplicarServlet('');
 objElemento.setstrLinkEditServlet('/instelec/Trabajos/TrabajosElementServlet'); 
 objElemento.setstrLinkEditParam('trabajos.IDTRABAJO='); 
 /*
 objElemento.setstrCampos('trabajos.IDCLIENTE;trabajos.DESCRIPCION;trabajos.FECHAAVISO;trabajos.HORAAVISO;trabajos.FECHAPRESUPUESTO;trabajos.FECHAFINTRABAJO;trabajos.FECHAFACTURA;trabajos.DIRECCION;trabajos.CP;trabajos.TELEFONO;trabajos.ESTADO;trabajos.IMPORTE;trabajos.OBSERVACIONES;trabajos.PERSONACONTACTO;trabajos.PERSONARECIBE;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrTipoEditor('AUTO;NORMAL;DATE;NORMAL;DATE;DATE;DATE;NORMAL;NORMAL;NORMAL;AUTO;NORMAL;NORMAL;NORMAL;NORMAL;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrCamposDec('Idcliente;Descripcion;Fechaaviso;Horaaviso;Fechapresupuesto;Fechafintrabajo;Fechafactura;Direccion;Cp;Telefono;Estado;Importe;Observaciones;Personacontacto;Personarecibe;Hijos;Editar;Borrar');
 objElemento.setstrCamposWidth('5%;5%;5%;5%;5%;5%;5%;5%;5%;5%;5%;5%;5%;5%;5%;5%;5%;5%');
 objElemento.setstrLinksUlContentServlet('/instelec/Clientes/ClientesUlContentServlet;;;;;;;;;/instelec/Trabajos/EstadoTrabajosUlContentServlet;;;;;;;;'); 
 objElemento.setstrMetodosController('IdclienteTrabajosParsed;DescripcionTrabajosParsed;FechaavisoTrabajosParsed;HoraavisoTrabajosParsed;FechapresupuestoTrabajosParsed;FechafintrabajoTrabajosParsed;FechafacturaTrabajosParsed;DireccionTrabajosParsed;CpTrabajosParsed;TelefonoTrabajosParsed;EstadoTrabajosParsedLabel;ImporteTrabajosParsed;ObservacionesTrabajosParsed;PersonacontactoTrabajosParsed;PersonarecibeTrabajosParsed;HijosOrdenestrabajoTrabajos;EditTrabajos;DeleteTrabajos');
 objElemento.setstrLinksUpdateServlet('/instelec/Trabajos/UpdateIdclienteServlet;/instelec/Trabajos/UpdateDescripcionServlet;/instelec/Trabajos/UpdateFechaavisoServlet;/instelec/Trabajos/UpdateHoraavisoServlet;/instelec/Trabajos/UpdateFechapresupuestoServlet;/instelec/Trabajos/UpdateFechafintrabajoServlet;/instelec/Trabajos/UpdateFechafacturaServlet;/instelec/Trabajos/UpdateDireccionServlet;/instelec/Trabajos/UpdateCpServlet;/instelec/Trabajos/UpdateTelefonoServlet;/instelec/Trabajos/UpdateEstadoServlet;/instelec/Trabajos/UpdateImporteServlet;/instelec/Trabajos/UpdateObservacionesServlet;/instelec/Trabajos/UpdatePersonacontactoServlet;/instelec/Trabajos/UpdatePersonarecibeServlet;hijos;editar;borrar'); 
 objElemento.setstrEsOrdenable('1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;0;0;0');  
 objElemento.setstrEventos('dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;click;click;click');
 objElemento.setstrValidarColumnasGrid('; validation-max-300-es; validate-date-separador-es; validation-max-4-es; validate-date-separador-es; validate-date-separador-es; validate-date-separador-es; validation-max-50-es; validation-max-5-es; validation-max-9-es;;; validation-max-500-es; validation-max-50-es; validation-max-50-es;;;');
 */
 objElemento.setstrCampos('trabajos.IDCLIENTE;trabajos.PERSONACONTACTO;trabajos.TELEFONO;trabajos.FECHAAVISO;trabajos.HORAAVISO;trabajos.DESCRIPCION;trabajos.ESTADO;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrTipoEditor('AUTO;NORMAL;NORMAL;DATE;NORMAL;NORMAL;AUTO;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrCamposDec('Cliente;Contacto;Teléfono;Aviso (fecha);Hora;Descripción;Estado;Hijos;Editar;Borrar');
 objElemento.setstrCamposWidth('14%;14%;12%;10%;5%;17%;12%;5%;5%;5%');
 objElemento.setstrLinksUlContentServlet('/instelec/Clientes/ClientesUlContentServlet;;;;;;;;/instelec/Trabajos/EstadoTrabajosUlContentServlet;;'); 
 objElemento.setstrMetodosController('IdclienteTrabajosParsed;PersonacontactoTrabajosParsed;TelefonoTrabajosParsed;FechaavisoTrabajosParsed;HoraavisoTrabajosParsed;DescripcionTrabajosParsed;EstadoTrabajosParsedLabel;HijosOrdenestrabajoTrabajos;EditTrabajos;DeleteTrabajos');
 objElemento.setstrLinksUpdateServlet('/instelec/Trabajos/UpdateIdclienteServlet;/instelec/Trabajos/UpdatePersonacontactoServlet;/instelec/Trabajos/UpdateTelefonoServlet;/instelec/Trabajos/UpdateFechaavisoServlet;/instelec/Trabajos/UpdateHoraavisoServlet;/instelec/Trabajos/UpdateDescripcionServlet;/instelec/Trabajos/UpdateEstadoServlet;hijos;editar;borrar'); 
 objElemento.setstrEsOrdenable('1;1;1;1;1;1;1;0;0;0');  
 objElemento.setstrEventos('dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;click;click;click');
 objElemento.setstrValidarColumnasGrid('requerido-es; validation-max-50-es; validation-max-9-es; validate-date-separador-es; validation-max-4-es; validation-max-300-es;;;;'); 
 
 objElemento.setstrFormCampos('trabajos.IDTRABAJO;trabajos.IDCLIENTE;trabajos.DESCRIPCION;trabajos.FECHAAVISO;trabajos.HORAAVISO;trabajos.FECHAPRESUPUESTO;trabajos.FECHAFINTRABAJO;trabajos.FECHAFACTURA;trabajos.DIRECCION;trabajos.CP;trabajos.TELEFONO;trabajos.PERSONACONTACTO;trabajos.PERSONARECIBE;trabajos.ESTADO;trabajos.IMPORTECALCULADO;trabajos.IMPORTE;trabajos.OBSERVACIONES'); 
 objElemento.setstrFormCamposOblig('1;1;1;1;;;;;;;;;;1;;;'); 
 objElemento.setstrFormTipoEditor('HIDDEN;AUTO;NORMAL;DATE;NORMAL;DATE;DATE;DATE;NORMAL;NORMAL;NORMAL;NORMAL;NORMAL;AUTO;LECTURA;NORMAL;AREA');
 objElemento.setstrFormCamposDec('Idtrabajo;Cliente;Referencia;Aviso;Aviso (hora);Presupuesto;Finalización;Factura;Dirección;Cp;Teléfono;Contacto;Recibe;Estado;Total;Importe;Observaciones');
 objElemento.setstrFormCamposWidth('250px;350px;450px;300px;250px;250px;550px;250px;300px;250px;250px;550px;250px;350px;200px;250px;800px'); 
 objElemento.setstrFormLinksUlContentServlet(';/instelec/Clientes/ClientesUlContentServlet;;;;;;;;;;;;/instelec/Trabajos/EstadoTrabajosUlContentServlet;;;');
 objElemento.setstrFormLinksElementServlet(';/instelec/Trabajos/TrabajosClientesServlet;;;;;;;;;;;;;;;'); 
 objElemento.setstrFormMetodosController('Idtrabajo;IdclienteTrabajosParsed;DescripcionTrabajosParsed;FechaavisoTrabajosParsed;HoraavisoTrabajosParsed;FechapresupuestoTrabajosParsed;FechafintrabajoTrabajosParsed;FechafacturaTrabajosParsed;DireccionTrabajosParsed;CpTrabajosParsed;TelefonoTrabajosParsed;PersonacontactoTrabajosParsed;PersonarecibeTrabajosParsed;EstadoTrabajosParsed;ImporteCalculadoTrabajosParsed;ImporteTrabajosParsed;ObservacionesTrabajosParsed');  
 objElemento.setstrValidarCamposForm(' requerido-es; requerido-es; requerido-es validation-max-300-es; requerido-es validate-date-separador-es; validation-max-4-es; validate-date-separador-es; validate-date-separador-es; validate-date-separador-es; validation-max-50-es; validation-max-5-es; validation-max-9-es; validation-max-50-es; validation-max-50-es; requerido-es ;;; validation-max-500-es');
 objElemento.setstrFormCabeceraLinks('Ordenes de trabajo');
 objElemento.setstrFormCabeceraFunctions('verOrdenestrabajo()'); 
 objElemento.setstrCabeceraLinks('Clientes');
 objElemento.setstrCabeceraFunctions('verClientes()');  
 objElemento.setstrCabeceraIds('clientes.IDCLIENTE');  
 objElemento.setstrLinkDetallePdfServlet('/instelec/Trabajos/GetTrabajosDetallePdfServlet;/instelec/Trabajos/GetTrabajosPresupuestoPdfServlet;/instelec/Trabajos/GetTrabajosFacturaPdfServlet'); 
 objElemento.setstrLinkDetallePdfServletDec('Imprimir;Presupuesto;Factura');  
 objElemento.setstrLinkListaPdfServlet('/instelec/Trabajos/TrabajosTableContentPdfServlet');   
 objElemento.setstrLinkListaPdfServletDec('Imprimir');   
 objElemento.setstrFiltroLinks('Todos;Pendientes;Abiertos;Presupuestados;Rechazados;Facturados');
 objElemento.setstrFiltroFunctions('0;5;1;2;3;4');
 objElemento.setstrSeparadorFecha('-');
 objElemento.setstrSeparadorHora(':');   
 cargaQueryGrid();
 cargaGrid();
 crear();
 } 
 function verOrdenestrabajo()
{
 objElemento.setiModoVisualizacion('1');
 objElemento.setviewedRows('5');
 objElemento.setstrTotalRegistros('0');
 objElemento.setstrGap('0');
 objElemento.setstrTableId('Ordenestrabajo');   
 objElemento.setstrFunction('verOrdenestrabajo()');
 objElemento.setstrTituloLista('Lista de Ordenes de trabajo');
 objElemento.setstrTituloForm('Ordenes de trabajo');  
 objElemento.settableContentServlet('/instelec/Ordenestrabajo/OrdenestrabajoTableContentServlet'); 
 objElemento.setstrLinkAddServlet('/instelec/Ordenestrabajo/AddOrdenestrabajoServlet');
 objElemento.setstrLinkDeleteServlet('/instelec/Ordenestrabajo/DeleteOrdenestrabajoServlet'); 
 objElemento.setstrLinkDuplicarServlet('');
 objElemento.setstrLinkEditServlet('/instelec/Ordenestrabajo/OrdenestrabajoElementServlet');  
 objElemento.setstrLinkEditParam('ordenestrabajo.IDORDEN='); 
 /*
 objElemento.setstrCampos('ordenestrabajo.FECHAINICIO;ordenestrabajo.FECHAFIN;ordenestrabajo.IDTRABAJO;ordenestrabajo.DESCRIPCION;ordenestrabajo.OBSERVACIONES;ordenestrabajo.TIPOMANTENIMIENTO;ordenestrabajo.URGENCIA;ordenestrabajo.SINTOMAS;ordenestrabajo.CAUSAS;ordenestrabajo.IMPORTE;FREE_HIJOS;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrTipoEditor('DATE;DATE;AUTO;NORMAL;NORMAL;AUTO;AUTO;NORMAL;NORMAL;NORMAL;FREE_HIJOS;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrCamposDec('Fechainicio;Fechafin;Idtrabajo;Descripcion;Observaciones;Tipomantenimiento;Urgencia;Sintomas;Causas;Importe;Hijos;Hijos;Editar;Borrar');
 objElemento.setstrCamposWidth('8%;8%;8%;8%;8%;8%;8%;8%;8%;8%;5%;5%;5%;5%');
 objElemento.setstrLinksUlContentServlet(';;/instelec/Trabajos/TrabajosUlContentServlet;;;/instelec/Ordenestrabajo/TipomantenimientoOrdenestrabajoUlContentServlet;/instelec/Ordenestrabajo/UrgenciaOrdenestrabajoUlContentServlet;;;;;;;'); 
 objElemento.setstrMetodosController('FechainicioOrdenestrabajoParsed;FechafinOrdenestrabajoParsed;IdtrabajoOrdenestrabajoParsed;DescripcionOrdenestrabajoParsed;ObservacionesOrdenestrabajoParsed;TipomantenimientoOrdenestrabajoParsedLabel;UrgenciaOrdenestrabajoParsedLabel;SintomasOrdenestrabajoParsed;CausasOrdenestrabajoParsed;ImporteOrdenestrabajoParsed;HijosPartesOrdenestrabajo;HijosTareasOrdenestrabajo;EditOrdenestrabajo;DeleteOrdenestrabajo');
 objElemento.setstrLinksUpdateServlet('/instelec/Ordenestrabajo/UpdateFechainicioServlet;/instelec/Ordenestrabajo/UpdateFechafinServlet;/instelec/Ordenestrabajo/UpdateIdtrabajoServlet;/instelec/Ordenestrabajo/UpdateDescripcionServlet;/instelec/Ordenestrabajo/UpdateObservacionesServlet;/instelec/Ordenestrabajo/UpdateTipomantenimientoServlet;/instelec/Ordenestrabajo/UpdateUrgenciaServlet;/instelec/Ordenestrabajo/UpdateSintomasServlet;/instelec/Ordenestrabajo/UpdateCausasServlet;/instelec/Ordenestrabajo/UpdateImporteServlet;hijos;hijos;editar;borrar'); 
 objElemento.setstrEsOrdenable('1;1;1;1;1;1;1;1;1;1;0;0;0;0');  
 objElemento.setstrEventos('dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;click;click;click;click');
 objElemento.setstrValidarColumnasGrid(' validate-date-separador-es; validate-date-separador-es;; validation-max-250-es; validation-max-250-es;;; validation-max-250-es; validation-max-250-es;;;;;');
 */
 objElemento.setstrCampos('ordenestrabajo.IDTRABAJO;ordenestrabajo.DESCRIPCION;ordenestrabajo.TIPOMANTENIMIENTO;ordenestrabajo.URGENCIA;ordenestrabajo.SINTOMAS;ordenestrabajo.CAUSAS;FREE_HIJOS;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrTipoEditor('AUTO;NORMAL;AUTO;AUTO;AREA;AREA;FREE_HIJOS;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrCamposDec('Trabajo;Referencia;Tipo;Urgencia;Sintomas;Causas;Hijos;Hijos;Editar;Borrar');
 objElemento.setstrCamposWidth('14%;14%;12%;12%;13%;13%;5%;5%;5%;5%');
 objElemento.setstrLinksUlContentServlet('/instelec/Trabajos/TrabajosUlContentServlet;;/instelec/Ordenestrabajo/TipomantenimientoOrdenestrabajoUlContentServlet;/instelec/Ordenestrabajo/UrgenciaOrdenestrabajoUlContentServlet;;;;;;'); 
 objElemento.setstrMetodosController('IdtrabajoOrdenestrabajoParsed;DescripcionOrdenestrabajoParsed;TipomantenimientoOrdenestrabajoParsedLabel;UrgenciaOrdenestrabajoParsedLabel;SintomasOrdenestrabajoParsed;CausasOrdenestrabajoParsed;HijosPartesOrdenestrabajo;HijosTareasOrdenestrabajo;EditOrdenestrabajo;DeleteOrdenestrabajo');
 objElemento.setstrLinksUpdateServlet('/instelec/Ordenestrabajo/UpdateIdtrabajoServlet;/instelec/Ordenestrabajo/UpdateDescripcionServlet;/instelec/Ordenestrabajo/UpdateTipomantenimientoServlet;/instelec/Ordenestrabajo/UpdateUrgenciaServlet;/instelec/Ordenestrabajo/UpdateSintomasServlet;/instelec/Ordenestrabajo/UpdateCausasServlet;hijos;hijos;editar;borrar'); 
 objElemento.setstrEsOrdenable('1;1;1;1;1;1;0;0;0;0');  
 objElemento.setstrEventos('dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;click;click;click;click');
 objElemento.setstrValidarColumnasGrid('; validation-max-250-es;;; validation-max-250-es; validation-max-250-es;;;;'); 
 
 objElemento.setstrFormCampos('ordenestrabajo.IDORDEN;ordenestrabajo.FECHAINICIO;ordenestrabajo.FECHAFIN;ordenestrabajo.IDTRABAJO;ordenestrabajo.DESCRIPCION;ordenestrabajo.URGENCIA;ordenestrabajo.TIPOMANTENIMIENTO;ordenestrabajo.OBSERVACIONES;ordenestrabajo.SINTOMAS;ordenestrabajo.CAUSAS;ordenestrabajo.IMPORTECALCULADO;ordenestrabajo.MANOOBRACALCULADO;ordenestrabajo.IMPORTE'); 
 objElemento.setstrFormCamposOblig('1;1;;1;1;1;1;;;;;;'); 
 objElemento.setstrFormTipoEditor('HIDDEN;DATE;DATE;AUTO;NORMAL;AUTO;AUTO;AREA;AREA;AREA;LECTURA;LECTURA;NORMAL');
 objElemento.setstrFormCamposDec('Idorden;Fecha Inicio;Fecha Fin;Trabajo;Referencia;Urgencia;Tipo;Observaciones;Síntomas;Causas;Materiales;Cálculo;Mano de obra');
 objElemento.setstrFormCamposWidth('250px;300px;250px;300px;300px;300px;250px;800px;800px;800px;200px;250px;350px'); 
 objElemento.setstrFormLinksUlContentServlet(';;;/instelec/Trabajos/TrabajosUlContentServlet;;/instelec/Ordenestrabajo/UrgenciaOrdenestrabajoUlContentServlet;/instelec/Ordenestrabajo/TipomantenimientoOrdenestrabajoUlContentServlet;;;;;;');
 objElemento.setstrFormLinksElementServlet(';;;/instelec/Ordenestrabajo/OrdenestrabajoTrabajosServlet;;;;;;;;;'); 
 objElemento.setstrFormMetodosController('Idorden;FechainicioOrdenestrabajoParsed;FechafinOrdenestrabajoParsed;IdtrabajoOrdenestrabajoParsed;DescripcionOrdenestrabajoParsed;UrgenciaOrdenestrabajoParsed;TipomantenimientoOrdenestrabajoParsed;ObservacionesOrdenestrabajoParsed;SintomasOrdenestrabajoParsed;CausasOrdenestrabajoParsed;ImporteCalculadoOrdenestrabajoParsed;ManoObraCalculadoOrdenestrabajoParsed;ImporteOrdenestrabajoParsed');  
 objElemento.setstrValidarCamposForm(' requerido-es; requerido-es validate-date-separador-es; validate-date-separador-es; requerido-es; requerido-es validation-max-250-es; requerido-es; requerido-es; validation-max-250-es; validation-max-250-es; validation-max-250-es;;;');
 objElemento.setstrFormCabeceraLinks('Partes;Tareas');
 objElemento.setstrFormCabeceraFunctions('verPartes();verTareas()'); 
 objElemento.setstrCabeceraLinks('Trabajos');
 objElemento.setstrCabeceraFunctions('verTrabajos()');  
 objElemento.setstrCabeceraIds('trabajos.IDTRABAJO');  
 objElemento.setstrLinkDetallePdfServlet('/instelec/Ordenestrabajo/GetOrdenestrabajoDetallePdfServlet'); 
 objElemento.setstrLinkDetallePdfServletDec('Imprimir');   
 objElemento.setstrLinkListaPdfServlet('/instelec/Ordenestrabajo/OrdenestrabajoTableContentPdfServlet');  
 objElemento.setstrLinkListaPdfServletDec('Imprimir');  
 objElemento.setstrFiltroLinks('Todas;No urgente;Urgente;Muy urgente');
 objElemento.setstrFiltroFunctions('0;1;2;3'); 
 objElemento.setstrSeparadorFecha('-');
 objElemento.setstrSeparadorHora(':');   
 cargaQueryGrid();
 cargaGrid();
 crear();
 } 
 function verTareas()
{
 objElemento.setiModoVisualizacion('1');
 objElemento.setviewedRows('8');
 objElemento.setstrTotalRegistros('0');
 objElemento.setstrGap('0');
 objElemento.setstrTableId('Tareas');   
 objElemento.setstrFunction('verTareas()');
 objElemento.setstrTituloLista('Lista de Tareas');
 objElemento.setstrTituloForm('Tareas');  
 objElemento.settableContentServlet('/instelec/Tareas/TareasTableContentServlet'); 
 objElemento.setstrLinkAddServlet('/instelec/Tareas/AddTareasServlet');
 objElemento.setstrLinkDeleteServlet('/instelec/Tareas/DeleteTareasServlet'); 
 objElemento.setstrLinkDuplicarServlet('');
 objElemento.setstrLinkEditServlet('/instelec/Tareas/TareasElementServlet');  
 objElemento.setstrLinkEditParam('tareas.IDTAREA='); 
 objElemento.setstrCampos('tareas.FECHAINICIO;tareas.HORAS;tareas.IDORDEN;tareas.IDTIPOTAREA;tareas.IDCATEGORIA;tareas.OBSERVACIONES;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrTipoEditor('DATE;NORMAL;AUTO;AUTO;AUTO;AREA;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrCamposDec('Fecha Inicio;Horas;Orden de Trabajo;Tipo Tarea;Categoría;Descripción;Hijos;Editar;Borrar');
 objElemento.setstrCamposWidth('12%;12%;14%;14%;14%;18%;5%;5%;5%');
 objElemento.setstrLinksUlContentServlet(';;/instelec/Ordenestrabajo/OrdenestrabajoUlContentServlet;/instelec/Tipotareas/TipotareasUlContentServlet;/instelec/Categorias/CategoriasUlContentServlet;;;;'); 
 objElemento.setstrMetodosController('FechainicioTareasParsed;HorasTareasParsed;IdordenTareasParsed;IdtipotareaTareasParsed;IdcategoriaTareasParsed;ObservacionesTareasParsed;HijosMaterialesTareas;EditTareas;DeleteTareas');
 objElemento.setstrLinksUpdateServlet('/instelec/Tareas/UpdateFechainicioServlet;/instelec/Tareas/UpdateHorasServlet;/instelec/Tareas/UpdateIdordenServlet;/instelec/Tareas/UpdateIdtipotareaServlet;/instelec/Tareas/UpdateIdcategoriaServlet;/instelec/Tareas/UpdateObservacionesServlet;hijos;editar;borrar'); 
 objElemento.setstrEsOrdenable('1;1;1;1;1;1;0;0;0');  
 objElemento.setstrEventos('dblclick;dblclick;dblclick;dblclick;dblclick;dblclick;click;click;click');
 objElemento.setstrValidarColumnasGrid(' validate-date-separador-es; requerido-es validate-number-es;;;; validation-max-500-es;;;');
 objElemento.setstrFormCampos('tareas.IDTAREA;tareas.FECHAINICIO;tareas.HORAS;tareas.IDORDEN;tareas.IDTIPOTAREA;tareas.IDCATEGORIA;tareas.OBSERVACIONES;tareas.IMPORTECALCULADO;tareas.MANOOBRACALCULADO'); 
 objElemento.setstrFormCamposOblig('1;1;1;1;1;1;1;1;1'); 
 objElemento.setstrFormTipoEditor('HIDDEN;DATE;NORMAL;AUTO;AUTO;AUTO;AREA;LECTURA;LECTURA');
 objElemento.setstrFormCamposDec('Idtarea;Fecha Inicio;Horas;Orden de Trabajo;Tipo Tarea;Categoría;Descripción;Total Materiales;Mano de obra');
 objElemento.setstrFormCamposWidth('350px;350px;350px;400px;350px;400px;850px;250px;350px'); 
 objElemento.setstrFormLinksUlContentServlet(';;;/instelec/Ordenestrabajo/OrdenestrabajoUlContentServlet;/instelec/Tipotareas/TipotareasUlContentServlet;/instelec/Categorias/CategoriasUlContentServlet;;;');
 objElemento.setstrFormLinksElementServlet(';;;/instelec/Tareas/TareasOrdenestrabajoServlet;/instelec/Tareas/TareasTipotareasServlet;/instelec/Tareas/TareasCategoriasServlet;;;'); 
 objElemento.setstrFormMetodosController('Idtarea;FechainicioTareasParsed;HorasTareasParsed;IdordenTareasParsed;IdtipotareaTareasParsed;IdcategoriaTareasParsed;ObservacionesTareasParsed;ImporteCalculadoTareasParsed;ManoObraCalculadoTareasParsed');  
 objElemento.setstrValidarCamposForm(' requerido-es; requerido-es validate-date-separador-es; requerido-es validate-number-es; requerido-es; requerido-es; requerido-es; requerido-es validation-max-500-es; requerido-es; requerido-es');
 objElemento.setstrFormCabeceraLinks('Materiales');
 objElemento.setstrFormCabeceraFunctions('verMateriales()'); 
 objElemento.setstrCabeceraLinks('Ordenes de trabajo;Tipo de tareas;Categorias');
 objElemento.setstrCabeceraFunctions('verOrdenestrabajo();verTipotareas();verCategorias()');  
 objElemento.setstrCabeceraIds('ordenestrabajo.IDORDEN;tipotareas.IDTIPOTAREA;categorias.IDCATEGORIA'); 
 objElemento.setstrLinkDetallePdfServlet('/instelec/Tareas/GetTareasDetallePdfServlet'); 
 objElemento.setstrLinkDetallePdfServletDec('Imprimir');   
 objElemento.setstrLinkListaPdfServlet('/instelec/Tareas/TareasTableContentPdfServlet');   
 objElemento.setstrLinkListaPdfServletDec('Imprimir');  
 objElemento.setstrFiltroLinks('');
 objElemento.setstrFiltroFunctions(''); 
 objElemento.setstrSeparadorFecha('-');
 objElemento.setstrSeparadorHora(':');  
 cargaQueryGrid();
 cargaGrid();
 crear();
 } 
 function verMateriales()
{
 objElemento.setiModoVisualizacion('1');
 objElemento.setviewedRows('12');
 objElemento.setstrTotalRegistros('0');
 objElemento.setstrGap('0');
 objElemento.setstrTableId('Materiales');   
 objElemento.setstrFunction('verMateriales()');
 objElemento.setstrTituloLista('Lista de Materiales');
 objElemento.setstrTituloForm('Materiales');  
 objElemento.settableContentServlet('/instelec/Materiales/MaterialesTableContentServlet'); 
 objElemento.setstrLinkAddServlet('/instelec/Materiales/AddMaterialesServlet');
 objElemento.setstrLinkDeleteServlet('/instelec/Materiales/DeleteMaterialesServlet'); 
 objElemento.setstrLinkDuplicarServlet('');
 objElemento.setstrLinkEditServlet('/instelec/Materiales/MaterialesElementServlet'); 
 objElemento.setstrLinkEditParam('materiales.IDMATERIAL='); 
/* 
 objElemento.setstrCampos('materiales.DESCRIPCION;materiales.CANTIDAD;materiales.IMPORTE;materiales.IDTAREA;materiales.IDTIPOMATERIAL;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrTipoEditor('NORMAL;NORMAL;NORMAL;AUTO;AUTO;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrCamposDec('Referencia;Cantidad;Importe;Tarea;Tipo de material;Editar;Borrar');
 objElemento.setstrCamposWidth('14%;14%;14%;23%;23%;5%;5%');
 objElemento.setstrLinksUlContentServlet(';;;/instelec/Tareas/TareasUlContentServlet;/instelec/Tipomateriales/TipomaterialesUlContentServlet;;'); 
 objElemento.setstrMetodosController('DescripcionMaterialesParsed;CantidadMaterialesParsed;ImporteMaterialesParsed;IdtareaMaterialesParsed;IdtipomaterialMaterialesParsed;EditMateriales;DeleteMateriales');
 objElemento.setstrLinksUpdateServlet('/instelec/Materiales/UpdateDescripcionServlet;/instelec/Materiales/UpdateCantidadServlet;/instelec/Materiales/UpdateImporteServlet;/instelec/Materiales/UpdateIdtareaServlet;/instelec/Materiales/UpdateIdtipomaterialServlet;editar;borrar'); 
 objElemento.setstrEsOrdenable('1;1;1;1;1;0;0');  
 objElemento.setstrEventos('dblclick;dblclick;dblclick;dblclick;dblclick;click;click');
 objElemento.setstrValidarColumnasGrid(';requerido-es validate-number-es;requerido-es validate-number-es;;;;');
*/
 objElemento.setstrCampos('materiales.DESCRIPCION;materiales.IDTIPOMATERIAL;materiales.CANTIDAD;materiales.IMPORTE;materiales.IDTAREA;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrTipoEditor('NORMAL;AUTO;NORMAL;NORMAL;AUTO;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrCamposDec('Referencia;Descripción;Cantidad;Importe;Tarea;Editar;Borrar');
 objElemento.setstrCamposWidth('14%;28%;14%;14%;18%;5%;5%');
 objElemento.setstrLinksUlContentServlet(';/instelec/Tipomateriales/TipomaterialesUlContentServlet;;;/instelec/Tareas/TareasUlContentServlet;;'); 
 objElemento.setstrMetodosController('DescripcionMaterialesParsed;IdtipomaterialMaterialesParsed;CantidadMaterialesParsed;ImporteMaterialesParsed;IdtareaMaterialesParsed;EditMateriales;DeleteMateriales');
 objElemento.setstrLinksUpdateServlet('/instelec/Materiales/UpdateDescripcionServlet;/instelec/Materiales/UpdateIdtipomaterialServlet;/instelec/Materiales/UpdateCantidadServlet;/instelec/Materiales/UpdateImporteServlet;/instelec/Materiales/UpdateIdtareaServlet;editar;borrar'); 
 objElemento.setstrEsOrdenable('1;1;1;1;1;0;0');  
 objElemento.setstrEventos('dblclick;dblclick;dblclick;dblclick;dblclick;click;click');
 objElemento.setstrValidarColumnasGrid(';;requerido-es validate-number-es;requerido-es validate-number-es;;;');
 
 objElemento.setstrFormCampos('materiales.IDMATERIAL;materiales.DESCRIPCION;materiales.IDTAREA;materiales.IDTIPOMATERIAL;materiales.CANTIDAD;materiales.IMPORTE;materiales.IMPORTECALCULADO'); 
 objElemento.setstrFormCamposOblig('1;1;1;1;1;1;1'); 
 objElemento.setstrFormTipoEditor('HIDDEN;NORMAL;AUTO;AUTO;NORMAL;NORMAL;LECTURA');
 objElemento.setstrFormCamposDec('Idmaterial;Referencia;Tarea;Tipo;Cantidad;Importe (ud.);Cálculo');
 objElemento.setstrFormCamposWidth('250px;250px;300px;250px;250px;250px;140px'); 
 objElemento.setstrFormLinksUlContentServlet(';;/instelec/Tareas/TareasUlContentServlet;/instelec/Tipomateriales/TipomaterialesUlContentServlet;;;');
 objElemento.setstrFormLinksElementServlet(';;/instelec/Materiales/MaterialesTareasServlet;/instelec/Materiales/MaterialesTipomaterialesServlet;;;'); 
 objElemento.setstrFormMetodosController('Idmaterial;DescripcionMaterialesParsed;IdtareaMaterialesParsed;IdtipomaterialMaterialesParsed;CantidadMaterialesParsed;ImporteMaterialesParsed;ImporteCalculadoMaterialesParsed');  
 objElemento.setstrValidarCamposForm(' requerido-es; requerido-es;requerido-es;requerido-es;requerido-es validate-number-es; requerido-es validate-number-es;');
 objElemento.setstrFormCabeceraLinks('');
 objElemento.setstrFormCabeceraFunctions(''); 
 objElemento.setstrCabeceraLinks('Tareas;Tipo de materiales');
 objElemento.setstrCabeceraFunctions('verTareas();verTipomateriales()');  
 objElemento.setstrCabeceraIds('tareas.IDTAREA;tipomateriales.IDTIPOMATERIAL');  
 objElemento.setstrLinkDetallePdfServlet('/instelec/Materiales/GetMaterialesDetallePdfServlet'); 
 objElemento.setstrLinkDetallePdfServletDec('Imprimir');   
 objElemento.setstrLinkListaPdfServlet('/instelec/Materiales/MaterialesTableContentPdfServlet');   
 objElemento.setstrLinkListaPdfServletDec('Imprimir'); 
 objElemento.setstrFiltroLinks('');
 objElemento.setstrFiltroFunctions(''); 
 objElemento.setstrSeparadorFecha('-');
 objElemento.setstrSeparadorHora(':');   
 cargaQueryGrid();
 cargaGrid();
 crear();
 } 
 function verTipomateriales()
{
 objElemento.setiModoVisualizacion('1');
 objElemento.setviewedRows('14');
 objElemento.setstrTotalRegistros('0');
 objElemento.setstrGap('0');
 objElemento.setstrTableId('Tipomateriales');   
 objElemento.setstrFunction('verTipomateriales()');
 objElemento.setstrTituloLista('Lista de Tipo de materiales');
 objElemento.setstrTituloForm('Tipo de materiales');  
 objElemento.settableContentServlet('/instelec/Tipomateriales/TipomaterialesTableContentServlet'); 
 objElemento.setstrLinkAddServlet('/instelec/Tipomateriales/AddTipomaterialesServlet');
 objElemento.setstrLinkDeleteServlet('/instelec/Tipomateriales/DeleteTipomaterialesServlet'); 
 objElemento.setstrLinkDuplicarServlet('');
 objElemento.setstrLinkEditServlet('/instelec/Tipomateriales/TipomaterialesElementServlet');  
 objElemento.setstrLinkEditParam('tipomateriales.IDTIPOMATERIAL='); 
 objElemento.setstrCampos('tipomateriales.DESCRIPCION;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrTipoEditor('NORMAL;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrCamposDec('Descripción;Hijos;Editar;Borrar');
 objElemento.setstrCamposWidth('85%;5%;5%;5%');
 objElemento.setstrLinksUlContentServlet(';;;'); 
 objElemento.setstrMetodosController('DescripcionTipomaterialesParsed;HijosMaterialesTipomateriales;EditTipomateriales;DeleteTipomateriales');
 objElemento.setstrLinksUpdateServlet('/instelec/Tipomateriales/UpdateDescripcionServlet;hijos;editar;borrar'); 
 objElemento.setstrEsOrdenable('1;0;0;0');  
 objElemento.setstrEventos('dblclick;click;click;click');
 objElemento.setstrValidarColumnasGrid(' validation-max-300-es;;;');
 objElemento.setstrFormCampos('tipomateriales.IDTIPOMATERIAL;tipomateriales.DESCRIPCION'); 
 objElemento.setstrFormCamposOblig('1;1'); 
 objElemento.setstrFormTipoEditor('HIDDEN;NORMAL');
 objElemento.setstrFormCamposDec('Idtipomaterial;Descripción');
 objElemento.setstrFormCamposWidth('350px;600px'); 
 objElemento.setstrFormLinksUlContentServlet(';');
 objElemento.setstrFormLinksElementServlet(';'); 
 objElemento.setstrFormMetodosController('Idtipomaterial;DescripcionTipomaterialesParsed');  
 objElemento.setstrValidarCamposForm(' requerido-es; requerido-es validation-max-300-es');
 objElemento.setstrFormCabeceraLinks('Materiales');
 objElemento.setstrFormCabeceraFunctions('verMateriales()'); 
 objElemento.setstrCabeceraLinks('');
 objElemento.setstrCabeceraFunctions('');  
 objElemento.setstrCabeceraIds('');  
 objElemento.setstrLinkDetallePdfServlet('/instelec/Tipomateriales/GetTipomaterialesDetallePdfServlet'); 
 objElemento.setstrLinkDetallePdfServletDec('Imprimir');   
 objElemento.setstrLinkListaPdfServlet('/instelec/Tipomateriales/TipomaterialesTableContentPdfServlet');  
 objElemento.setstrLinkListaPdfServletDec('Imprimir');  
 objElemento.setstrFiltroLinks('');
 objElemento.setstrFiltroFunctions(''); 
 objElemento.setstrSeparadorFecha('-');
 objElemento.setstrSeparadorHora(':');   
 cargaQueryGrid();
 cargaGrid();
 crear();
 } 
 function verTipotareas()
{
 objElemento.setiModoVisualizacion('1');
 objElemento.setviewedRows('14');
 objElemento.setstrTotalRegistros('0');
 objElemento.setstrGap('0');
 objElemento.setstrTableId('Tipotareas');   
 objElemento.setstrFunction('verTipotareas()');
 objElemento.setstrTituloLista('Lista de Tipo de tareas');
 objElemento.setstrTituloForm('Tipo de tareas');  
 objElemento.settableContentServlet('/instelec/Tipotareas/TipotareasTableContentServlet'); 
 objElemento.setstrLinkAddServlet('/instelec/Tipotareas/AddTipotareasServlet');
 objElemento.setstrLinkDeleteServlet('/instelec/Tipotareas/DeleteTipotareasServlet'); 
 objElemento.setstrLinkDuplicarServlet('');
 objElemento.setstrLinkEditServlet('/instelec/Tipotareas/TipotareasElementServlet');  
 objElemento.setstrLinkEditParam('tipotareas.IDTIPOTAREA='); 
 objElemento.setstrCampos('tipotareas.DESCRIPCION;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrTipoEditor('NORMAL;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrCamposDec('Descripción;Hijos;Editar;Borrar');
 objElemento.setstrCamposWidth('85%;5%;5%;5%');
 objElemento.setstrLinksUlContentServlet(';;;'); 
 objElemento.setstrMetodosController('DescripcionTipotareasParsed;HijosTareasTipotareas;EditTipotareas;DeleteTipotareas');
 objElemento.setstrLinksUpdateServlet('/instelec/Tipotareas/UpdateDescripcionServlet;hijos;editar;borrar'); 
 objElemento.setstrEsOrdenable('1;0;0;0');  
 objElemento.setstrEventos('dblclick;click;click;click');
 objElemento.setstrValidarColumnasGrid(' validation-max-300-es;;;');
 objElemento.setstrFormCampos('tipotareas.IDTIPOTAREA;tipotareas.DESCRIPCION'); 
 objElemento.setstrFormCamposOblig('1;1'); 
 objElemento.setstrFormTipoEditor('HIDDEN;NORMAL');
 objElemento.setstrFormCamposDec('Idtipotarea;Descripción');
 objElemento.setstrFormCamposWidth('350px;600px'); 
 objElemento.setstrFormLinksUlContentServlet(';');
 objElemento.setstrFormLinksElementServlet(';'); 
 objElemento.setstrFormMetodosController('Idtipotarea;DescripcionTipotareasParsed');  
 objElemento.setstrValidarCamposForm(' requerido-es;requerido-es validation-max-300-es');
 objElemento.setstrFormCabeceraLinks('Tareas');
 objElemento.setstrFormCabeceraFunctions('verTareas()'); 
 objElemento.setstrCabeceraLinks('');
 objElemento.setstrCabeceraFunctions('');  
 objElemento.setstrCabeceraIds('');  
 objElemento.setstrLinkDetallePdfServlet('/instelec/Tipotareas/GetTipotareasDetallePdfServlet'); 
 objElemento.setstrLinkDetallePdfServletDec('Imprimir');   
 objElemento.setstrLinkListaPdfServlet('/instelec/Tipotareas/TipotareasTableContentPdfServlet');  
 objElemento.setstrLinkListaPdfServletDec('Imprimir');  
 objElemento.setstrFiltroLinks('');
 objElemento.setstrFiltroFunctions(''); 
 objElemento.setstrSeparadorFecha('-');
 objElemento.setstrSeparadorHora(':');   
 cargaQueryGrid();
 cargaGrid();
 crear();
 } 
 function verCategorias()
{
 objElemento.setiModoVisualizacion('1');
 objElemento.setviewedRows('14');
 objElemento.setstrTotalRegistros('0');
 objElemento.setstrGap('0');
 objElemento.setstrTableId('Categorias');   
 objElemento.setstrFunction('verCategorias()');
 objElemento.setstrTituloLista('Lista de Categorias');
 objElemento.setstrTituloForm('Categorias');  
 objElemento.settableContentServlet('/instelec/Categorias/CategoriasTableContentServlet'); 
 objElemento.setstrLinkAddServlet('/instelec/Categorias/AddCategoriasServlet');
 objElemento.setstrLinkDeleteServlet('/instelec/Categorias/DeleteCategoriasServlet'); 
 objElemento.setstrLinkDuplicarServlet('');
 objElemento.setstrLinkEditServlet('/instelec/Categorias/CategoriasElementServlet');  
 objElemento.setstrLinkEditParam('categorias.IDCATEGORIA='); 
 objElemento.setstrCampos('categorias.DESCRIPCION;categorias.COSTE;FREE_HIJOS;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrTipoEditor('NORMAL;NORMAL;FREE_HIJOS;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrCamposDec('Descripción;Coste;Hijos;Hijos;Editar;Borrar');
 objElemento.setstrCamposWidth('60%;20%;5%;5%;5%;5%');
 objElemento.setstrLinksUlContentServlet(';;;;;'); 
 objElemento.setstrMetodosController('DescripcionCategoriasParsed;CosteCategoriasParsed;HijosTrabajadoresCategorias;HijosTareasCategorias;EditCategorias;DeleteCategorias');
 objElemento.setstrLinksUpdateServlet('/instelec/Categorias/UpdateDescripcionServlet;/instelec/Categorias/UpdateCosteServlet;hijos;hijos;editar;borrar'); 
 objElemento.setstrEsOrdenable('1;1;0;0;0;0');  
 objElemento.setstrEventos('dblclick;dblclick;click;click;click;click');
 objElemento.setstrValidarColumnasGrid(' validation-max-300-es; requerido-es validate-number-es;;;;');
 objElemento.setstrFormCampos('categorias.IDCATEGORIA;categorias.DESCRIPCION;categorias.COSTE'); 
 objElemento.setstrFormCamposOblig('1;1;1'); 
 objElemento.setstrFormTipoEditor('HIDDEN;NORMAL;NORMAL');
 objElemento.setstrFormCamposDec('Idcategoria;Descripción;Coste');
 objElemento.setstrFormCamposWidth('350px;400px;350px'); 
 objElemento.setstrFormLinksUlContentServlet(';;');
 objElemento.setstrFormLinksElementServlet(';;'); 
 objElemento.setstrFormMetodosController('Idcategoria;DescripcionCategoriasParsed;CosteCategoriasParsed');  
 objElemento.setstrValidarCamposForm(' requerido-es; requerido-es validation-max-300-es; requerido-es validate-number-es');
 objElemento.setstrFormCabeceraLinks('Trabajadores;Tareas');
 objElemento.setstrFormCabeceraFunctions('verTrabajadores();verTareas()'); 
 objElemento.setstrCabeceraLinks('');
 objElemento.setstrCabeceraFunctions('');  
 objElemento.setstrCabeceraIds('');  
 objElemento.setstrLinkDetallePdfServlet('/instelec/Categorias/GetCategoriasDetallePdfServlet'); 
 objElemento.setstrLinkDetallePdfServletDec('Imprimir');   
 objElemento.setstrLinkListaPdfServlet('/instelec/Categorias/CategoriasTableContentPdfServlet');  
 objElemento.setstrLinkListaPdfServletDec('Imprimir');  
 objElemento.setstrFiltroLinks('');
 objElemento.setstrFiltroFunctions(''); 
 objElemento.setstrSeparadorFecha('-');
 objElemento.setstrSeparadorHora(':');  
 cargaQueryGrid();
 cargaGrid();
 crear();
 } 
 function verProvincias()
{
 objElemento.setiModoVisualizacion('0');
 objElemento.setviewedRows('20');
 objElemento.setstrTotalRegistros('0');
 objElemento.setstrGap('0');
 objElemento.setstrTableId('Provincias');   
 objElemento.setstrFunction('verProvincias()');
 objElemento.setstrTituloLista('Lista de Provincias');
 objElemento.setstrTituloForm('Provincias');  
 objElemento.settableContentServlet('/instelec/Provincias/ProvinciasTableContentServlet'); 
 objElemento.setstrLinkAddServlet('/instelec/Provincias/AddProvinciasServlet');
 objElemento.setstrLinkDeleteServlet('/instelec/Provincias/DeleteProvinciasServlet'); 
 objElemento.setstrLinkDuplicarServlet('');
 objElemento.setstrLinkEditServlet('/instelec/Provincias/ProvinciasElementServlet');  
 objElemento.setstrLinkEditParam('provincias.IDPROVINCIA='); 
 objElemento.setstrCampos('provincias.NOMBRE;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrTipoEditor('NORMAL;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrCamposDec('Nombre;Hijos;Editar;Borrar');
 objElemento.setstrCamposWidth('85%;5%;5%;5%');
 objElemento.setstrLinksUlContentServlet(';;;'); 
 objElemento.setstrMetodosController('NombreProvinciasParsed;HijosLocalidadesProvincias;EditProvincias;DeleteProvincias');
 objElemento.setstrLinksUpdateServlet('/instelec/Provincias/UpdateNombreServlet;hijos;editar;borrar'); 
 objElemento.setstrEsOrdenable('1;0;0;0');  
 objElemento.setstrEventos('dblclick;click;click;click');
 objElemento.setstrValidarColumnasGrid(' validation-max-50-es;;;');
 objElemento.setstrFormCampos('provincias.IDPROVINCIA;provincias.NOMBRE'); 
 objElemento.setstrFormCamposOblig(';'); 
 objElemento.setstrFormTipoEditor('HIDDEN;NORMAL');
 objElemento.setstrFormCamposDec('Idprovincia;Nombre');
 objElemento.setstrFormCamposWidth('350px;350px'); 
 objElemento.setstrFormLinksUlContentServlet(';');
 objElemento.setstrFormLinksElementServlet(';'); 
 objElemento.setstrFormMetodosController('Idprovincia;NombreProvinciasParsed');  
 objElemento.setstrValidarCamposForm(' requerido-es; validation-max-50-es');
 objElemento.setstrFormCabeceraLinks('Localidades');
 objElemento.setstrFormCabeceraFunctions('verLocalidades()'); 
 objElemento.setstrCabeceraLinks('');
 objElemento.setstrCabeceraFunctions('');  
 objElemento.setstrCabeceraIds('');  
 objElemento.setstrLinkDetallePdfServlet('/instelec/Provincias/GetProvinciasDetallePdfServlet'); 
 objElemento.setstrLinkDetallePdfServletDec('Imprimir');   
 objElemento.setstrLinkListaPdfServlet('/instelec/Provincias/ProvinciasTableContentPdfServlet');  
 objElemento.setstrLinkListaPdfServletDec('Imprimir');  
 objElemento.setstrFiltroLinks('');
 objElemento.setstrFiltroFunctions(''); 
 objElemento.setstrSeparadorFecha('-');
 objElemento.setstrSeparadorHora(':');   
 cargaQueryGrid();
 cargaGrid();
 crear();
 } 
 function verLocalidades()
{
 objElemento.setiModoVisualizacion('0');
 objElemento.setviewedRows('20');
 objElemento.setstrTotalRegistros('0');
 objElemento.setstrGap('0');
 objElemento.setstrTableId('Localidades');   
 objElemento.setstrFunction('verLocalidades()');
 objElemento.setstrTituloLista('Lista de Localidades');
 objElemento.setstrTituloForm('Localidades');  
 objElemento.settableContentServlet('/instelec/Localidades/LocalidadesTableContentServlet'); 
 objElemento.setstrLinkAddServlet('/instelec/Localidades/AddLocalidadesServlet');
 objElemento.setstrLinkDeleteServlet('/instelec/Localidades/DeleteLocalidadesServlet'); 
 objElemento.setstrLinkDuplicarServlet('');
 objElemento.setstrLinkEditServlet('/instelec/Localidades/LocalidadesElementServlet');  
 objElemento.setstrLinkEditParam('localidades.IDLOCALIDAD='); 
 objElemento.setstrCampos('localidades.IDPROVINCIA;localidades.NOMBRE;FREE_HIJOS;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrTipoEditor('AUTO_3;NORMAL;FREE_HIJOS;FREE_HIJOS;FREE_EDITAR;FREE_BORRAR'); 
 objElemento.setstrCamposDec('Idprovincia;Nombre;Hijos;Hijos;Editar;Borrar');
 objElemento.setstrCamposWidth('40%;40%;5%;5%;5%;5%');
 objElemento.setstrLinksUlContentServlet('/instelec/Provincias/ProvinciasUlContentServlet;;;;;'); 
 objElemento.setstrMetodosController('IdprovinciaLocalidadesParsed;NombreLocalidadesParsed;HijosClientesLocalidades;HijosTrabajadoresLocalidades;EditLocalidades;DeleteLocalidades');
 objElemento.setstrLinksUpdateServlet('/instelec/Localidades/UpdateIdprovinciaServlet;/instelec/Localidades/UpdateNombreServlet;hijos;hijos;editar;borrar'); 
 objElemento.setstrEsOrdenable('1;1;0;0;0;0');  
 objElemento.setstrEventos('dblclick;dblclick;click;click;click;click');
 objElemento.setstrValidarColumnasGrid('; validation-max-50-es;;;;');
 objElemento.setstrFormCampos('localidades.IDLOCALIDAD;localidades.IDPROVINCIA;localidades.NOMBRE'); 
 objElemento.setstrFormCamposOblig(';;'); 
 objElemento.setstrFormTipoEditor('HIDDEN;AUTO_3;NORMAL');
 objElemento.setstrFormCamposDec('Idlocalidad;Provincia;Nombre');
 objElemento.setstrFormCamposWidth('350px;350px;350px'); 
 objElemento.setstrFormLinksUlContentServlet(';/instelec/Provincias/ProvinciasUlContentServlet;');
 objElemento.setstrFormLinksElementServlet(';/instelec/Localidades/LocalidadesProvinciasServlet;'); 
 objElemento.setstrFormMetodosController('Idlocalidad;IdprovinciaLocalidadesParsed;NombreLocalidadesParsed');  
 objElemento.setstrValidarCamposForm(' requerido-es;; validation-max-50-es');
 objElemento.setstrFormCabeceraLinks('Clientes;Trabajadores');
 objElemento.setstrFormCabeceraFunctions('verClientes();verTrabajadores()'); 
 objElemento.setstrCabeceraLinks('Provincias');
 objElemento.setstrCabeceraFunctions('verProvincias()');  
 objElemento.setstrCabeceraIds('provincias.IDPROVINCIA');  
 objElemento.setstrLinkDetallePdfServlet('/instelec/Localidades/GetLocalidadesDetallePdfServlet'); 
 objElemento.setstrLinkDetallePdfServletDec('Imprimir');   
 objElemento.setstrLinkListaPdfServlet('/instelec/Localidades/LocalidadesTableContentPdfServlet');  
 objElemento.setstrLinkListaPdfServletDec('Imprimir');  
 objElemento.setstrFiltroLinks('');
 objElemento.setstrFiltroFunctions(''); 
 objElemento.setstrSeparadorFecha('-');
 objElemento.setstrSeparadorHora(':');   
 cargaQueryGrid();
 cargaGrid();
 crear();
 } 
 