
package net.idtoki.instelec.model;


import java.util.logging.Logger;

import net.zylk.tools.format.FormatUtils;

import org.apache.torque.TorqueException;
import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Aug 10 13:35:35 CEST 2006]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Categorias
    extends net.idtoki.instelec.model.BaseCategorias
    implements Persistent
{

private static final Logger logger = Logger.getLogger("net.idtoki.instelec.model.Categorias");


		
	public String getIdcategoriaCategoriasParsed()
	{
		return FormatUtils.genericParsedStr(this.getIdcategoria() + "");
		}					

		
	public String getDescripcionCategoriasParsed()
	{
				return FormatUtils.genericParsedStr(this.getDescripcion());		
				}					

		
	public String getCosteCategoriasParsed()
	{
		return FormatUtils.genericParsedStr(this.getCoste() + "");	 
		}					


	public String getPathCategoriasParsed(String strQueryString) throws TorqueException
	{	
	  String a = "";
	  a = a + this.getDescripcionCategoriasParsed();  
	  return a;
	}

	public String getULContentCategoriasParsed() throws TorqueException
	{
		return FormatUtils.genericParsedStr(this.getIdcategoria() + "-" + this.getDescripcionCategoriasParsed());	
	}	

	public String getHijosTrabajadoresCategorias()
	{
		return "<a href='#' class='hijos' id='getHijosTrabajadoresCategorias" + this.getIdcategoria() + "' title='Trabajadores'>&#160;&#160;&#160;&#160;</a>";
	}
	public String getHijosTareasCategorias()
	{
		return "<a href='#' class='hijos' id='getHijosTareasCategorias" + this.getIdcategoria() + "' title='Tareas'>&#160;&#160;&#160;&#160;</a>";
	}
	
	public String getDeleteCategorias()
	{
		return "<a href='#' class='eliminar' id='getDeleteCategorias" + this.getIdcategoria() + "'>&#160;&#160;&#160;&#160;</a>";
	}	
	public String getEditCategorias()
	{
		return "<a href='#' class='edicion' id='getEditCategorias" + this.getIdcategoria() + "'>&#160;&#160;&#160;&#160;</a>";
	}

}
