package net.idtoki.instelec.model;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Aug 10 13:35:35 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class ProvinciasPeer
    extends net.idtoki.instelec.model.BaseProvinciasPeer
{
}
