
package net.idtoki.instelec.model;


import java.util.logging.Logger;

import net.zylk.tools.format.FormatUtils;

import org.apache.torque.TorqueException;
import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Aug 10 13:35:35 CEST 2006]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Provincias
    extends net.idtoki.instelec.model.BaseProvincias
    implements Persistent
{

private static final Logger logger = Logger.getLogger("net.idtoki.instelec.model.Provincias");


		
	public String getIdprovinciaProvinciasParsed()
	{
		return FormatUtils.genericParsedStr(this.getIdprovincia() + "");
		}					

		
	public String getNombreProvinciasParsed()
	{
				return FormatUtils.genericParsedStr(this.getNombre());		
				}					


	public String getPathProvinciasParsed(String strQueryString) throws TorqueException
	{	
	  String a = "";
	  a = a + this.getNombreProvinciasParsed();  
	  return a;
	}

	public String getULContentProvinciasParsed() throws TorqueException
	{
		return FormatUtils.genericParsedStr(this.getIdprovincia() + "-" + this.getNombreProvinciasParsed());	
	}	

	public String getHijosLocalidadesProvincias()
	{
		return "<a href='#' class='hijos' id='getHijosLocalidadesProvincias" + this.getIdprovincia() + "' title='Localidades'>&#160;&#160;&#160;&#160;</a>";
	}
	
	public String getDeleteProvincias()
	{
		return "<a href='#' class='eliminar' id='getDeleteProvincias" + this.getIdprovincia() + "'>&#160;&#160;&#160;&#160;</a>";
	}	
	public String getEditProvincias()
	{
		return "<a href='#' class='edicion' id='getEditProvincias" + this.getIdprovincia() + "'>&#160;&#160;&#160;&#160;</a>";
	}

}
