
package net.idtoki.instelec.model;


import java.util.logging.Logger;

import net.zylk.tools.format.FormatUtils;

import org.apache.torque.TorqueException;
import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Aug 10 13:35:35 CEST 2006]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Tipotareas
    extends net.idtoki.instelec.model.BaseTipotareas
    implements Persistent
{

private static final Logger logger = Logger.getLogger("net.idtoki.instelec.model.Tipotareas");


		
	public String getIdtipotareaTipotareasParsed()
	{
		return FormatUtils.genericParsedStr(this.getIdtipotarea() + "");
		}					

		
	public String getDescripcionTipotareasParsed()
	{
				return FormatUtils.genericParsedStr(this.getDescripcion());		
				}					


	public String getPathTipotareasParsed(String strQueryString) throws TorqueException
	{	
	  String a = "";
	  a = a + this.getDescripcionTipotareasParsed();  
	  return a;
	}

	public String getULContentTipotareasParsed() throws TorqueException
	{
		return FormatUtils.genericParsedStr(this.getIdtipotarea() + "-" + this.getDescripcionTipotareasParsed());	
	}	

	public String getHijosTareasTipotareas()
	{
		return "<a href='#' class='hijos' id='getHijosTareasTipotareas" + this.getIdtipotarea() + "' title='Tareas'>&#160;&#160;&#160;&#160;</a>";
	}
	
	public String getDeleteTipotareas()
	{
		return "<a href='#' class='eliminar' id='getDeleteTipotareas" + this.getIdtipotarea() + "'>&#160;&#160;&#160;&#160;</a>";
	}	
	public String getEditTipotareas()
	{
		return "<a href='#' class='edicion' id='getEditTipotareas" + this.getIdtipotarea() + "'>&#160;&#160;&#160;&#160;</a>";
	}

}
