package net.idtoki.instelec.controller;

import java.util.logging.Logger;
import net.zylk.web.controller.LoginController;


/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jul 27 14:02:11 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */

public class AppLoginController extends LoginController
{
 private static final Logger logger = Logger.getLogger("net.idtoki.instelec.controller.AppLoginController");

 public void init()
 {
  super.init();
  //Aqui se registran los metodos que no se quieran repetir de otros sitios.
  //por ejemplo igual quieres tener los metodos de generacion de ajax
  // en un paquete aparte y no copiarlos por aqui,  sino tenerlos disponibles
  //para todas las aplicaciones sin repetirlos en todos los sitios, pues los registras
  //y punto!!
  //setDefaultURL("/General/HomePageServlet");
 }
}