package net.idtoki.instelec.controller;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.ResourceBundle;
import java.util.logging.Logger;

import javax.servlet.ServletConfig;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamSource;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

import net.idtoki.instelec.manager.CategoriasManager;
import net.idtoki.instelec.group.CategoriasGroupBean;
import net.idtoki.instelec.helper.CategoriasHelper;
import net.idtoki.instelec.model.CategoriasPeer;
import net.idtoki.instelec.model.Categorias;


import net.idtoki.instelec.helper.TrabajadoresHelper;
import net.idtoki.instelec.helper.TareasHelper;


import net.zylk.tools.ajax.AjaxUtils;
import net.zylk.tools.ajax.AjaxUtils.DinamicGridBean;
import net.zylk.tools.format.FormatUtils;
import net.zylk.tools.pdf.PdfUtils;
import net.zylk.tools.xml.XmlUtils;
import net.zylk.torque.TorqueUtils;
import net.zylk.web.WebUtils;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Aug 10 13:35:35 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
 
 
public class CategoriasController
    extends net.idtoki.instelec.controller.BaseCategoriasController
{
 private static final Logger logger = Logger.getLogger("net.idtoki.instelec.controller.CategoriasController");
 private TransformerFactory tFactory = TransformerFactory.newInstance();
 private Transformer categorias_transformer = null;  
 private Transformer categoriass_transformer = null; 

 public void init(ServletConfig config)
 {
	super.init();
	ResourceBundle resource = ResourceBundle.getBundle("net/idtoki/instelec/app/config/app-config");
	File categorias = new File(resource.getString("app.xsl.templates.dir")+"/PdfCategorias.xslt");
	Source xslSource = new StreamSource(categorias);
	File categoriass = new File(resource.getString("app.xsl.templates.dir")+"/PdfListaCategorias.xslt");
	Source xslSourceT = new StreamSource(categoriass); 	  
	try{
		categorias_transformer = tFactory.newTransformer(xslSource);
		categoriass_transformer = tFactory.newTransformer(xslSourceT);			  
	}catch (Exception e){
	  e.printStackTrace();
	}
 }


//Función para la inserción/actualización de registros

public void serviceAddCategorias(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 //Con esto se consigue transformar el request a UTF
	 //para temas de acentos y otros caracteres
	 utf8RequestService(request);

	 //recojo los parametros del formulario y doy de alta un nuevo elmento
	 try
	 {
		 Categorias elCategorias = CategoriasHelper.createObj(request);
		 CategoriasGroupBean gbCategorias = new CategoriasGroupBean();
		 gbCategorias.setElemento(elCategorias);
		 gbCategorias.save();
	 }
	 catch(TorqueException te)
	 {
		 response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
	 }
 }


//Función para la eliminación de un registro
//este método invoca al método public void deleteCategorias(int idBorrar)
//definido en el CategoriasManager
 public void serviceDeleteCategorias(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 int idBorrar=-1;
	 idBorrar=WebUtils.getintParam(request, "borrarId");
	 if (idBorrar!=-1)
 		 if (CategoriasManager.borraCategorias(idBorrar))
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlOKResponse("ISO-8859-1"));
		 else
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlNotOKResponse("ISO-8859-1"));			 
 }


// Funciones para las ordenaciones y filtrados de información

 private Criteria ordenacion(Criteria c,String CampoOrdenacion,String OrdenOrdenacion) 
 { 
 	if((OrdenOrdenacion != null )&& (OrdenOrdenacion.compareTo("ASC")==0))
 		if ((CampoOrdenacion != null))
 		{
 			c.addAscendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	if  ((OrdenOrdenacion != null) && (OrdenOrdenacion.compareTo("DESC")==0))
 		if ((CampoOrdenacion != null))
		{
 			c.addDescendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	return c;
 }

private Criteria filtro(Criteria c,int filtro) 
{ 
	String cadena = null;
	 switch (filtro)
	 {
	 case 1:
		  //Caso uno de Filtrado
		  //c.add(Campo,valor);
		  break;
	 case 2:
		  //Caso dos de Filtrado
		  //c.add(Campo,valor);
		  break;
	 default:
		 //caso por defecto
		 break;
	 }
	return c;
}

 public StringBuffer replaceStringBuffer (StringBuffer strBA, String strOrigen, String strDestino) 
 {
	 return new StringBuffer(strBA.toString().replaceAll(strOrigen,strDestino));
 }

 private Criteria criteriaCategoriasTableContent(HttpServletRequest request,Criteria c) throws IOException, ServletException
 {
 	String param = "";	 
	  String paramSortCol =  WebUtils.getStringParam(request, "sort_col");
	  String paramSortDir =  WebUtils.getStringParam(request, "sort_dir");
	  int paramFiltro =  WebUtils.getintParam(request, "filtro");
	  c = ordenacion(c,paramSortCol,paramSortDir);
	  c = filtro(c,paramFiltro);

 	  return c;
 } 
 
 public String getPathElementCategorias(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;
	 int claveFkId=-1;	 
	 claveId=WebUtils.getintParam(request, "categorias.IDCATEGORIA");
	 if (claveId!=-1)
	 {
		c.add(CategoriasPeer.IDCATEGORIA, claveId);
		CategoriasGroupBean trgb = CategoriasManager.getCategoriass(c);							
		strPath = trgb.getCategorias(0).getPathCategoriasParsed(request.getQueryString());
	 }
	 return "<path>" + strPath + "</path>";
 } 
 
 public String getPathTableContentCategorias(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;	 
	 return "<path>" + strPath + "</path>";
 }  


public void  serviceCategoriasTableContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 utf8RequestService(request);
	 int numElemPedidosBD = 40;
	 int gap = 0;//gap = viewedRows - numElemVisiblesUltPag	  
	 DinamicGridBean dgb = WebUtils.getDinamicGridBeanParam(request,numElemPedidosBD,gap); 
	 Criteria c =CategoriasManager.buildSearchCriteria(dgb);
	 c =criteriaCategoriasTableContent(request,c);	 
	 CategoriasGroupBean cgb = CategoriasManager.getCategoriass(c);
	 dgb.setTotalSize(cgb.getTotalSize());
	  
	 String[] methodos= new String[] {
		CategoriasHelper.DESCRIPCION_GET_METHOD_NAME+"CategoriasParsed"
		,CategoriasHelper.COSTE_GET_METHOD_NAME+"CategoriasParsed"
		,"getHijosTrabajadoresCategorias"
		,"getHijosTareasCategorias"
		,"getEditCategorias"
		,"getDeleteCategorias"
	};
	 
	 StringBuffer cadena=null;
	 cadena = AjaxUtils.buildXmlAjaxResponseTableContentFromListObj(cgb.getAlmacen(),methodos,CategoriasHelper.IDCATEGORIA_GET_METHOD_NAME, dgb,"ISO-8859-1"); 
	 cadena.insert(cadena.indexOf("</ajax-response>"),"<response type='object' id='divPath'>" + getPathTableContentCategorias(request,response) + "</response>");
	 xmlResponseService(response,cadena); 
 }  

 public void serviceCategoriasUlContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] methodos= new String[] {
	 		"getULContentCategoriasParsed"
			 };
	 String param =  WebUtils.getStringParam(request, "value");
	 if(param==null || param.length() <= 0)
		 param =  WebUtils.getStringParam(request, new TrabajadoresHelper().getIdcategoriaName());
	 if(param==null || param.length() <= 0)
		 param =  WebUtils.getStringParam(request, new TareasHelper().getIdcategoriaName());
	 	 
	 CategoriasGroupBean mgb = CategoriasManager.getCategoriass(CategoriasManager.buildSearchCriteria(param));
	 simpleResponseService(response, AjaxUtils.buildAjaxULContentFromListObj(mgb.getAlmacen(),methodos, CategoriasHelper.COMPLEX_ID_GET_METHOD,"Categorias"));
 } 



 public void serviceCategoriasElement(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
  StringBuffer cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "categorias.IDCATEGORIA");
  if (claveId!=-1)
  {
	  c.add(CategoriasPeer.IDCATEGORIA, claveId);
  }
  c.addAscendingOrderByColumn(CategoriasPeer.IDCATEGORIA);
  CategoriasGroupBean trgb = CategoriasManager.getCategoriass(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  String [] parametros={
		CategoriasHelper.IDCATEGORIA_GET_METHOD_NAME
		,CategoriasHelper.DESCRIPCION_GET_METHOD_NAME+"CategoriasParsed"
		,CategoriasHelper.COSTE_GET_METHOD_NAME+"CategoriasParsed"
	  };
	  cadena=trgb.buildXml(parametros,null,"ISO-8859-1");	
	  cadena.insert(cadena.indexOf("</result>"),getPathElementCategorias(request,response));  
  }
  xmlResponseService(response, cadena);
 }  

 protected StringBuffer updateIdcategoriaResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(CategoriasManager.getCategorias(Integer.parseInt(a.get(0).toString())).getIdcategoriaCategoriasParsed());
 }  
 

 protected StringBuffer updateDescripcionResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(CategoriasManager.getCategorias(Integer.parseInt(a.get(0).toString())).getDescripcionCategoriasParsed());
 }  
 

 protected StringBuffer updateCosteResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(CategoriasManager.getCategorias(Integer.parseInt(a.get(0).toString())).getCosteCategoriasParsed());
 }  

 public void serviceGetCategoriasDetallePdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] getMethodos= new String[] {
		CategoriasHelper.IDCATEGORIA_GET_METHOD_NAME
		,CategoriasHelper.DESCRIPCION_GET_METHOD_NAME+"CategoriasParsed"
		,CategoriasHelper.COSTE_GET_METHOD_NAME+"CategoriasParsed"
			 };
	  
	 
	 CategoriasGroupBean tgb = new CategoriasGroupBean();
	 try
	{
		tgb.setElemento(CategoriasHelper.getCategorias(request));
	} catch (TorqueException e)
	{
		logger.severe(e.getMessage());
	}
	
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(getMethodos, null,"ISO-8859-1"),"n/a"," "), categorias_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=Categorias.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
	
 }  

 public void serviceCategoriasTableContentPdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
  	utf8RequestService(request);
  	Criteria c= new Criteria();
  	String paramQuery =  WebUtils.getStringParam(request, "query");
  	if ((paramQuery != null)&& (paramQuery.compareTo("")!=0) )
		c = CategoriasManager.buildSearchCriteria(paramQuery);   
  	c =criteriaCategoriasTableContent(request,c);	  
  	CategoriasGroupBean tgb = CategoriasManager.getCategoriass(c);
  
  	String[] methodos= new String[] {	
		CategoriasHelper.DESCRIPCION_GET_METHOD_NAME+"CategoriasParsed"
		,CategoriasHelper.COSTE_GET_METHOD_NAME+"CategoriasParsed"
			};
  
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(methodos, null,"ISO-8859-1"),"n/a"," "), categoriass_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=ListaCategorias.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
 }

}


