package net.idtoki.instelec.controller;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.ResourceBundle;
import java.util.logging.Logger;

import javax.servlet.ServletConfig;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamSource;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

import net.idtoki.instelec.manager.ClientesManager;
import net.idtoki.instelec.group.ClientesGroupBean;
import net.idtoki.instelec.helper.ClientesHelper;
import net.idtoki.instelec.model.ClientesPeer;
import net.idtoki.instelec.model.Clientes;

import net.idtoki.instelec.manager.LocalidadesManager;
import net.idtoki.instelec.group.LocalidadesGroupBean;
import net.idtoki.instelec.model.LocalidadesPeer;
import net.idtoki.instelec.helper.LocalidadesHelper;

import net.idtoki.instelec.helper.TrabajosHelper;


import net.zylk.tools.ajax.AjaxUtils;
import net.zylk.tools.ajax.AjaxUtils.DinamicGridBean;
import net.zylk.tools.format.FormatUtils;
import net.zylk.tools.pdf.PdfUtils;
import net.zylk.tools.xml.XmlUtils;
import net.zylk.torque.TorqueUtils;
import net.zylk.web.WebUtils;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Aug 10 13:35:35 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
 
 
public class ClientesController
    extends net.idtoki.instelec.controller.BaseClientesController
{
 private static final Logger logger = Logger.getLogger("net.idtoki.instelec.controller.ClientesController");
 private TransformerFactory tFactory = TransformerFactory.newInstance();
 private Transformer clientes_transformer = null;  
 private Transformer clientess_transformer = null; 

 public void init(ServletConfig config)
 {
	super.init();
	ResourceBundle resource = ResourceBundle.getBundle("net/idtoki/instelec/app/config/app-config");
	File clientes = new File(resource.getString("app.xsl.templates.dir")+"/PdfClientes.xslt");
	Source xslSource = new StreamSource(clientes);
	File clientess = new File(resource.getString("app.xsl.templates.dir")+"/PdfListaClientes.xslt");
	Source xslSourceT = new StreamSource(clientess); 	  
	try{
		clientes_transformer = tFactory.newTransformer(xslSource);
		clientess_transformer = tFactory.newTransformer(xslSourceT);			  
	}catch (Exception e){
	  e.printStackTrace();
	}
 }


//Función para la inserción/actualización de registros

public void serviceAddClientes(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 //Con esto se consigue transformar el request a UTF
	 //para temas de acentos y otros caracteres
	 utf8RequestService(request);

	 //recojo los parametros del formulario y doy de alta un nuevo elmento
	 try
	 {
		 Clientes elClientes = ClientesHelper.createObj(request);
		 ClientesGroupBean gbClientes = new ClientesGroupBean();
		 elClientes.setFechaalta(FormatUtils.ddmmaaaa2aaaammdd(elClientes.getFechaalta(),"-",""));
		 elClientes.setFechabaja(FormatUtils.ddmmaaaa2aaaammdd(elClientes.getFechabaja(),"-",""));
		 gbClientes.setElemento(elClientes);
		 gbClientes.save();
	 }
	 catch(TorqueException te)
	 {
		 response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
	 }
 }


//Función para la eliminación de un registro
//este método invoca al método public void deleteClientes(int idBorrar)
//definido en el ClientesManager
 public void serviceDeleteClientes(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 int idBorrar=-1;
	 idBorrar=WebUtils.getintParam(request, "borrarId");
	 if (idBorrar!=-1)
 		 if (ClientesManager.borraClientes(idBorrar))
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlOKResponse("ISO-8859-1"));
		 else
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlNotOKResponse("ISO-8859-1"));			 
 }


// Funciones para las ordenaciones y filtrados de información

 private Criteria ordenacion(Criteria c,String CampoOrdenacion,String OrdenOrdenacion) 
 { 
 	if((OrdenOrdenacion != null )&& (OrdenOrdenacion.compareTo("ASC")==0))
 		if ((CampoOrdenacion != null))
 		{
 			c.addAscendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	if  ((OrdenOrdenacion != null) && (OrdenOrdenacion.compareTo("DESC")==0))
 		if ((CampoOrdenacion != null))
		{
 			c.addDescendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	return c;
 }

private Criteria filtro(Criteria c,int filtro) 
{ 
	String cadena = null;
	 switch (filtro)
	 {
	 case 1:
		  //Caso uno de Filtrado
		  //c.add(Campo,valor);
		  break;
	 case 2:
		  //Caso dos de Filtrado
		  //c.add(Campo,valor);
		  break;
	 default:
		 //caso por defecto
		 break;
	 }
	return c;
}

 public StringBuffer replaceStringBuffer (StringBuffer strBA, String strOrigen, String strDestino) 
 {
	 return new StringBuffer(strBA.toString().replaceAll(strOrigen,strDestino));
 }

 private Criteria criteriaClientesTableContent(HttpServletRequest request,Criteria c) throws IOException, ServletException
 {
 	String param = "";	 
	 param =  WebUtils.getStringParam(request, new LocalidadesHelper().getIdlocalidadName());
	 if(param != null)
		 TorqueUtils.addEqualCriteria(c,ClientesPeer.IDLOCALIDAD,param);
	  String paramSortCol =  WebUtils.getStringParam(request, "sort_col");
	  String paramSortDir =  WebUtils.getStringParam(request, "sort_dir");
	  int paramFiltro =  WebUtils.getintParam(request, "filtro");
	  c = ordenacion(c,paramSortCol,paramSortDir);
	  c = filtro(c,paramFiltro);

 	  return c;
 } 
 
 public String getPathElementClientes(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;
	 int claveFkId=-1;	 
	 claveId=WebUtils.getintParam(request, "clientes.IDCLIENTE");
	 if (claveId!=-1)
	 {
		c.add(ClientesPeer.IDCLIENTE, claveId);
		ClientesGroupBean trgb = ClientesManager.getClientess(c);							
		strPath = trgb.getClientes(0).getPathClientesParsed(request.getQueryString());
	 }
	 return "<path>" + strPath + "</path>";
 } 
 
 public String getPathTableContentClientes(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;	 
	 claveId=WebUtils.getintParam(request, "localidades.IDLOCALIDAD");
	 if(claveId != -1){
		 strPath = LocalidadesManager.getLocalidades(claveId).getPathLocalidadesParsed(request.getQueryString());
	 }		 	 
	 return "<path>" + strPath + "</path>";
 }  


public void  serviceClientesTableContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 utf8RequestService(request);
	 int numElemPedidosBD = 40;
	 int gap = 0;//gap = viewedRows - numElemVisiblesUltPag	  
	 DinamicGridBean dgb = WebUtils.getDinamicGridBeanParam(request,numElemPedidosBD,gap); 
	 Criteria c =ClientesManager.buildSearchCriteria(dgb);
	 c =criteriaClientesTableContent(request,c);	 
	 ClientesGroupBean cgb = ClientesManager.getClientess(c);
	 dgb.setTotalSize(cgb.getTotalSize());
	  
	 String[] methodos= new String[] {
		//ClientesHelper.CIF_GET_METHOD_NAME+"ClientesParsed"
		//,ClientesHelper.FECHAALTA_GET_METHOD_NAME+"ClientesParsed"
		//,ClientesHelper.FECHABAJA_GET_METHOD_NAME+"ClientesParsed"
		ClientesHelper.NOMBRE_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.RAZONSOCIAL_GET_METHOD_NAME+"ClientesParsed"
		//,ClientesHelper.IDLOCALIDAD_GET_METHOD_NAME+"ClientesParsed"
		//,ClientesHelper.DIRECCION_GET_METHOD_NAME+"ClientesParsed"
		//,ClientesHelper.CP_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.TELEFONO_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.FAX_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.MOVIL_GET_METHOD_NAME+"ClientesParsed"
		//,ClientesHelper.EMAIL_GET_METHOD_NAME+"ClientesParsed"
		//,ClientesHelper.NUMEROCUENTA_GET_METHOD_NAME+"ClientesParsed"
		//,ClientesHelper.OBSERVACIONES_GET_METHOD_NAME+"ClientesParsed"
		,"getHijosTrabajosClientes"
		,"getEditClientes"
		,"getDeleteClientes"
	};
	 
	 StringBuffer cadena=null;
	 cadena = AjaxUtils.buildXmlAjaxResponseTableContentFromListObj(cgb.getAlmacen(),methodos,ClientesHelper.IDCLIENTE_GET_METHOD_NAME, dgb,"ISO-8859-1"); 
	 cadena.insert(cadena.indexOf("</ajax-response>"),"<response type='object' id='divPath'>" + getPathTableContentClientes(request,response) + "</response>");
	 xmlResponseService(response,cadena); 
 }  

 public void serviceClientesUlContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] methodos= new String[] {
	 		"getULContentClientesParsed"
			 };
	 String param =  WebUtils.getStringParam(request, "value");
	 if(param==null || param.length() <= 0)
		 param =  WebUtils.getStringParam(request, new TrabajosHelper().getIdclienteName());
	 	 
	 ClientesGroupBean mgb = ClientesManager.getClientess(ClientesManager.buildSearchCriteria(param));
	 simpleResponseService(response, AjaxUtils.buildAjaxULContentFromListObj(mgb.getAlmacen(),methodos, ClientesHelper.COMPLEX_ID_GET_METHOD,"Clientes"));
 } 



 public void serviceClientesElement(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
  StringBuffer cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "clientes.IDCLIENTE");
  if (claveId!=-1)
  {
	  c.add(ClientesPeer.IDCLIENTE, claveId);
  }
  c.addAscendingOrderByColumn(ClientesPeer.IDCLIENTE);
  ClientesGroupBean trgb = ClientesManager.getClientess(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  String [] parametros={
		ClientesHelper.IDCLIENTE_GET_METHOD_NAME
		,ClientesHelper.CIF_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.FECHAALTA_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.FECHABAJA_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.NOMBRE_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.RAZONSOCIAL_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.IDLOCALIDAD_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.DIRECCION_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.CP_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.TELEFONO_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.FAX_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.MOVIL_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.EMAIL_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.NUMEROCUENTA_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.OBSERVACIONES_GET_METHOD_NAME+"ClientesParsed"
	  };
	  cadena=trgb.buildXml(parametros,null,"ISO-8859-1");	
	  cadena.insert(cadena.indexOf("</result>"),getPathElementClientes(request,response));  
  }
  xmlResponseService(response, cadena);
 }  
 

 protected StringBuffer updateIdclienteResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(ClientesManager.getClientes(Integer.parseInt(a.get(0).toString())).getIdclienteClientesParsed());
 }  
 

 protected StringBuffer updateCifResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(ClientesManager.getClientes(Integer.parseInt(a.get(0).toString())).getCifClientesParsed());
 }  
 

 protected StringBuffer updateFechaaltaResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(ClientesManager.getClientes(Integer.parseInt(a.get(0).toString())).getFechaaltaClientesParsed());
 }  
 

 protected StringBuffer updateFechabajaResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(ClientesManager.getClientes(Integer.parseInt(a.get(0).toString())).getFechabajaClientesParsed());
 }  
 

 protected StringBuffer updateNombreResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(ClientesManager.getClientes(Integer.parseInt(a.get(0).toString())).getNombreClientesParsed());
 }  
 

 protected StringBuffer updateRazonsocialResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(ClientesManager.getClientes(Integer.parseInt(a.get(0).toString())).getRazonsocialClientesParsed());
 }  
 

 protected StringBuffer updateIdlocalidadResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(ClientesManager.getClientes(Integer.parseInt(a.get(0).toString())).getIdlocalidadClientesParsed());
 }  
 

 protected StringBuffer updateDireccionResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(ClientesManager.getClientes(Integer.parseInt(a.get(0).toString())).getDireccionClientesParsed());
 }  
 

 protected StringBuffer updateCpResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(ClientesManager.getClientes(Integer.parseInt(a.get(0).toString())).getCpClientesParsed());
 }  
 

 protected StringBuffer updateTelefonoResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(ClientesManager.getClientes(Integer.parseInt(a.get(0).toString())).getTelefonoClientesParsed());
 }  
 

 protected StringBuffer updateFaxResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(ClientesManager.getClientes(Integer.parseInt(a.get(0).toString())).getFaxClientesParsed());
 }  
 

 protected StringBuffer updateMovilResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(ClientesManager.getClientes(Integer.parseInt(a.get(0).toString())).getMovilClientesParsed());
 }  
 

 protected StringBuffer updateEmailResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(ClientesManager.getClientes(Integer.parseInt(a.get(0).toString())).getEmailClientesParsed());
 }  
 

 protected StringBuffer updateNumerocuentaResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(ClientesManager.getClientes(Integer.parseInt(a.get(0).toString())).getNumerocuentaClientesParsed());
 }  
 

 protected StringBuffer updateObservacionesResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(ClientesManager.getClientes(Integer.parseInt(a.get(0).toString())).getObservacionesClientesParsed());
 }  
 
 
 
 public void serviceClientesLocalidades(HttpServletRequest request, HttpServletResponse response) throws IOException, TorqueException, ServletException
 {
  String cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "localidades.IDLOCALIDAD");
  if (claveId!=-1)
  {
	  c.add(LocalidadesPeer.IDLOCALIDAD, claveId);
  }
  c.addAscendingOrderByColumn(LocalidadesPeer.IDLOCALIDAD);
  LocalidadesGroupBean trgb = LocalidadesManager.getLocalidadess(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  cadena = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>";
	  cadena = cadena + "<result><clientes.IDLOCALIDAD>" + trgb.getLocalidades(0).getULContentLocalidadesParsed()  + "</clientes.IDLOCALIDAD></result>";
  }
  
  xmlResponseService(response, new StringBuffer(cadena));
 }  
  			

 public void serviceGetClientesDetallePdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] getMethodos= new String[] {
		ClientesHelper.IDCLIENTE_GET_METHOD_NAME
		,ClientesHelper.CIF_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.FECHAALTA_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.FECHABAJA_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.NOMBRE_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.RAZONSOCIAL_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.IDLOCALIDAD_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.DIRECCION_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.CP_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.TELEFONO_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.FAX_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.MOVIL_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.EMAIL_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.NUMEROCUENTA_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.OBSERVACIONES_GET_METHOD_NAME+"ClientesParsed"
			 };
	  
	 
	 ClientesGroupBean tgb = new ClientesGroupBean();
	 try
	{
		tgb.setElemento(ClientesHelper.getClientes(request));
	} catch (TorqueException e)
	{
		logger.severe(e.getMessage());
	}
	
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(getMethodos, null,"ISO-8859-1"),"n/a"," "), clientes_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=Clientes.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
	
 }  

 public void serviceClientesTableContentPdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
  	utf8RequestService(request);
  	Criteria c= new Criteria();
  	String paramQuery =  WebUtils.getStringParam(request, "query");
  	if ((paramQuery != null)&& (paramQuery.compareTo("")!=0) )
		c = ClientesManager.buildSearchCriteria(paramQuery);   
  	c =criteriaClientesTableContent(request,c);	  
  	ClientesGroupBean tgb = ClientesManager.getClientess(c);
  
  	String[] methodos= new String[] {	
		ClientesHelper.CIF_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.FECHAALTA_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.FECHABAJA_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.NOMBRE_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.RAZONSOCIAL_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.IDLOCALIDAD_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.DIRECCION_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.CP_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.TELEFONO_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.FAX_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.MOVIL_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.EMAIL_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.NUMEROCUENTA_GET_METHOD_NAME+"ClientesParsed"
		,ClientesHelper.OBSERVACIONES_GET_METHOD_NAME+"ClientesParsed"
			};
  
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(methodos, null,"ISO-8859-1"),"n/a"," "), clientess_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=ListaClientes.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
 }

}


