package net.idtoki.instelec.controller;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.ResourceBundle;
import java.util.logging.Logger;

import javax.servlet.ServletConfig;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamSource;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

import net.idtoki.instelec.manager.LineasparteManager;
import net.idtoki.instelec.group.LineasparteGroupBean;
import net.idtoki.instelec.helper.LineasparteHelper;
import net.idtoki.instelec.model.LineaspartePeer;
import net.idtoki.instelec.model.Lineasparte;

import net.idtoki.instelec.manager.PartesManager;
import net.idtoki.instelec.group.PartesGroupBean;
import net.idtoki.instelec.model.PartesPeer;
import net.idtoki.instelec.helper.PartesHelper;



import net.zylk.tools.ajax.AjaxUtils;
import net.zylk.tools.ajax.AjaxUtils.DinamicGridBean;
import net.zylk.tools.format.FormatUtils;
import net.zylk.tools.pdf.PdfUtils;
import net.zylk.tools.xml.XmlUtils;
import net.zylk.torque.TorqueUtils;
import net.zylk.web.WebUtils;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Aug 10 13:35:35 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
 
 
public class LineasparteController
    extends net.idtoki.instelec.controller.BaseLineasparteController
{
 private static final Logger logger = Logger.getLogger("net.idtoki.instelec.controller.LineasparteController");
 private TransformerFactory tFactory = TransformerFactory.newInstance();
 private Transformer lineasparte_transformer = null;  
 private Transformer lineaspartes_transformer = null; 

 public void init(ServletConfig config)
 {
	super.init();
	ResourceBundle resource = ResourceBundle.getBundle("net/idtoki/instelec/app/config/app-config");
	File lineasparte = new File(resource.getString("app.xsl.templates.dir")+"/PdfLineasparte.xslt");
	Source xslSource = new StreamSource(lineasparte);
	File lineaspartes = new File(resource.getString("app.xsl.templates.dir")+"/PdfListaLineasparte.xslt");
	Source xslSourceT = new StreamSource(lineaspartes); 	  
	try{
		lineasparte_transformer = tFactory.newTransformer(xslSource);
		lineaspartes_transformer = tFactory.newTransformer(xslSourceT);			  
	}catch (Exception e){
	  e.printStackTrace();
	}
 }


//Función para la inserción/actualización de registros

public void serviceAddLineasparte(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 //Con esto se consigue transformar el request a UTF
	 //para temas de acentos y otros caracteres
	 utf8RequestService(request);

	 //recojo los parametros del formulario y doy de alta un nuevo elmento
	 try
	 {
		 Lineasparte elLineasparte = LineasparteHelper.createObj(request);
		 LineasparteGroupBean gbLineasparte = new LineasparteGroupBean();
		 elLineasparte.setFecha(FormatUtils.ddmmaaaa2aaaammdd(elLineasparte.getFecha(),"-",""));
		 gbLineasparte.setElemento(elLineasparte);
		 gbLineasparte.save();
	 }
	 catch(TorqueException te)
	 {
		 response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
	 }
 }


//Función para la eliminación de un registro
//este método invoca al método public void deleteLineasparte(int idBorrar)
//definido en el LineasparteManager
 public void serviceDeleteLineasparte(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 int idBorrar=-1;
	 idBorrar=WebUtils.getintParam(request, "borrarId");
	 if (idBorrar!=-1)
 		 if (LineasparteManager.borraLineasparte(idBorrar))
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlOKResponse("ISO-8859-1"));
		 else
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlNotOKResponse("ISO-8859-1"));			 
 }


// Funciones para las ordenaciones y filtrados de información

 private Criteria ordenacion(Criteria c,String CampoOrdenacion,String OrdenOrdenacion) 
 { 
 	if((OrdenOrdenacion != null )&& (OrdenOrdenacion.compareTo("ASC")==0))
 		if ((CampoOrdenacion != null))
 		{
 			c.addAscendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	if  ((OrdenOrdenacion != null) && (OrdenOrdenacion.compareTo("DESC")==0))
 		if ((CampoOrdenacion != null))
		{
 			c.addDescendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	return c;
 }

private Criteria filtro(Criteria c,int filtro) 
{ 
	String cadena = null;
	 switch (filtro)
	 {
	 case 1:
		  //Caso uno de Filtrado
		  //c.add(Campo,valor);
		  break;
	 case 2:
		  //Caso dos de Filtrado
		  //c.add(Campo,valor);
		  break;
	 default:
		 //caso por defecto
		 break;
	 }
	return c;
}

 public StringBuffer replaceStringBuffer (StringBuffer strBA, String strOrigen, String strDestino) 
 {
	 return new StringBuffer(strBA.toString().replaceAll(strOrigen,strDestino));
 }

 private Criteria criteriaLineasparteTableContent(HttpServletRequest request,Criteria c) throws IOException, ServletException
 {
 	String param = "";	 
	 param =  WebUtils.getStringParam(request, new PartesHelper().getIdparteName());
	 if(param != null)
		 TorqueUtils.addEqualCriteria(c,LineaspartePeer.IDPARTE,param);
	  String paramSortCol =  WebUtils.getStringParam(request, "sort_col");
	  String paramSortDir =  WebUtils.getStringParam(request, "sort_dir");
	  int paramFiltro =  WebUtils.getintParam(request, "filtro");
	  c = ordenacion(c,paramSortCol,paramSortDir);
	  c = filtro(c,paramFiltro);

 	  return c;
 } 
 
 public String getPathElementLineasparte(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;
	 int claveFkId=-1;	 
	 claveId=WebUtils.getintParam(request, "lineasparte.IDLINEAPARTE");
	 if (claveId!=-1)
	 {
		c.add(LineaspartePeer.IDLINEAPARTE, claveId);
		LineasparteGroupBean trgb = LineasparteManager.getLineaspartes(c);							
		strPath = trgb.getLineasparte(0).getPathLineasparteParsed(request.getQueryString());
	 }
	 return "<path>" + strPath + "</path>";
 } 
 
 public String getPathTableContentLineasparte(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;	 
	 claveId=WebUtils.getintParam(request, "partes.IDPARTE");
	 if(claveId != -1){
		 strPath = PartesManager.getPartes(claveId).getPathPartesParsed(request.getQueryString());
	 }		 	 
	 return "<path>" + strPath + "</path>";
 }  


public void  serviceLineasparteTableContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 utf8RequestService(request);
	 int numElemPedidosBD = 40;
	 int gap = 0;//gap = viewedRows - numElemVisiblesUltPag	  
	 DinamicGridBean dgb = WebUtils.getDinamicGridBeanParam(request,numElemPedidosBD,gap); 
	 Criteria c =LineasparteManager.buildSearchCriteria(dgb);
	 c =criteriaLineasparteTableContent(request,c);	 
	 LineasparteGroupBean cgb = LineasparteManager.getLineaspartes(c);
	 dgb.setTotalSize(cgb.getTotalSize());
	  
	 String[] methodos= new String[] {
		LineasparteHelper.IDPARTE_GET_METHOD_NAME+"LineasparteParsed"
		,LineasparteHelper.FECHA_GET_METHOD_NAME+"LineasparteParsed"
		,LineasparteHelper.HORAS_GET_METHOD_NAME+"LineasparteParsed"
		,LineasparteHelper.OBSERVACIONES_GET_METHOD_NAME+"LineasparteParsed"
		,"getEditLineasparte"
		,"getDeleteLineasparte"
	};
	 
	 StringBuffer cadena=null;
	 cadena = AjaxUtils.buildXmlAjaxResponseTableContentFromListObj(cgb.getAlmacen(),methodos,LineasparteHelper.IDLINEAPARTE_GET_METHOD_NAME, dgb,"ISO-8859-1"); 
	 cadena.insert(cadena.indexOf("</ajax-response>"),"<response type='object' id='divPath'>" + getPathTableContentLineasparte(request,response) + "</response>");
	 xmlResponseService(response,cadena); 
 }  

 public void serviceLineasparteUlContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] methodos= new String[] {
	 		"getULContentLineasparteParsed"
			 };
	 String param =  WebUtils.getStringParam(request, "value");
	 	 
	 LineasparteGroupBean mgb = LineasparteManager.getLineaspartes(LineasparteManager.buildSearchCriteria(param));
	 simpleResponseService(response, AjaxUtils.buildAjaxULContentFromListObj(mgb.getAlmacen(),methodos, LineasparteHelper.COMPLEX_ID_GET_METHOD,"Lineasparte"));
 } 



 public void serviceLineasparteElement(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
  StringBuffer cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "lineasparte.IDLINEAPARTE");
  if (claveId!=-1)
  {
	  c.add(LineaspartePeer.IDLINEAPARTE, claveId);
  }
  c.addAscendingOrderByColumn(LineaspartePeer.IDLINEAPARTE);
  LineasparteGroupBean trgb = LineasparteManager.getLineaspartes(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  String [] parametros={
		LineasparteHelper.IDLINEAPARTE_GET_METHOD_NAME
		,LineasparteHelper.IDPARTE_GET_METHOD_NAME+"LineasparteParsed"
		,LineasparteHelper.FECHA_GET_METHOD_NAME+"LineasparteParsed"
		,LineasparteHelper.HORAS_GET_METHOD_NAME+"LineasparteParsed"
		,LineasparteHelper.OBSERVACIONES_GET_METHOD_NAME+"LineasparteParsed"
	  };
	  cadena=trgb.buildXml(parametros,null,"ISO-8859-1");	
	  cadena.insert(cadena.indexOf("</result>"),getPathElementLineasparte(request,response));  
  }
  xmlResponseService(response, cadena);
 }  
 

 protected StringBuffer updateIdlineaparteResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(LineasparteManager.getLineasparte(Integer.parseInt(a.get(0).toString())).getIdlineaparteLineasparteParsed());
 }  
 

 protected StringBuffer updateIdparteResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(LineasparteManager.getLineasparte(Integer.parseInt(a.get(0).toString())).getIdparteLineasparteParsed());
 }  
 

 protected StringBuffer updateFechaResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(LineasparteManager.getLineasparte(Integer.parseInt(a.get(0).toString())).getFechaLineasparteParsed());
 }  
 

 protected StringBuffer updateHorasResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(LineasparteManager.getLineasparte(Integer.parseInt(a.get(0).toString())).getHorasLineasparteParsed());
 }  
 

 protected StringBuffer updateObservacionesResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(LineasparteManager.getLineasparte(Integer.parseInt(a.get(0).toString())).getObservacionesLineasparteParsed());
 }  
 
 
 
 
 public void serviceLineaspartePartes(HttpServletRequest request, HttpServletResponse response) throws IOException, TorqueException, ServletException
 {
  String cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "partes.IDPARTE");
  if (claveId!=-1)
  {
	  c.add(PartesPeer.IDPARTE, claveId);
  }
  c.addAscendingOrderByColumn(PartesPeer.IDPARTE);
  PartesGroupBean trgb = PartesManager.getPartess(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  cadena = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>";
	  cadena = cadena + "<result><lineasparte.IDPARTE>" + trgb.getPartes(0).getULContentPartesParsed()  + "</lineasparte.IDPARTE></result>";
  }
  
  xmlResponseService(response, new StringBuffer(cadena));
 }  
  			

 public void serviceGetLineasparteDetallePdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] getMethodos= new String[] {
		LineasparteHelper.IDLINEAPARTE_GET_METHOD_NAME
		,LineasparteHelper.IDPARTE_GET_METHOD_NAME+"LineasparteParsed"
		,LineasparteHelper.FECHA_GET_METHOD_NAME+"LineasparteParsed"
		,LineasparteHelper.HORAS_GET_METHOD_NAME+"LineasparteParsed"
		,LineasparteHelper.OBSERVACIONES_GET_METHOD_NAME+"LineasparteParsed"
			 };
	  
	 
	 LineasparteGroupBean tgb = new LineasparteGroupBean();
	 try
	{
		tgb.setElemento(LineasparteHelper.getLineasparte(request));
	} catch (TorqueException e)
	{
		logger.severe(e.getMessage());
	}
	
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(getMethodos, null,"ISO-8859-1"),"n/a"," "), lineasparte_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=Lineasparte.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
	
 }  

 public void serviceLineasparteTableContentPdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
  	utf8RequestService(request);
  	Criteria c= new Criteria();
  	String paramQuery =  WebUtils.getStringParam(request, "query");
  	if ((paramQuery != null)&& (paramQuery.compareTo("")!=0) )
		c = LineasparteManager.buildSearchCriteria(paramQuery);   
  	c =criteriaLineasparteTableContent(request,c);	  
  	LineasparteGroupBean tgb = LineasparteManager.getLineaspartes(c);
  
  	String[] methodos= new String[] {	
		LineasparteHelper.IDPARTE_GET_METHOD_NAME+"LineasparteParsed"
		,LineasparteHelper.FECHA_GET_METHOD_NAME+"LineasparteParsed"
		,LineasparteHelper.HORAS_GET_METHOD_NAME+"LineasparteParsed"
		,LineasparteHelper.OBSERVACIONES_GET_METHOD_NAME+"LineasparteParsed"
			};
  
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(methodos, null,"ISO-8859-1"),"n/a"," "), lineaspartes_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=ListaLineasparte.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
 }

}


