package net.idtoki.instelec.controller;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.ResourceBundle;
import java.util.logging.Logger;

import javax.servlet.ServletConfig;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamSource;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

import net.idtoki.instelec.manager.LocalidadesManager;
import net.idtoki.instelec.group.LocalidadesGroupBean;
import net.idtoki.instelec.helper.LocalidadesHelper;
import net.idtoki.instelec.model.LocalidadesPeer;
import net.idtoki.instelec.model.Localidades;

import net.idtoki.instelec.manager.ProvinciasManager;
import net.idtoki.instelec.group.ProvinciasGroupBean;
import net.idtoki.instelec.model.ProvinciasPeer;
import net.idtoki.instelec.helper.ProvinciasHelper;

import net.idtoki.instelec.helper.ClientesHelper;
import net.idtoki.instelec.helper.TrabajadoresHelper;


import net.zylk.tools.ajax.AjaxUtils;
import net.zylk.tools.ajax.AjaxUtils.DinamicGridBean;
import net.zylk.tools.format.FormatUtils;
import net.zylk.tools.pdf.PdfUtils;
import net.zylk.tools.xml.XmlUtils;
import net.zylk.torque.TorqueUtils;
import net.zylk.web.WebUtils;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Aug 10 13:35:35 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
 
 
public class LocalidadesController
    extends net.idtoki.instelec.controller.BaseLocalidadesController
{
 private static final Logger logger = Logger.getLogger("net.idtoki.instelec.controller.LocalidadesController");
 private TransformerFactory tFactory = TransformerFactory.newInstance();
 private Transformer localidades_transformer = null;  
 private Transformer localidadess_transformer = null; 

 public void init(ServletConfig config)
 {
	super.init();
	ResourceBundle resource = ResourceBundle.getBundle("net/idtoki/instelec/app/config/app-config");
	File localidades = new File(resource.getString("app.xsl.templates.dir")+"/PdfLocalidades.xslt");
	Source xslSource = new StreamSource(localidades);
	File localidadess = new File(resource.getString("app.xsl.templates.dir")+"/PdfListaLocalidades.xslt");
	Source xslSourceT = new StreamSource(localidadess); 	  
	try{
		localidades_transformer = tFactory.newTransformer(xslSource);
		localidadess_transformer = tFactory.newTransformer(xslSourceT);			  
	}catch (Exception e){
	  e.printStackTrace();
	}
 }


//Función para la inserción/actualización de registros

public void serviceAddLocalidades(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 //Con esto se consigue transformar el request a UTF
	 //para temas de acentos y otros caracteres
	 utf8RequestService(request);

	 //recojo los parametros del formulario y doy de alta un nuevo elmento
	 try
	 {
		 Localidades elLocalidades = LocalidadesHelper.createObj(request);
		 LocalidadesGroupBean gbLocalidades = new LocalidadesGroupBean();
		 gbLocalidades.setElemento(elLocalidades);
		 gbLocalidades.save();
	 }
	 catch(TorqueException te)
	 {
		 response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
	 }
 }


//Función para la eliminación de un registro
//este método invoca al método public void deleteLocalidades(int idBorrar)
//definido en el LocalidadesManager
 public void serviceDeleteLocalidades(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 int idBorrar=-1;
	 idBorrar=WebUtils.getintParam(request, "borrarId");
	 if (idBorrar!=-1)
 		 if (LocalidadesManager.borraLocalidades(idBorrar))
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlOKResponse("ISO-8859-1"));
		 else
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlNotOKResponse("ISO-8859-1"));			 
 }


// Funciones para las ordenaciones y filtrados de información

 private Criteria ordenacion(Criteria c,String CampoOrdenacion,String OrdenOrdenacion) 
 { 
 	if((OrdenOrdenacion != null )&& (OrdenOrdenacion.compareTo("ASC")==0))
 		if ((CampoOrdenacion != null))
 		{
 			c.addAscendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	if  ((OrdenOrdenacion != null) && (OrdenOrdenacion.compareTo("DESC")==0))
 		if ((CampoOrdenacion != null))
		{
 			c.addDescendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	return c;
 }

private Criteria filtro(Criteria c,int filtro) 
{ 
	String cadena = null;
	 switch (filtro)
	 {
	 case 1:
		  //Caso uno de Filtrado
		  //c.add(Campo,valor);
		  break;
	 case 2:
		  //Caso dos de Filtrado
		  //c.add(Campo,valor);
		  break;
	 default:
		 //caso por defecto
		 break;
	 }
	return c;
}

 public StringBuffer replaceStringBuffer (StringBuffer strBA, String strOrigen, String strDestino) 
 {
	 return new StringBuffer(strBA.toString().replaceAll(strOrigen,strDestino));
 }

 private Criteria criteriaLocalidadesTableContent(HttpServletRequest request,Criteria c) throws IOException, ServletException
 {
 	String param = "";	 
	 param =  WebUtils.getStringParam(request, new ProvinciasHelper().getIdprovinciaName());
	 if(param != null)
		 TorqueUtils.addEqualCriteria(c,LocalidadesPeer.IDPROVINCIA,param);
	  String paramSortCol =  WebUtils.getStringParam(request, "sort_col");
	  String paramSortDir =  WebUtils.getStringParam(request, "sort_dir");
	  int paramFiltro =  WebUtils.getintParam(request, "filtro");
	  c = ordenacion(c,paramSortCol,paramSortDir);
	  c = filtro(c,paramFiltro);

 	  return c;
 } 
 
 public String getPathElementLocalidades(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;
	 int claveFkId=-1;	 
	 claveId=WebUtils.getintParam(request, "localidades.IDLOCALIDAD");
	 if (claveId!=-1)
	 {
		c.add(LocalidadesPeer.IDLOCALIDAD, claveId);
		LocalidadesGroupBean trgb = LocalidadesManager.getLocalidadess(c);							
		strPath = trgb.getLocalidades(0).getPathLocalidadesParsed(request.getQueryString());
	 }
	 return "<path>" + strPath + "</path>";
 } 
 
 public String getPathTableContentLocalidades(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;	 
	 claveId=WebUtils.getintParam(request, "provincias.IDPROVINCIA");
	 if(claveId != -1){
		 strPath = ProvinciasManager.getProvincias(claveId).getPathProvinciasParsed(request.getQueryString());
	 }		 	 
	 return "<path>" + strPath + "</path>";
 }  


public void  serviceLocalidadesTableContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 utf8RequestService(request);
	 int numElemPedidosBD = 40;
	 int gap = 0;//gap = viewedRows - numElemVisiblesUltPag	  
	 DinamicGridBean dgb = WebUtils.getDinamicGridBeanParam(request,numElemPedidosBD,gap); 
	 Criteria c =LocalidadesManager.buildSearchCriteria(dgb);
	 c =criteriaLocalidadesTableContent(request,c);	 
	 LocalidadesGroupBean cgb = LocalidadesManager.getLocalidadess(c);
	 dgb.setTotalSize(cgb.getTotalSize());
	  
	 String[] methodos= new String[] {
		LocalidadesHelper.IDPROVINCIA_GET_METHOD_NAME+"LocalidadesParsed"
		,LocalidadesHelper.NOMBRE_GET_METHOD_NAME+"LocalidadesParsed"
		,"getHijosClientesLocalidades"
		,"getHijosTrabajadoresLocalidades"
		,"getEditLocalidades"
		,"getDeleteLocalidades"
	};
	 
	 StringBuffer cadena=null;
	 cadena = AjaxUtils.buildXmlAjaxResponseTableContentFromListObj(cgb.getAlmacen(),methodos,LocalidadesHelper.IDLOCALIDAD_GET_METHOD_NAME, dgb,"ISO-8859-1"); 
	 cadena.insert(cadena.indexOf("</ajax-response>"),"<response type='object' id='divPath'>" + getPathTableContentLocalidades(request,response) + "</response>");
	 xmlResponseService(response,cadena); 
 }  

 public void serviceLocalidadesUlContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] methodos= new String[] {
	 		"getULContentLocalidadesParsed"
			 };
	 String param =  WebUtils.getStringParam(request, "value");
	 if(param==null || param.length() <= 0)
		 param =  WebUtils.getStringParam(request, new ClientesHelper().getIdlocalidadName());
	 if(param==null || param.length() <= 0)
		 param =  WebUtils.getStringParam(request, new TrabajadoresHelper().getIdlocalidadName());
	 	 
	 LocalidadesGroupBean mgb = LocalidadesManager.getLocalidadess(LocalidadesManager.buildSearchCriteria(param));
	 simpleResponseService(response, AjaxUtils.buildAjaxULContentFromListObj(mgb.getAlmacen(),methodos, LocalidadesHelper.COMPLEX_ID_GET_METHOD,"Localidades"));
 } 



 public void serviceLocalidadesElement(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
  StringBuffer cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "localidades.IDLOCALIDAD");
  if (claveId!=-1)
  {
	  c.add(LocalidadesPeer.IDLOCALIDAD, claveId);
  }
  c.addAscendingOrderByColumn(LocalidadesPeer.IDLOCALIDAD);
  LocalidadesGroupBean trgb = LocalidadesManager.getLocalidadess(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  String [] parametros={
		LocalidadesHelper.IDLOCALIDAD_GET_METHOD_NAME
		,LocalidadesHelper.IDPROVINCIA_GET_METHOD_NAME+"LocalidadesParsed"
		,LocalidadesHelper.NOMBRE_GET_METHOD_NAME+"LocalidadesParsed"
	  };
	  cadena=trgb.buildXml(parametros,null,"ISO-8859-1");	
	  cadena.insert(cadena.indexOf("</result>"),getPathElementLocalidades(request,response));  
  }
  xmlResponseService(response, cadena);
 }  
 


 protected StringBuffer updateIdlocalidadResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(LocalidadesManager.getLocalidades(Integer.parseInt(a.get(0).toString())).getIdlocalidadLocalidadesParsed());
 }  
 

 protected StringBuffer updateIdprovinciaResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(LocalidadesManager.getLocalidades(Integer.parseInt(a.get(0).toString())).getIdprovinciaLocalidadesParsed());
 }  
 

 protected StringBuffer updateNombreResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(LocalidadesManager.getLocalidades(Integer.parseInt(a.get(0).toString())).getNombreLocalidadesParsed());
 }  
 
 
 public void serviceLocalidadesProvincias(HttpServletRequest request, HttpServletResponse response) throws IOException, TorqueException, ServletException
 {
  String cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "provincias.IDPROVINCIA");
  if (claveId!=-1)
  {
	  c.add(ProvinciasPeer.IDPROVINCIA, claveId);
  }
  c.addAscendingOrderByColumn(ProvinciasPeer.IDPROVINCIA);
  ProvinciasGroupBean trgb = ProvinciasManager.getProvinciass(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  cadena = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>";
	  cadena = cadena + "<result><localidades.IDPROVINCIA>" + trgb.getProvincias(0).getULContentProvinciasParsed()  + "</localidades.IDPROVINCIA></result>";
  }
  
  xmlResponseService(response, new StringBuffer(cadena));
 }  
  			

 public void serviceGetLocalidadesDetallePdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] getMethodos= new String[] {
		LocalidadesHelper.IDLOCALIDAD_GET_METHOD_NAME
		,LocalidadesHelper.IDPROVINCIA_GET_METHOD_NAME+"LocalidadesParsed"
		,LocalidadesHelper.NOMBRE_GET_METHOD_NAME+"LocalidadesParsed"
			 };
	  
	 
	 LocalidadesGroupBean tgb = new LocalidadesGroupBean();
	 try
	{
		tgb.setElemento(LocalidadesHelper.getLocalidades(request));
	} catch (TorqueException e)
	{
		logger.severe(e.getMessage());
	}
	
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(getMethodos, null,"ISO-8859-1"),"n/a"," "), localidades_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=Localidades.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
	
 }  

 public void serviceLocalidadesTableContentPdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
  	utf8RequestService(request);
  	Criteria c= new Criteria();
  	String paramQuery =  WebUtils.getStringParam(request, "query");
  	if ((paramQuery != null)&& (paramQuery.compareTo("")!=0) )
		c = LocalidadesManager.buildSearchCriteria(paramQuery);   
  	c =criteriaLocalidadesTableContent(request,c);	  
  	LocalidadesGroupBean tgb = LocalidadesManager.getLocalidadess(c);
  
  	String[] methodos= new String[] {	
		LocalidadesHelper.IDPROVINCIA_GET_METHOD_NAME+"LocalidadesParsed"
		,LocalidadesHelper.NOMBRE_GET_METHOD_NAME+"LocalidadesParsed"
			};
  
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(methodos, null,"ISO-8859-1"),"n/a"," "), localidadess_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=ListaLocalidades.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
 }

}


