package net.idtoki.instelec.controller;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.ResourceBundle;
import java.util.logging.Logger;

import javax.servlet.ServletConfig;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamSource;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

import net.idtoki.instelec.manager.OrdenestrabajoManager;
import net.idtoki.instelec.group.OrdenestrabajoGroupBean;
import net.idtoki.instelec.helper.OrdenestrabajoHelper;
import net.idtoki.instelec.model.OrdenestrabajoPeer;
import net.idtoki.instelec.model.Ordenestrabajo;

import net.idtoki.instelec.manager.TrabajosManager;
import net.idtoki.instelec.group.TrabajosGroupBean;
import net.idtoki.instelec.model.TrabajosPeer;
import net.idtoki.instelec.helper.TrabajosHelper;

import net.idtoki.instelec.helper.PartesHelper;
import net.idtoki.instelec.helper.TareasHelper;


import net.zylk.tools.ajax.AjaxUtils;
import net.zylk.tools.ajax.AjaxUtils.DinamicGridBean;
import net.zylk.tools.format.FormatUtils;
import net.zylk.tools.pdf.PdfUtils;
import net.zylk.tools.xml.XmlUtils;
import net.zylk.torque.TorqueUtils;
import net.zylk.web.WebUtils;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Aug 10 13:35:35 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
 
 
public class OrdenestrabajoController
    extends net.idtoki.instelec.controller.BaseOrdenestrabajoController
{
 private static final Logger logger = Logger.getLogger("net.idtoki.instelec.controller.OrdenestrabajoController");
 private TransformerFactory tFactory = TransformerFactory.newInstance();
 private Transformer ordenestrabajo_transformer = null;  
 private Transformer ordenestrabajos_transformer = null; 

 public void init(ServletConfig config)
 {
	super.init();
	ResourceBundle resource = ResourceBundle.getBundle("net/idtoki/instelec/app/config/app-config");
	File ordenestrabajo = new File(resource.getString("app.xsl.templates.dir")+"/PdfOrdenestrabajo.xslt");
	Source xslSource = new StreamSource(ordenestrabajo);
	File ordenestrabajos = new File(resource.getString("app.xsl.templates.dir")+"/PdfListaOrdenestrabajo.xslt");
	Source xslSourceT = new StreamSource(ordenestrabajos); 	  
	try{
		ordenestrabajo_transformer = tFactory.newTransformer(xslSource);
		ordenestrabajos_transformer = tFactory.newTransformer(xslSourceT);			  
	}catch (Exception e){
	  e.printStackTrace();
	}
 }


//Función para la inserción/actualización de registros

public void serviceAddOrdenestrabajo(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 //Con esto se consigue transformar el request a UTF
	 //para temas de acentos y otros caracteres
	 utf8RequestService(request);

	 //recojo los parametros del formulario y doy de alta un nuevo elmento
	 try
	 {
		 String tipo =  WebUtils.getStringParam(request, "ordenestrabajo.TIPOMANTENIMIENTO");
		 String [] valorTipo= tipo.split("-");	
		 String urgencia =  WebUtils.getStringParam(request, "ordenestrabajo.URGENCIA");
		 String [] valorUrgencia= urgencia.split("-");		 
		 Ordenestrabajo elOrdenestrabajo = OrdenestrabajoHelper.createObj(request);
		 OrdenestrabajoGroupBean gbOrdenestrabajo = new OrdenestrabajoGroupBean();
		 elOrdenestrabajo.setTipomantenimiento(new Integer(valorTipo[0]).intValue());
		 elOrdenestrabajo.setUrgencia(new Integer(valorUrgencia[0]).intValue());
		 elOrdenestrabajo.setFechainicio(FormatUtils.ddmmaaaa2aaaammdd(elOrdenestrabajo.getFechainicio(),"-",""));
		 elOrdenestrabajo.setFechafin(FormatUtils.ddmmaaaa2aaaammdd(elOrdenestrabajo.getFechafin(),"-",""));
		 gbOrdenestrabajo.setElemento(elOrdenestrabajo);
		 gbOrdenestrabajo.save();
	 }
	 catch(TorqueException te)
	 {
		 response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
	 }
 }


//Función para la eliminación de un registro
//este método invoca al método public void deleteOrdenestrabajo(int idBorrar)
//definido en el OrdenestrabajoManager
 public void serviceDeleteOrdenestrabajo(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 int idBorrar=-1;
	 idBorrar=WebUtils.getintParam(request, "borrarId");
	 if (idBorrar!=-1)
 		 if (OrdenestrabajoManager.borraOrdenestrabajo(idBorrar))
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlOKResponse("ISO-8859-1"));
		 else
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlNotOKResponse("ISO-8859-1"));			 
 }


// Funciones para las ordenaciones y filtrados de información

 private Criteria ordenacion(Criteria c,String CampoOrdenacion,String OrdenOrdenacion) 
 { 
 	if((OrdenOrdenacion != null )&& (OrdenOrdenacion.compareTo("ASC")==0))
 		if ((CampoOrdenacion != null))
 		{
 			c.addAscendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	if  ((OrdenOrdenacion != null) && (OrdenOrdenacion.compareTo("DESC")==0))
 		if ((CampoOrdenacion != null))
		{
 			c.addDescendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	return c;
 }

private Criteria filtro(Criteria c,int filtro) 
{ 
	String cadena = null;
	 switch (filtro)
	 {
	 case 1:
		  //Caso uno de Filtrado
		 c.add(OrdenestrabajoPeer.URGENCIA,0);
		  break;
	 case 2:
		  //Caso dos de Filtrado
		 c.add(OrdenestrabajoPeer.URGENCIA,1);
		  break;
	 case 3:
		  //Caso dos de Filtrado
		 c.add(OrdenestrabajoPeer.URGENCIA,2);
		  break;		  
	 default:
		 //caso por defecto
		 break;
	 }
	return c;
}

 public StringBuffer replaceStringBuffer (StringBuffer strBA, String strOrigen, String strDestino) 
 {
	 return new StringBuffer(strBA.toString().replaceAll(strOrigen,strDestino));
 }

 private Criteria criteriaOrdenestrabajoTableContent(HttpServletRequest request,Criteria c) throws IOException, ServletException
 {
 	String param = "";	 
	 param =  WebUtils.getStringParam(request, new TrabajosHelper().getIdtrabajoName());
	 if(param != null)
		 TorqueUtils.addEqualCriteria(c,OrdenestrabajoPeer.IDTRABAJO,param);
	  String paramSortCol =  WebUtils.getStringParam(request, "sort_col");
	  String paramSortDir =  WebUtils.getStringParam(request, "sort_dir");
	  int paramFiltro =  WebUtils.getintParam(request, "filtro");
	  c = ordenacion(c,paramSortCol,paramSortDir);
	  c = filtro(c,paramFiltro);

 	  return c;
 } 
 
 public String getPathElementOrdenestrabajo(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;
	 int claveFkId=-1;	 
	 claveId=WebUtils.getintParam(request, "ordenestrabajo.IDORDEN");
	 if (claveId!=-1)
	 {
		c.add(OrdenestrabajoPeer.IDORDEN, claveId);
		OrdenestrabajoGroupBean trgb = OrdenestrabajoManager.getOrdenestrabajos(c);							
		strPath = trgb.getOrdenestrabajo(0).getPathOrdenestrabajoParsed(request.getQueryString());
	 }
	 return "<path>" + strPath + "</path>";
 } 
 
 public String getPathTableContentOrdenestrabajo(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;	 
	 claveId=WebUtils.getintParam(request, "trabajos.IDTRABAJO");
	 if(claveId != -1){
		 strPath = TrabajosManager.getTrabajos(claveId).getPathTrabajosParsed(request.getQueryString());
	 }		 	 
	 return "<path>" + strPath + "</path>";
 }  


public void  serviceOrdenestrabajoTableContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 utf8RequestService(request);
	 int numElemPedidosBD = 40;
	 int gap = 0;//gap = viewedRows - numElemVisiblesUltPag	  
	 DinamicGridBean dgb = WebUtils.getDinamicGridBeanParam(request,numElemPedidosBD,gap); 
	 Criteria c =OrdenestrabajoManager.buildSearchCriteria(dgb);
	 c =criteriaOrdenestrabajoTableContent(request,c);	 
	 OrdenestrabajoGroupBean cgb = OrdenestrabajoManager.getOrdenestrabajos(c);
	 dgb.setTotalSize(cgb.getTotalSize());
	  
	 String[] methodos= new String[] {
		//OrdenestrabajoHelper.FECHAINICIO_GET_METHOD_NAME+"OrdenestrabajoParsed"
		//,OrdenestrabajoHelper.FECHAFIN_GET_METHOD_NAME+"OrdenestrabajoParsed"
		OrdenestrabajoHelper.IDTRABAJO_GET_METHOD_NAME+"OrdenestrabajoParsed"
		,OrdenestrabajoHelper.DESCRIPCION_GET_METHOD_NAME+"OrdenestrabajoParsed"
		//,OrdenestrabajoHelper.OBSERVACIONES_GET_METHOD_NAME+"OrdenestrabajoParsed"
		,OrdenestrabajoHelper.TIPOMANTENIMIENTO_GET_METHOD_NAME+"OrdenestrabajoParsed"+"Label"
		,OrdenestrabajoHelper.URGENCIA_GET_METHOD_NAME+"OrdenestrabajoParsed"+"Label"
		,OrdenestrabajoHelper.SINTOMAS_GET_METHOD_NAME+"OrdenestrabajoParsed"
		,OrdenestrabajoHelper.CAUSAS_GET_METHOD_NAME+"OrdenestrabajoParsed"
		//,OrdenestrabajoHelper.IMPORTE_GET_METHOD_NAME+"OrdenestrabajoParsed"
		,"getHijosPartesOrdenestrabajo"
		,"getHijosTareasOrdenestrabajo"
		,"getEditOrdenestrabajo"
		,"getDeleteOrdenestrabajo"
	};
	 
	 StringBuffer cadena=null;
	 cadena = AjaxUtils.buildXmlAjaxResponseTableContentFromListObj(cgb.getAlmacen(),methodos,OrdenestrabajoHelper.IDORDEN_GET_METHOD_NAME, dgb,"ISO-8859-1"); 
	 cadena.insert(cadena.indexOf("</ajax-response>"),"<response type='object' id='divPath'>" + getPathTableContentOrdenestrabajo(request,response) + "</response>");
	 xmlResponseService(response,cadena); 
 }  

 public void serviceOrdenestrabajoUlContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] methodos= new String[] {
	 		"getULContentOrdenestrabajoParsed"
			 };
	 String param =  WebUtils.getStringParam(request, "value");
	 if(param==null || param.length() <= 0)
		 param =  WebUtils.getStringParam(request, new PartesHelper().getIdordenName());
	 if(param==null || param.length() <= 0)
		 param =  WebUtils.getStringParam(request, new TareasHelper().getIdordenName());
	 	 
	 OrdenestrabajoGroupBean mgb = OrdenestrabajoManager.getOrdenestrabajos(OrdenestrabajoManager.buildSearchCriteria(param));
	 simpleResponseService(response, AjaxUtils.buildAjaxULContentFromListObj(mgb.getAlmacen(),methodos, OrdenestrabajoHelper.COMPLEX_ID_GET_METHOD,"Ordenestrabajo"));
 } 

 public void serviceTipomantenimientoOrdenestrabajoUlContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String cadena="<ul><li>0-Preventivo</li><li>1-Correctivo</li></ul>";
	 response.getWriter().print(cadena);
 }
 
 public void serviceUrgenciaOrdenestrabajoUlContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String cadena="<ul><li>0-No urgente</li><li>1-Urgente</li><li>2-Muy urgente</li></ul>";
	 response.getWriter().print(cadena);
 }

 public void serviceOrdenestrabajoElement(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
  StringBuffer cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "ordenestrabajo.IDORDEN");
  if (claveId!=-1)
  {
	  c.add(OrdenestrabajoPeer.IDORDEN, claveId);
  }
  c.addAscendingOrderByColumn(OrdenestrabajoPeer.IDORDEN);
  OrdenestrabajoGroupBean trgb = OrdenestrabajoManager.getOrdenestrabajos(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  String [] parametros={
		OrdenestrabajoHelper.IDORDEN_GET_METHOD_NAME
		,OrdenestrabajoHelper.FECHAINICIO_GET_METHOD_NAME+"OrdenestrabajoParsed"
		,OrdenestrabajoHelper.FECHAFIN_GET_METHOD_NAME+"OrdenestrabajoParsed"
		,OrdenestrabajoHelper.IDTRABAJO_GET_METHOD_NAME+"OrdenestrabajoParsed"
		,OrdenestrabajoHelper.DESCRIPCION_GET_METHOD_NAME+"OrdenestrabajoParsed"
		,OrdenestrabajoHelper.URGENCIA_GET_METHOD_NAME+"OrdenestrabajoParsed"		
		,OrdenestrabajoHelper.TIPOMANTENIMIENTO_GET_METHOD_NAME+"OrdenestrabajoParsed"
		,OrdenestrabajoHelper.OBSERVACIONES_GET_METHOD_NAME+"OrdenestrabajoParsed"		
		,OrdenestrabajoHelper.SINTOMAS_GET_METHOD_NAME+"OrdenestrabajoParsed"
		,OrdenestrabajoHelper.CAUSAS_GET_METHOD_NAME+"OrdenestrabajoParsed"
		,"getImporteCalculadoOrdenestrabajoParsed"
		,"getManoObraCalculadoOrdenestrabajoParsed"
		,OrdenestrabajoHelper.IMPORTE_GET_METHOD_NAME+"OrdenestrabajoParsed"		
	  };
	  cadena=trgb.buildXml(parametros,null,"ISO-8859-1");	
	  cadena.insert(cadena.indexOf("</result>"),getPathElementOrdenestrabajo(request,response));  
  }
  xmlResponseService(response, cadena);
 }  
 

 protected StringBuffer updateIdordenResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(OrdenestrabajoManager.getOrdenestrabajo(Integer.parseInt(a.get(0).toString())).getIdordenOrdenestrabajoParsed());
 }  
 

 protected StringBuffer updateFechainicioResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(OrdenestrabajoManager.getOrdenestrabajo(Integer.parseInt(a.get(0).toString())).getFechainicioOrdenestrabajoParsed());
 }  
 

 protected StringBuffer updateFechafinResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(OrdenestrabajoManager.getOrdenestrabajo(Integer.parseInt(a.get(0).toString())).getFechafinOrdenestrabajoParsed());
 }  
 

 protected StringBuffer updateIdtrabajoResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(OrdenestrabajoManager.getOrdenestrabajo(Integer.parseInt(a.get(0).toString())).getIdtrabajoOrdenestrabajoParsed());
 }  
 

 protected StringBuffer updateDescripcionResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(OrdenestrabajoManager.getOrdenestrabajo(Integer.parseInt(a.get(0).toString())).getDescripcionOrdenestrabajoParsed());
 }  
 

 protected StringBuffer updateObservacionesResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(OrdenestrabajoManager.getOrdenestrabajo(Integer.parseInt(a.get(0).toString())).getObservacionesOrdenestrabajoParsed());
 }  
 

 protected StringBuffer updateTipomantenimientoResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(OrdenestrabajoManager.getOrdenestrabajo(Integer.parseInt(a.get(0).toString())).getTipomantenimientoOrdenestrabajoParsed());
 }  
 

 protected StringBuffer updateUrgenciaResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(OrdenestrabajoManager.getOrdenestrabajo(Integer.parseInt(a.get(0).toString())).getUrgenciaOrdenestrabajoParsed());
 }  
 

 protected StringBuffer updateSintomasResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(OrdenestrabajoManager.getOrdenestrabajo(Integer.parseInt(a.get(0).toString())).getSintomasOrdenestrabajoParsed());
 }  
 

 protected StringBuffer updateCausasResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(OrdenestrabajoManager.getOrdenestrabajo(Integer.parseInt(a.get(0).toString())).getCausasOrdenestrabajoParsed());
 }  
 

 protected StringBuffer updateImporteResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(OrdenestrabajoManager.getOrdenestrabajo(Integer.parseInt(a.get(0).toString())).getImporteOrdenestrabajoParsed());
 }  
 
 
 public void serviceOrdenestrabajoTrabajos(HttpServletRequest request, HttpServletResponse response) throws IOException, TorqueException, ServletException
 {
  String cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "trabajos.IDTRABAJO");
  if (claveId!=-1)
  {
	  c.add(TrabajosPeer.IDTRABAJO, claveId);
  }
  c.addAscendingOrderByColumn(TrabajosPeer.IDTRABAJO);
  TrabajosGroupBean trgb = TrabajosManager.getTrabajoss(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  cadena = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>";
	  cadena = cadena + "<result><ordenestrabajo.IDTRABAJO>" + trgb.getTrabajos(0).getULContentTrabajosParsed()  + "</ordenestrabajo.IDTRABAJO></result>";
  }
  
  xmlResponseService(response, new StringBuffer(cadena));
 }  
  			

 public void serviceGetOrdenestrabajoDetallePdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] getMethodos= new String[] {
		OrdenestrabajoHelper.IDORDEN_GET_METHOD_NAME
		,OrdenestrabajoHelper.FECHAINICIO_GET_METHOD_NAME+"OrdenestrabajoParsed"
		,OrdenestrabajoHelper.FECHAFIN_GET_METHOD_NAME+"OrdenestrabajoParsed"
		,OrdenestrabajoHelper.IDTRABAJO_GET_METHOD_NAME+"OrdenestrabajoParsed"
		,OrdenestrabajoHelper.DESCRIPCION_GET_METHOD_NAME+"OrdenestrabajoParsed"
		,OrdenestrabajoHelper.OBSERVACIONES_GET_METHOD_NAME+"OrdenestrabajoParsed"
		,OrdenestrabajoHelper.TIPOMANTENIMIENTO_GET_METHOD_NAME+"OrdenestrabajoParsed"
		,OrdenestrabajoHelper.URGENCIA_GET_METHOD_NAME+"OrdenestrabajoParsed"
		,OrdenestrabajoHelper.SINTOMAS_GET_METHOD_NAME+"OrdenestrabajoParsed"
		,OrdenestrabajoHelper.CAUSAS_GET_METHOD_NAME+"OrdenestrabajoParsed"
		,OrdenestrabajoHelper.IMPORTE_GET_METHOD_NAME+"OrdenestrabajoParsed"
			 };
	  
	 
	 OrdenestrabajoGroupBean tgb = new OrdenestrabajoGroupBean();
	 try
	{
		tgb.setElemento(OrdenestrabajoHelper.getOrdenestrabajo(request));
	} catch (TorqueException e)
	{
		logger.severe(e.getMessage());
	}
	
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(getMethodos, null,"ISO-8859-1"),"n/a"," "), ordenestrabajo_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=Ordenestrabajo.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
	
 }  

 public void serviceOrdenestrabajoTableContentPdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
  	utf8RequestService(request);
  	Criteria c= new Criteria();
  	String paramQuery =  WebUtils.getStringParam(request, "query");
  	if ((paramQuery != null)&& (paramQuery.compareTo("")!=0) )
		c = OrdenestrabajoManager.buildSearchCriteria(paramQuery);   
  	c =criteriaOrdenestrabajoTableContent(request,c);	  
  	OrdenestrabajoGroupBean tgb = OrdenestrabajoManager.getOrdenestrabajos(c);
  
  	String[] methodos= new String[] {	
		OrdenestrabajoHelper.FECHAINICIO_GET_METHOD_NAME+"OrdenestrabajoParsed"
		,OrdenestrabajoHelper.FECHAFIN_GET_METHOD_NAME+"OrdenestrabajoParsed"
		,OrdenestrabajoHelper.IDTRABAJO_GET_METHOD_NAME+"OrdenestrabajoParsed"
		,OrdenestrabajoHelper.DESCRIPCION_GET_METHOD_NAME+"OrdenestrabajoParsed"
		,OrdenestrabajoHelper.OBSERVACIONES_GET_METHOD_NAME+"OrdenestrabajoParsed"
		,OrdenestrabajoHelper.TIPOMANTENIMIENTO_GET_METHOD_NAME+"OrdenestrabajoParsed"
		,OrdenestrabajoHelper.URGENCIA_GET_METHOD_NAME+"OrdenestrabajoParsed"
		,OrdenestrabajoHelper.SINTOMAS_GET_METHOD_NAME+"OrdenestrabajoParsed"
		,OrdenestrabajoHelper.CAUSAS_GET_METHOD_NAME+"OrdenestrabajoParsed"
		,OrdenestrabajoHelper.IMPORTE_GET_METHOD_NAME+"OrdenestrabajoParsed"
			};
  
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(methodos, null,"ISO-8859-1"),"n/a"," "), ordenestrabajos_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=ListaOrdenestrabajo.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
 }

}


