package net.idtoki.instelec.controller;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.ResourceBundle;
import java.util.logging.Logger;

import javax.servlet.ServletConfig;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamSource;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

import net.idtoki.instelec.manager.TareasManager;
import net.idtoki.instelec.group.TareasGroupBean;
import net.idtoki.instelec.helper.TareasHelper;
import net.idtoki.instelec.model.TareasPeer;
import net.idtoki.instelec.model.Tareas;

import net.idtoki.instelec.manager.OrdenestrabajoManager;
import net.idtoki.instelec.group.OrdenestrabajoGroupBean;
import net.idtoki.instelec.model.OrdenestrabajoPeer;
import net.idtoki.instelec.helper.OrdenestrabajoHelper;
import net.idtoki.instelec.manager.TipotareasManager;
import net.idtoki.instelec.group.TipotareasGroupBean;
import net.idtoki.instelec.model.TipotareasPeer;
import net.idtoki.instelec.helper.TipotareasHelper;
import net.idtoki.instelec.manager.CategoriasManager;
import net.idtoki.instelec.group.CategoriasGroupBean;
import net.idtoki.instelec.model.CategoriasPeer;
import net.idtoki.instelec.helper.CategoriasHelper;

import net.idtoki.instelec.helper.MaterialesHelper;


import net.zylk.tools.ajax.AjaxUtils;
import net.zylk.tools.ajax.AjaxUtils.DinamicGridBean;
import net.zylk.tools.format.FormatUtils;
import net.zylk.tools.pdf.PdfUtils;
import net.zylk.tools.xml.XmlUtils;
import net.zylk.torque.TorqueUtils;
import net.zylk.web.WebUtils;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Aug 10 13:35:35 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
 
 
public class TareasController
    extends net.idtoki.instelec.controller.BaseTareasController
{
 private static final Logger logger = Logger.getLogger("net.idtoki.instelec.controller.TareasController");
 private TransformerFactory tFactory = TransformerFactory.newInstance();
 private Transformer tareas_transformer = null;  
 private Transformer tareass_transformer = null; 

 public void init(ServletConfig config)
 {
	super.init();
	ResourceBundle resource = ResourceBundle.getBundle("net/idtoki/instelec/app/config/app-config");
	File tareas = new File(resource.getString("app.xsl.templates.dir")+"/PdfTareas.xslt");
	Source xslSource = new StreamSource(tareas);
	File tareass = new File(resource.getString("app.xsl.templates.dir")+"/PdfListaTareas.xslt");
	Source xslSourceT = new StreamSource(tareass); 	  
	try{
		tareas_transformer = tFactory.newTransformer(xslSource);
		tareass_transformer = tFactory.newTransformer(xslSourceT);			  
	}catch (Exception e){
	  e.printStackTrace();
	}
 }


//Función para la inserción/actualización de registros

public void serviceAddTareas(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 //Con esto se consigue transformar el request a UTF
	 //para temas de acentos y otros caracteres
	 utf8RequestService(request);

	 //recojo los parametros del formulario y doy de alta un nuevo elmento
	 try
	 {
		 Tareas elTareas = TareasHelper.createObj(request);
		 TareasGroupBean gbTareas = new TareasGroupBean();
		 elTareas.setFechainicio(FormatUtils.ddmmaaaa2aaaammdd(elTareas.getFechainicio(),"-",""));
		 gbTareas.setElemento(elTareas);
		 gbTareas.save();
	 }
	 catch(TorqueException te)
	 {
		 response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
	 }
 }


//Función para la eliminación de un registro
//este método invoca al método public void deleteTareas(int idBorrar)
//definido en el TareasManager
 public void serviceDeleteTareas(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 int idBorrar=-1;
	 idBorrar=WebUtils.getintParam(request, "borrarId");
	 if (idBorrar!=-1)
 		 if (TareasManager.borraTareas(idBorrar))
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlOKResponse("ISO-8859-1"));
		 else
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlNotOKResponse("ISO-8859-1"));			 
 }


// Funciones para las ordenaciones y filtrados de información

 private Criteria ordenacion(Criteria c,String CampoOrdenacion,String OrdenOrdenacion) 
 { 
 	if((OrdenOrdenacion != null )&& (OrdenOrdenacion.compareTo("ASC")==0))
 		if ((CampoOrdenacion != null))
 		{
 			c.addAscendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	if  ((OrdenOrdenacion != null) && (OrdenOrdenacion.compareTo("DESC")==0))
 		if ((CampoOrdenacion != null))
		{
 			c.addDescendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	return c;
 }

private Criteria filtro(Criteria c,int filtro) 
{ 
	String cadena = null;
	 switch (filtro)
	 {
	 case 1:
		  //Caso uno de Filtrado
		  //c.add(Campo,valor);
		  break;
	 case 2:
		  //Caso dos de Filtrado
		  //c.add(Campo,valor);
		  break;
	 default:
		 //caso por defecto
		 break;
	 }
	return c;
}

 public StringBuffer replaceStringBuffer (StringBuffer strBA, String strOrigen, String strDestino) 
 {
	 return new StringBuffer(strBA.toString().replaceAll(strOrigen,strDestino));
 }

 private Criteria criteriaTareasTableContent(HttpServletRequest request,Criteria c) throws IOException, ServletException
 {
 	String param = "";	 
	 param =  WebUtils.getStringParam(request, new OrdenestrabajoHelper().getIdordenName());
	 if(param != null)
		 TorqueUtils.addEqualCriteria(c,TareasPeer.IDORDEN,param);
	 param =  WebUtils.getStringParam(request, new TipotareasHelper().getIdtipotareaName());
	 if(param != null)
		 TorqueUtils.addEqualCriteria(c,TareasPeer.IDTIPOTAREA,param);
	 param =  WebUtils.getStringParam(request, new CategoriasHelper().getIdcategoriaName());
	 if(param != null)
		 TorqueUtils.addEqualCriteria(c,TareasPeer.IDCATEGORIA,param);
	  String paramSortCol =  WebUtils.getStringParam(request, "sort_col");
	  String paramSortDir =  WebUtils.getStringParam(request, "sort_dir");
	  int paramFiltro =  WebUtils.getintParam(request, "filtro");
	  c = ordenacion(c,paramSortCol,paramSortDir);
	  c = filtro(c,paramFiltro);

 	  return c;
 } 
 
 public String getPathElementTareas(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;
	 int claveFkId=-1;	 
	 claveId=WebUtils.getintParam(request, "tareas.IDTAREA");
	 if (claveId!=-1)
	 {
		c.add(TareasPeer.IDTAREA, claveId);
		TareasGroupBean trgb = TareasManager.getTareass(c);							
		strPath = trgb.getTareas(0).getPathTareasParsed(request.getQueryString());
	 }
	 return "<path>" + strPath + "</path>";
 } 
 
 public String getPathTableContentTareas(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;	 
	 claveId=WebUtils.getintParam(request, "ordenestrabajo.IDORDEN");
	 if(claveId != -1){
		 strPath = OrdenestrabajoManager.getOrdenestrabajo(claveId).getPathOrdenestrabajoParsed(request.getQueryString());
	 }		 	 
	 claveId=WebUtils.getintParam(request, "tipotareas.IDTIPOTAREA");
	 if(claveId != -1){
		 strPath = TipotareasManager.getTipotareas(claveId).getPathTipotareasParsed(request.getQueryString());
	 }		 	 
	 claveId=WebUtils.getintParam(request, "categorias.IDCATEGORIA");
	 if(claveId != -1){
		 strPath = CategoriasManager.getCategorias(claveId).getPathCategoriasParsed(request.getQueryString());
	 }		 	 
	 return "<path>" + strPath + "</path>";
 }  


public void  serviceTareasTableContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 utf8RequestService(request);
	 int numElemPedidosBD = 40;
	 int gap = 0;//gap = viewedRows - numElemVisiblesUltPag	  
	 DinamicGridBean dgb = WebUtils.getDinamicGridBeanParam(request,numElemPedidosBD,gap); 
	 Criteria c =TareasManager.buildSearchCriteria(dgb);
	 c =criteriaTareasTableContent(request,c);	 
	 TareasGroupBean cgb = TareasManager.getTareass(c);
	 dgb.setTotalSize(cgb.getTotalSize());
	  
	 String[] methodos= new String[] {
		TareasHelper.FECHAINICIO_GET_METHOD_NAME+"TareasParsed"
		,TareasHelper.HORAS_GET_METHOD_NAME+"TareasParsed"
		,TareasHelper.IDORDEN_GET_METHOD_NAME+"TareasParsed"
		,TareasHelper.IDTIPOTAREA_GET_METHOD_NAME+"TareasParsed"
		,TareasHelper.IDCATEGORIA_GET_METHOD_NAME+"TareasParsed"
		,TareasHelper.OBSERVACIONES_GET_METHOD_NAME+"TareasParsed"
		,"getHijosMaterialesTareas"
		,"getEditTareas"
		,"getDeleteTareas"
	};
	 
	 StringBuffer cadena=null;
	 cadena = AjaxUtils.buildXmlAjaxResponseTableContentFromListObj(cgb.getAlmacen(),methodos,TareasHelper.IDTAREA_GET_METHOD_NAME, dgb,"ISO-8859-1"); 
	 cadena.insert(cadena.indexOf("</ajax-response>"),"<response type='object' id='divPath'>" + getPathTableContentTareas(request,response) + "</response>");
	 xmlResponseService(response,cadena); 
 }  

 public void serviceTareasUlContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] methodos= new String[] {
	 		"getULContentTareasParsed"
			 };
	 String param =  WebUtils.getStringParam(request, "value");
	 if(param==null || param.length() <= 0)
		 param =  WebUtils.getStringParam(request, new MaterialesHelper().getIdtareaName());
	 	 
	 TareasGroupBean mgb = TareasManager.getTareass(TareasManager.buildSearchCriteria(param));
	 simpleResponseService(response, AjaxUtils.buildAjaxULContentFromListObj(mgb.getAlmacen(),methodos, TareasHelper.COMPLEX_ID_GET_METHOD,"Tareas"));
 } 



 public void serviceTareasElement(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
  StringBuffer cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "tareas.IDTAREA");
  if (claveId!=-1)
  {
	  c.add(TareasPeer.IDTAREA, claveId);
  }
  c.addAscendingOrderByColumn(TareasPeer.IDTAREA);
  TareasGroupBean trgb = TareasManager.getTareass(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  String [] parametros={
		TareasHelper.IDTAREA_GET_METHOD_NAME
		,TareasHelper.FECHAINICIO_GET_METHOD_NAME+"TareasParsed"
		,TareasHelper.HORAS_GET_METHOD_NAME+"TareasParsed"
		,TareasHelper.IDORDEN_GET_METHOD_NAME+"TareasParsed"
		,TareasHelper.IDTIPOTAREA_GET_METHOD_NAME+"TareasParsed"
		,TareasHelper.IDCATEGORIA_GET_METHOD_NAME+"TareasParsed"
		,TareasHelper.OBSERVACIONES_GET_METHOD_NAME+"TareasParsed"
		,"getImporteCalculadoTareasParsed"
		,"getManoObraCalculadoTareasParsed"
	  };
	  cadena=trgb.buildXml(parametros,null,"ISO-8859-1");	
	  cadena.insert(cadena.indexOf("</result>"),getPathElementTareas(request,response));  
  }
  xmlResponseService(response, cadena);
 }  
 
 

 protected StringBuffer updateIdtareaResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TareasManager.getTareas(Integer.parseInt(a.get(0).toString())).getIdtareaTareasParsed());
 }  
 

 protected StringBuffer updateFechainicioResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TareasManager.getTareas(Integer.parseInt(a.get(0).toString())).getFechainicioTareasParsed());
 }  
 

 protected StringBuffer updateHorasResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TareasManager.getTareas(Integer.parseInt(a.get(0).toString())).getHorasTareasParsed());
 }  
 

 protected StringBuffer updateIdordenResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TareasManager.getTareas(Integer.parseInt(a.get(0).toString())).getIdordenTareasParsed());
 }  
 

 protected StringBuffer updateIdtipotareaResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TareasManager.getTareas(Integer.parseInt(a.get(0).toString())).getIdtipotareaTareasParsed());
 }  
 

 protected StringBuffer updateIdcategoriaResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TareasManager.getTareas(Integer.parseInt(a.get(0).toString())).getIdcategoriaTareasParsed());
 }  
 

 protected StringBuffer updateObservacionesResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TareasManager.getTareas(Integer.parseInt(a.get(0).toString())).getObservacionesTareasParsed());
 }  
 
 
 	
 
 public void serviceTareasOrdenestrabajo(HttpServletRequest request, HttpServletResponse response) throws IOException, TorqueException, ServletException
 {
  String cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "ordenestrabajo.IDORDEN");
  if (claveId!=-1)
  {
	  c.add(OrdenestrabajoPeer.IDORDEN, claveId);
  }
  c.addAscendingOrderByColumn(OrdenestrabajoPeer.IDORDEN);
  OrdenestrabajoGroupBean trgb = OrdenestrabajoManager.getOrdenestrabajos(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  cadena = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>";
	  cadena = cadena + "<result><tareas.IDORDEN>" + trgb.getOrdenestrabajo(0).getULContentOrdenestrabajoParsed()  + "</tareas.IDORDEN></result>";
  }
  
  xmlResponseService(response, new StringBuffer(cadena));
 }  
  			

 public void serviceTareasTipotareas(HttpServletRequest request, HttpServletResponse response) throws IOException, TorqueException, ServletException
 {
  String cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "tipotareas.IDTIPOTAREA");
  if (claveId!=-1)
  {
	  c.add(TipotareasPeer.IDTIPOTAREA, claveId);
  }
  c.addAscendingOrderByColumn(TipotareasPeer.IDTIPOTAREA);
  TipotareasGroupBean trgb = TipotareasManager.getTipotareass(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  cadena = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>";
	  cadena = cadena + "<result><tareas.IDTIPOTAREA>" + trgb.getTipotareas(0).getULContentTipotareasParsed()  + "</tareas.IDTIPOTAREA></result>";
  }
  
  xmlResponseService(response, new StringBuffer(cadena));
 }  
  			

 public void serviceTareasCategorias(HttpServletRequest request, HttpServletResponse response) throws IOException, TorqueException, ServletException
 {
  String cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "categorias.IDCATEGORIA");
  if (claveId!=-1)
  {
	  c.add(CategoriasPeer.IDCATEGORIA, claveId);
  }
  c.addAscendingOrderByColumn(CategoriasPeer.IDCATEGORIA);
  CategoriasGroupBean trgb = CategoriasManager.getCategoriass(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  cadena = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>";
	  cadena = cadena + "<result><tareas.IDCATEGORIA>" + trgb.getCategorias(0).getULContentCategoriasParsed()  + "</tareas.IDCATEGORIA></result>";
  }
  
  xmlResponseService(response, new StringBuffer(cadena));
 }  
  			

 public void serviceGetTareasDetallePdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] getMethodos= new String[] {
		TareasHelper.IDTAREA_GET_METHOD_NAME
		,TareasHelper.FECHAINICIO_GET_METHOD_NAME+"TareasParsed"
		,TareasHelper.HORAS_GET_METHOD_NAME+"TareasParsed"
		,TareasHelper.IDORDEN_GET_METHOD_NAME+"TareasParsed"
		,TareasHelper.IDTIPOTAREA_GET_METHOD_NAME+"TareasParsed"
		,TareasHelper.IDCATEGORIA_GET_METHOD_NAME+"TareasParsed"
		,TareasHelper.OBSERVACIONES_GET_METHOD_NAME+"TareasParsed"
			 };
	  
	 
	 TareasGroupBean tgb = new TareasGroupBean();
	 try
	{
		tgb.setElemento(TareasHelper.getTareas(request));
	} catch (TorqueException e)
	{
		logger.severe(e.getMessage());
	}
	
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(getMethodos, null,"ISO-8859-1"),"n/a"," "), tareas_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=Tareas.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
	
 }  

 public void serviceTareasTableContentPdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
  	utf8RequestService(request);
  	Criteria c= new Criteria();
  	String paramQuery =  WebUtils.getStringParam(request, "query");
  	if ((paramQuery != null)&& (paramQuery.compareTo("")!=0) )
		c = TareasManager.buildSearchCriteria(paramQuery);   
  	c =criteriaTareasTableContent(request,c);	  
  	TareasGroupBean tgb = TareasManager.getTareass(c);
  
  	String[] methodos= new String[] {	
		TareasHelper.FECHAINICIO_GET_METHOD_NAME+"TareasParsed"
		,TareasHelper.HORAS_GET_METHOD_NAME+"TareasParsed"
		,TareasHelper.IDORDEN_GET_METHOD_NAME+"TareasParsed"
		,TareasHelper.IDTIPOTAREA_GET_METHOD_NAME+"TareasParsed"
		,TareasHelper.IDCATEGORIA_GET_METHOD_NAME+"TareasParsed"
		,TareasHelper.OBSERVACIONES_GET_METHOD_NAME+"TareasParsed"
			};
  
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(methodos, null,"ISO-8859-1"),"n/a"," "), tareass_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=ListaTareas.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
 }

 public void serviceCosteCategoriasTareas(HttpServletRequest request, HttpServletResponse response) throws IOException, TorqueException, ServletException
 {
  String cadena=null;
  Criteria c= new Criteria();
  String claveId="";
  claveId=WebUtils.getStringParam(request, "tareas.IDCATEGORIA");
  if (claveId!="")
  {
	  int iId = Integer.parseInt(claveId.split("-")[0]);
	  c.add(CategoriasPeer.IDCATEGORIA, iId);
  }
  CategoriasGroupBean trgb = CategoriasManager.getCategoriass(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  cadena = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>";
	  cadena = cadena + "<result><tareas.COSTECATEGORIA>" + trgb.getCategorias(0).getCoste()  + "</tareas.COSTECATEGORIA></result>";
  }
  
  xmlResponseService(response, new StringBuffer(cadena));
 } 
 
}


