package net.idtoki.instelec.controller;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.ResourceBundle;
import java.util.logging.Logger;

import javax.servlet.ServletConfig;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamSource;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

import net.idtoki.instelec.manager.TipomaterialesManager;
import net.idtoki.instelec.group.TipomaterialesGroupBean;
import net.idtoki.instelec.helper.TipomaterialesHelper;
import net.idtoki.instelec.model.TipomaterialesPeer;
import net.idtoki.instelec.model.Tipomateriales;


import net.idtoki.instelec.helper.MaterialesHelper;


import net.zylk.tools.ajax.AjaxUtils;
import net.zylk.tools.ajax.AjaxUtils.DinamicGridBean;
import net.zylk.tools.format.FormatUtils;
import net.zylk.tools.pdf.PdfUtils;
import net.zylk.tools.xml.XmlUtils;
import net.zylk.torque.TorqueUtils;
import net.zylk.web.WebUtils;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Aug 10 13:35:35 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
 
 
public class TipomaterialesController
    extends net.idtoki.instelec.controller.BaseTipomaterialesController
{
 private static final Logger logger = Logger.getLogger("net.idtoki.instelec.controller.TipomaterialesController");
 private TransformerFactory tFactory = TransformerFactory.newInstance();
 private Transformer tipomateriales_transformer = null;  
 private Transformer tipomaterialess_transformer = null; 

 public void init(ServletConfig config)
 {
	super.init();
	ResourceBundle resource = ResourceBundle.getBundle("net/idtoki/instelec/app/config/app-config");
	File tipomateriales = new File(resource.getString("app.xsl.templates.dir")+"/PdfTipomateriales.xslt");
	Source xslSource = new StreamSource(tipomateriales);
	File tipomaterialess = new File(resource.getString("app.xsl.templates.dir")+"/PdfListaTipomateriales.xslt");
	Source xslSourceT = new StreamSource(tipomaterialess); 	  
	try{
		tipomateriales_transformer = tFactory.newTransformer(xslSource);
		tipomaterialess_transformer = tFactory.newTransformer(xslSourceT);			  
	}catch (Exception e){
	  e.printStackTrace();
	}
 }


//Función para la inserción/actualización de registros

public void serviceAddTipomateriales(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 //Con esto se consigue transformar el request a UTF
	 //para temas de acentos y otros caracteres
	 utf8RequestService(request);

	 //recojo los parametros del formulario y doy de alta un nuevo elmento
	 try
	 {
		 Tipomateriales elTipomateriales = TipomaterialesHelper.createObj(request);
		 TipomaterialesGroupBean gbTipomateriales = new TipomaterialesGroupBean();
		 gbTipomateriales.setElemento(elTipomateriales);
		 gbTipomateriales.save();
	 }
	 catch(TorqueException te)
	 {
		 response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
	 }
 }


//Función para la eliminación de un registro
//este método invoca al método public void deleteTipomateriales(int idBorrar)
//definido en el TipomaterialesManager
 public void serviceDeleteTipomateriales(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 int idBorrar=-1;
	 idBorrar=WebUtils.getintParam(request, "borrarId");
	 if (idBorrar!=-1)
 		 if (TipomaterialesManager.borraTipomateriales(idBorrar))
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlOKResponse("ISO-8859-1"));
		 else
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlNotOKResponse("ISO-8859-1"));			 
 }


// Funciones para las ordenaciones y filtrados de información

 private Criteria ordenacion(Criteria c,String CampoOrdenacion,String OrdenOrdenacion) 
 { 
 	if((OrdenOrdenacion != null )&& (OrdenOrdenacion.compareTo("ASC")==0))
 		if ((CampoOrdenacion != null))
 		{
 			c.addAscendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	if  ((OrdenOrdenacion != null) && (OrdenOrdenacion.compareTo("DESC")==0))
 		if ((CampoOrdenacion != null))
		{
 			c.addDescendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	return c;
 }

private Criteria filtro(Criteria c,int filtro) 
{ 
	String cadena = null;
	 switch (filtro)
	 {
	 case 1:
		  //Caso uno de Filtrado
		  //c.add(Campo,valor);
		  break;
	 case 2:
		  //Caso dos de Filtrado
		  //c.add(Campo,valor);
		  break;
	 default:
		 //caso por defecto
		 break;
	 }
	return c;
}

 public StringBuffer replaceStringBuffer (StringBuffer strBA, String strOrigen, String strDestino) 
 {
	 return new StringBuffer(strBA.toString().replaceAll(strOrigen,strDestino));
 }

 private Criteria criteriaTipomaterialesTableContent(HttpServletRequest request,Criteria c) throws IOException, ServletException
 {
 	String param = "";	 
	  String paramSortCol =  WebUtils.getStringParam(request, "sort_col");
	  String paramSortDir =  WebUtils.getStringParam(request, "sort_dir");
	  int paramFiltro =  WebUtils.getintParam(request, "filtro");
	  c = ordenacion(c,paramSortCol,paramSortDir);
	  c = filtro(c,paramFiltro);

 	  return c;
 } 
 
 public String getPathElementTipomateriales(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;
	 int claveFkId=-1;	 
	 claveId=WebUtils.getintParam(request, "tipomateriales.IDTIPOMATERIAL");
	 if (claveId!=-1)
	 {
		c.add(TipomaterialesPeer.IDTIPOMATERIAL, claveId);
		TipomaterialesGroupBean trgb = TipomaterialesManager.getTipomaterialess(c);							
		strPath = trgb.getTipomateriales(0).getPathTipomaterialesParsed(request.getQueryString());
	 }
	 return "<path>" + strPath + "</path>";
 } 
 
 public String getPathTableContentTipomateriales(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;	 
	 return "<path>" + strPath + "</path>";
 }  


public void  serviceTipomaterialesTableContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 utf8RequestService(request);
	 int numElemPedidosBD = 40;
	 int gap = 0;//gap = viewedRows - numElemVisiblesUltPag	  
	 DinamicGridBean dgb = WebUtils.getDinamicGridBeanParam(request,numElemPedidosBD,gap); 
	 Criteria c =TipomaterialesManager.buildSearchCriteria(dgb);
	 c =criteriaTipomaterialesTableContent(request,c);	 
	 TipomaterialesGroupBean cgb = TipomaterialesManager.getTipomaterialess(c);
	 dgb.setTotalSize(cgb.getTotalSize());
	  
	 String[] methodos= new String[] {
		TipomaterialesHelper.DESCRIPCION_GET_METHOD_NAME+"TipomaterialesParsed"
		,"getHijosMaterialesTipomateriales"
		,"getEditTipomateriales"
		,"getDeleteTipomateriales"
	};
	 
	 StringBuffer cadena=null;
	 cadena = AjaxUtils.buildXmlAjaxResponseTableContentFromListObj(cgb.getAlmacen(),methodos,TipomaterialesHelper.IDTIPOMATERIAL_GET_METHOD_NAME, dgb,"ISO-8859-1"); 
	 cadena.insert(cadena.indexOf("</ajax-response>"),"<response type='object' id='divPath'>" + getPathTableContentTipomateriales(request,response) + "</response>");
	 xmlResponseService(response,cadena); 
 }  

 public void serviceTipomaterialesUlContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] methodos= new String[] {
	 		"getULContentTipomaterialesParsed"
			 };
	 String param =  WebUtils.getStringParam(request, "value");
	 if(param==null || param.length() <= 0)
		 param =  WebUtils.getStringParam(request, new MaterialesHelper().getIdtipomaterialName());
	 	 
	 TipomaterialesGroupBean mgb = TipomaterialesManager.getTipomaterialess(TipomaterialesManager.buildSearchCriteria(param));
	 simpleResponseService(response, AjaxUtils.buildAjaxULContentFromListObj(mgb.getAlmacen(),methodos, TipomaterialesHelper.COMPLEX_ID_GET_METHOD,"Tipomateriales"));
 } 



 protected StringBuffer updateIdtipomaterialResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TipomaterialesManager.getTipomateriales(Integer.parseInt(a.get(0).toString())).getIdtipomaterialTipomaterialesParsed());
 }  
 

 protected StringBuffer updateDescripcionResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TipomaterialesManager.getTipomateriales(Integer.parseInt(a.get(0).toString())).getDescripcionTipomaterialesParsed());
 }  
 

 public void serviceTipomaterialesElement(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
  StringBuffer cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "tipomateriales.IDTIPOMATERIAL");
  if (claveId!=-1)
  {
	  c.add(TipomaterialesPeer.IDTIPOMATERIAL, claveId);
  }
  c.addAscendingOrderByColumn(TipomaterialesPeer.IDTIPOMATERIAL);
  TipomaterialesGroupBean trgb = TipomaterialesManager.getTipomaterialess(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  String [] parametros={
		TipomaterialesHelper.IDTIPOMATERIAL_GET_METHOD_NAME
		,TipomaterialesHelper.DESCRIPCION_GET_METHOD_NAME+"TipomaterialesParsed"
	  };
	  cadena=trgb.buildXml(parametros,null,"ISO-8859-1");	
	  cadena.insert(cadena.indexOf("</result>"),getPathElementTipomateriales(request,response));  
  }
  xmlResponseService(response, cadena);
 }  
 

 public void serviceGetTipomaterialesDetallePdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] getMethodos= new String[] {
		TipomaterialesHelper.IDTIPOMATERIAL_GET_METHOD_NAME
		,TipomaterialesHelper.DESCRIPCION_GET_METHOD_NAME+"TipomaterialesParsed"
			 };
	  
	 
	 TipomaterialesGroupBean tgb = new TipomaterialesGroupBean();
	 try
	{
		tgb.setElemento(TipomaterialesHelper.getTipomateriales(request));
	} catch (TorqueException e)
	{
		logger.severe(e.getMessage());
	}
	
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(getMethodos, null,"ISO-8859-1"),"n/a"," "), tipomateriales_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=Tipomateriales.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
	
 }  

 public void serviceTipomaterialesTableContentPdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
  	utf8RequestService(request);
  	Criteria c= new Criteria();
  	String paramQuery =  WebUtils.getStringParam(request, "query");
  	if ((paramQuery != null)&& (paramQuery.compareTo("")!=0) )
		c = TipomaterialesManager.buildSearchCriteria(paramQuery);   
  	c =criteriaTipomaterialesTableContent(request,c);	  
  	TipomaterialesGroupBean tgb = TipomaterialesManager.getTipomaterialess(c);
  
  	String[] methodos= new String[] {	
		TipomaterialesHelper.DESCRIPCION_GET_METHOD_NAME+"TipomaterialesParsed"
			};
  
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(methodos, null,"ISO-8859-1"),"n/a"," "), tipomaterialess_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=ListaTipomateriales.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
 }

}


