package net.idtoki.instelec.controller;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.ResourceBundle;
import java.util.logging.Logger;

import javax.servlet.ServletConfig;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamSource;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

import net.idtoki.instelec.manager.TipotareasManager;
import net.idtoki.instelec.group.TipotareasGroupBean;
import net.idtoki.instelec.helper.TipotareasHelper;
import net.idtoki.instelec.model.TipotareasPeer;
import net.idtoki.instelec.model.Tipotareas;


import net.idtoki.instelec.helper.TareasHelper;


import net.zylk.tools.ajax.AjaxUtils;
import net.zylk.tools.ajax.AjaxUtils.DinamicGridBean;
import net.zylk.tools.format.FormatUtils;
import net.zylk.tools.pdf.PdfUtils;
import net.zylk.tools.xml.XmlUtils;
import net.zylk.torque.TorqueUtils;
import net.zylk.web.WebUtils;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Aug 10 13:35:35 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
 
 
public class TipotareasController
    extends net.idtoki.instelec.controller.BaseTipotareasController
{
 private static final Logger logger = Logger.getLogger("net.idtoki.instelec.controller.TipotareasController");
 private TransformerFactory tFactory = TransformerFactory.newInstance();
 private Transformer tipotareas_transformer = null;  
 private Transformer tipotareass_transformer = null; 

 public void init(ServletConfig config)
 {
	super.init();
	ResourceBundle resource = ResourceBundle.getBundle("net/idtoki/instelec/app/config/app-config");
	File tipotareas = new File(resource.getString("app.xsl.templates.dir")+"/PdfTipotareas.xslt");
	Source xslSource = new StreamSource(tipotareas);
	File tipotareass = new File(resource.getString("app.xsl.templates.dir")+"/PdfListaTipotareas.xslt");
	Source xslSourceT = new StreamSource(tipotareass); 	  
	try{
		tipotareas_transformer = tFactory.newTransformer(xslSource);
		tipotareass_transformer = tFactory.newTransformer(xslSourceT);			  
	}catch (Exception e){
	  e.printStackTrace();
	}
 }


//Función para la inserción/actualización de registros

public void serviceAddTipotareas(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 //Con esto se consigue transformar el request a UTF
	 //para temas de acentos y otros caracteres
	 utf8RequestService(request);

	 //recojo los parametros del formulario y doy de alta un nuevo elmento
	 try
	 {
		 Tipotareas elTipotareas = TipotareasHelper.createObj(request);
		 TipotareasGroupBean gbTipotareas = new TipotareasGroupBean();
		 gbTipotareas.setElemento(elTipotareas);
		 gbTipotareas.save();
	 }
	 catch(TorqueException te)
	 {
		 response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
	 }
 }


//Función para la eliminación de un registro
//este método invoca al método public void deleteTipotareas(int idBorrar)
//definido en el TipotareasManager
 public void serviceDeleteTipotareas(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 int idBorrar=-1;
	 idBorrar=WebUtils.getintParam(request, "borrarId");
	 if (idBorrar!=-1)
 		 if (TipotareasManager.borraTipotareas(idBorrar))
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlOKResponse("ISO-8859-1"));
		 else
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlNotOKResponse("ISO-8859-1"));			 
 }


// Funciones para las ordenaciones y filtrados de información

 private Criteria ordenacion(Criteria c,String CampoOrdenacion,String OrdenOrdenacion) 
 { 
 	if((OrdenOrdenacion != null )&& (OrdenOrdenacion.compareTo("ASC")==0))
 		if ((CampoOrdenacion != null))
 		{
 			c.addAscendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	if  ((OrdenOrdenacion != null) && (OrdenOrdenacion.compareTo("DESC")==0))
 		if ((CampoOrdenacion != null))
		{
 			c.addDescendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	return c;
 }

private Criteria filtro(Criteria c,int filtro) 
{ 
	String cadena = null;
	 switch (filtro)
	 {
	 case 1:
		  //Caso uno de Filtrado
		  //c.add(Campo,valor);
		  break;
	 case 2:
		  //Caso dos de Filtrado
		  //c.add(Campo,valor);
		  break;
	 default:
		 //caso por defecto
		 break;
	 }
	return c;
}

 public StringBuffer replaceStringBuffer (StringBuffer strBA, String strOrigen, String strDestino) 
 {
	 return new StringBuffer(strBA.toString().replaceAll(strOrigen,strDestino));
 }

 private Criteria criteriaTipotareasTableContent(HttpServletRequest request,Criteria c) throws IOException, ServletException
 {
 	String param = "";	 
	  String paramSortCol =  WebUtils.getStringParam(request, "sort_col");
	  String paramSortDir =  WebUtils.getStringParam(request, "sort_dir");
	  int paramFiltro =  WebUtils.getintParam(request, "filtro");
	  c = ordenacion(c,paramSortCol,paramSortDir);
	  c = filtro(c,paramFiltro);

 	  return c;
 } 
 
 public String getPathElementTipotareas(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;
	 int claveFkId=-1;	 
	 claveId=WebUtils.getintParam(request, "tipotareas.IDTIPOTAREA");
	 if (claveId!=-1)
	 {
		c.add(TipotareasPeer.IDTIPOTAREA, claveId);
		TipotareasGroupBean trgb = TipotareasManager.getTipotareass(c);							
		strPath = trgb.getTipotareas(0).getPathTipotareasParsed(request.getQueryString());
	 }
	 return "<path>" + strPath + "</path>";
 } 
 
 public String getPathTableContentTipotareas(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;	 
	 return "<path>" + strPath + "</path>";
 }  


public void  serviceTipotareasTableContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 utf8RequestService(request);
	 int numElemPedidosBD = 40;
	 int gap = 0;//gap = viewedRows - numElemVisiblesUltPag	  
	 DinamicGridBean dgb = WebUtils.getDinamicGridBeanParam(request,numElemPedidosBD,gap); 
	 Criteria c =TipotareasManager.buildSearchCriteria(dgb);
	 c =criteriaTipotareasTableContent(request,c);	 
	 TipotareasGroupBean cgb = TipotareasManager.getTipotareass(c);
	 dgb.setTotalSize(cgb.getTotalSize());
	  
	 String[] methodos= new String[] {
		TipotareasHelper.DESCRIPCION_GET_METHOD_NAME+"TipotareasParsed"
		,"getHijosTareasTipotareas"
		,"getEditTipotareas"
		,"getDeleteTipotareas"
	};
	 
	 StringBuffer cadena=null;
	 cadena = AjaxUtils.buildXmlAjaxResponseTableContentFromListObj(cgb.getAlmacen(),methodos,TipotareasHelper.IDTIPOTAREA_GET_METHOD_NAME, dgb,"ISO-8859-1"); 
	 cadena.insert(cadena.indexOf("</ajax-response>"),"<response type='object' id='divPath'>" + getPathTableContentTipotareas(request,response) + "</response>");
	 xmlResponseService(response,cadena); 
 }  

 public void serviceTipotareasUlContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] methodos= new String[] {
	 		"getULContentTipotareasParsed"
			 };
	 String param =  WebUtils.getStringParam(request, "value");
	 if(param==null || param.length() <= 0)
		 param =  WebUtils.getStringParam(request, new TareasHelper().getIdtipotareaName());
	 	 
	 TipotareasGroupBean mgb = TipotareasManager.getTipotareass(TipotareasManager.buildSearchCriteria(param));
	 simpleResponseService(response, AjaxUtils.buildAjaxULContentFromListObj(mgb.getAlmacen(),methodos, TipotareasHelper.COMPLEX_ID_GET_METHOD,"Tipotareas"));
 } 



 public void serviceTipotareasElement(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
  StringBuffer cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "tipotareas.IDTIPOTAREA");
  if (claveId!=-1)
  {
	  c.add(TipotareasPeer.IDTIPOTAREA, claveId);
  }
  c.addAscendingOrderByColumn(TipotareasPeer.IDTIPOTAREA);
  TipotareasGroupBean trgb = TipotareasManager.getTipotareass(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  String [] parametros={
		TipotareasHelper.IDTIPOTAREA_GET_METHOD_NAME
		,TipotareasHelper.DESCRIPCION_GET_METHOD_NAME+"TipotareasParsed"
	  };
	  cadena=trgb.buildXml(parametros,null,"ISO-8859-1");	
	  cadena.insert(cadena.indexOf("</result>"),getPathElementTipotareas(request,response));  
  }
  xmlResponseService(response, cadena);
 }  
 
 

 protected StringBuffer updateIdtipotareaResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TipotareasManager.getTipotareas(Integer.parseInt(a.get(0).toString())).getIdtipotareaTipotareasParsed());
 }  
 

 protected StringBuffer updateDescripcionResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TipotareasManager.getTipotareas(Integer.parseInt(a.get(0).toString())).getDescripcionTipotareasParsed());
 }  
 
 

 public void serviceGetTipotareasDetallePdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] getMethodos= new String[] {
		TipotareasHelper.IDTIPOTAREA_GET_METHOD_NAME
		,TipotareasHelper.DESCRIPCION_GET_METHOD_NAME+"TipotareasParsed"
			 };
	  
	 
	 TipotareasGroupBean tgb = new TipotareasGroupBean();
	 try
	{
		tgb.setElemento(TipotareasHelper.getTipotareas(request));
	} catch (TorqueException e)
	{
		logger.severe(e.getMessage());
	}
	
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(getMethodos, null,"ISO-8859-1"),"n/a"," "), tipotareas_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=Tipotareas.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
	
 }  

 public void serviceTipotareasTableContentPdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
  	utf8RequestService(request);
  	Criteria c= new Criteria();
  	String paramQuery =  WebUtils.getStringParam(request, "query");
  	if ((paramQuery != null)&& (paramQuery.compareTo("")!=0) )
		c = TipotareasManager.buildSearchCriteria(paramQuery);   
  	c =criteriaTipotareasTableContent(request,c);	  
  	TipotareasGroupBean tgb = TipotareasManager.getTipotareass(c);
  
  	String[] methodos= new String[] {	
		TipotareasHelper.DESCRIPCION_GET_METHOD_NAME+"TipotareasParsed"
			};
  
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(methodos, null,"ISO-8859-1"),"n/a"," "), tipotareass_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=ListaTipotareas.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
 }

}


