package net.idtoki.instelec.controller;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.ResourceBundle;
import java.util.logging.Logger;

import javax.servlet.ServletConfig;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamSource;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

import net.idtoki.instelec.manager.TrabajadoresManager;
import net.idtoki.instelec.group.TrabajadoresGroupBean;
import net.idtoki.instelec.helper.TrabajadoresHelper;
import net.idtoki.instelec.model.TrabajadoresPeer;
import net.idtoki.instelec.model.Trabajadores;

import net.idtoki.instelec.manager.CategoriasManager;
import net.idtoki.instelec.group.CategoriasGroupBean;
import net.idtoki.instelec.model.CategoriasPeer;
import net.idtoki.instelec.helper.CategoriasHelper;
import net.idtoki.instelec.manager.LocalidadesManager;
import net.idtoki.instelec.group.LocalidadesGroupBean;
import net.idtoki.instelec.model.LocalidadesPeer;
import net.idtoki.instelec.helper.LocalidadesHelper;

import net.idtoki.instelec.helper.PartesHelper;


import net.zylk.tools.ajax.AjaxUtils;
import net.zylk.tools.ajax.AjaxUtils.DinamicGridBean;
import net.zylk.tools.format.FormatUtils;
import net.zylk.tools.pdf.PdfUtils;
import net.zylk.tools.xml.XmlUtils;
import net.zylk.torque.TorqueUtils;
import net.zylk.web.WebUtils;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Aug 10 13:35:35 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
 
 
public class TrabajadoresController
    extends net.idtoki.instelec.controller.BaseTrabajadoresController
{
 private static final Logger logger = Logger.getLogger("net.idtoki.instelec.controller.TrabajadoresController");
 private TransformerFactory tFactory = TransformerFactory.newInstance();
 private Transformer trabajadores_transformer = null;  
 private Transformer trabajadoress_transformer = null; 

 public void init(ServletConfig config)
 {
	super.init();
	ResourceBundle resource = ResourceBundle.getBundle("net/idtoki/instelec/app/config/app-config");
	File trabajadores = new File(resource.getString("app.xsl.templates.dir")+"/PdfTrabajadores.xslt");
	Source xslSource = new StreamSource(trabajadores);
	File trabajadoress = new File(resource.getString("app.xsl.templates.dir")+"/PdfListaTrabajadores.xslt");
	Source xslSourceT = new StreamSource(trabajadoress); 	  
	try{
		trabajadores_transformer = tFactory.newTransformer(xslSource);
		trabajadoress_transformer = tFactory.newTransformer(xslSourceT);			  
	}catch (Exception e){
	  e.printStackTrace();
	}
 }


//Función para la inserción/actualización de registros

public void serviceAddTrabajadores(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 //Con esto se consigue transformar el request a UTF
	 //para temas de acentos y otros caracteres
	 utf8RequestService(request);

	 //recojo los parametros del formulario y doy de alta un nuevo elmento
	 try
	 {
		 Trabajadores elTrabajadores = TrabajadoresHelper.createObj(request);
		 TrabajadoresGroupBean gbTrabajadores = new TrabajadoresGroupBean();
		 elTrabajadores.setFechaalta(FormatUtils.ddmmaaaa2aaaammdd(elTrabajadores.getFechaalta(),"-",""));
		 elTrabajadores.setFechabaja(FormatUtils.ddmmaaaa2aaaammdd(elTrabajadores.getFechabaja(),"-",""));
		 gbTrabajadores.setElemento(elTrabajadores);
		 gbTrabajadores.save();
	 }
	 catch(TorqueException te)
	 {
		 response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
	 }
 }


//Función para la eliminación de un registro
//este método invoca al método public void deleteTrabajadores(int idBorrar)
//definido en el TrabajadoresManager
 public void serviceDeleteTrabajadores(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 int idBorrar=-1;
	 idBorrar=WebUtils.getintParam(request, "borrarId");
	 if (idBorrar!=-1)
 		 if (TrabajadoresManager.borraTrabajadores(idBorrar))
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlOKResponse("ISO-8859-1"));
		 else
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlNotOKResponse("ISO-8859-1"));			 
 }


// Funciones para las ordenaciones y filtrados de información

 private Criteria ordenacion(Criteria c,String CampoOrdenacion,String OrdenOrdenacion) 
 { 
 	if((OrdenOrdenacion != null )&& (OrdenOrdenacion.compareTo("ASC")==0))
 		if ((CampoOrdenacion != null))
 		{
 			c.addAscendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	if  ((OrdenOrdenacion != null) && (OrdenOrdenacion.compareTo("DESC")==0))
 		if ((CampoOrdenacion != null))
		{
 			c.addDescendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	return c;
 }

private Criteria filtro(Criteria c,int filtro) 
{ 
	String cadena = null;
	 switch (filtro)
	 {
	 case 1:
		  //Caso uno de Filtrado
		  //c.add(Campo,valor);
		  break;
	 case 2:
		  //Caso dos de Filtrado
		  //c.add(Campo,valor);
		  break;
	 default:
		 //caso por defecto
		 break;
	 }
	return c;
}

 public StringBuffer replaceStringBuffer (StringBuffer strBA, String strOrigen, String strDestino) 
 {
	 return new StringBuffer(strBA.toString().replaceAll(strOrigen,strDestino));
 }

 private Criteria criteriaTrabajadoresTableContent(HttpServletRequest request,Criteria c) throws IOException, ServletException
 {
 	String param = "";	 
	 param =  WebUtils.getStringParam(request, new CategoriasHelper().getIdcategoriaName());
	 if(param != null)
		 TorqueUtils.addEqualCriteria(c,TrabajadoresPeer.IDCATEGORIA,param);
	 param =  WebUtils.getStringParam(request, new LocalidadesHelper().getIdlocalidadName());
	 if(param != null)
		 TorqueUtils.addEqualCriteria(c,TrabajadoresPeer.IDLOCALIDAD,param);
	  String paramSortCol =  WebUtils.getStringParam(request, "sort_col");
	  String paramSortDir =  WebUtils.getStringParam(request, "sort_dir");
	  int paramFiltro =  WebUtils.getintParam(request, "filtro");
	  c = ordenacion(c,paramSortCol,paramSortDir);
	  c = filtro(c,paramFiltro);

 	  return c;
 } 
 
 public String getPathElementTrabajadores(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;
	 int claveFkId=-1;	 
	 claveId=WebUtils.getintParam(request, "trabajadores.IDTRABAJADOR");
	 if (claveId!=-1)
	 {
		c.add(TrabajadoresPeer.IDTRABAJADOR, claveId);
		TrabajadoresGroupBean trgb = TrabajadoresManager.getTrabajadoress(c);							
		strPath = trgb.getTrabajadores(0).getPathTrabajadoresParsed(request.getQueryString());
	 }
	 return "<path>" + strPath + "</path>";
 } 
 
 public String getPathTableContentTrabajadores(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 Criteria c= new Criteria();
	 String strPath = "";
	 int claveId=-1;	 
	 claveId=WebUtils.getintParam(request, "categorias.IDCATEGORIA");
	 if(claveId != -1){
		 strPath = CategoriasManager.getCategorias(claveId).getPathCategoriasParsed(request.getQueryString());
	 }		 	 
	 claveId=WebUtils.getintParam(request, "localidades.IDLOCALIDAD");
	 if(claveId != -1){
		 strPath = LocalidadesManager.getLocalidades(claveId).getPathLocalidadesParsed(request.getQueryString());
	 }		 	 
	 return "<path>" + strPath + "</path>";
 }  


public void  serviceTrabajadoresTableContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
	 utf8RequestService(request);
	 int numElemPedidosBD = 40;
	 int gap = 0;//gap = viewedRows - numElemVisiblesUltPag	  
	 DinamicGridBean dgb = WebUtils.getDinamicGridBeanParam(request,numElemPedidosBD,gap); 
	 Criteria c =TrabajadoresManager.buildSearchCriteria(dgb);
	 c =criteriaTrabajadoresTableContent(request,c);	 
	 TrabajadoresGroupBean cgb = TrabajadoresManager.getTrabajadoress(c);
	 dgb.setTotalSize(cgb.getTotalSize());
	  
	 String[] methodos= new String[] {
		TrabajadoresHelper.IDCATEGORIA_GET_METHOD_NAME+"TrabajadoresParsed"
		//,TrabajadoresHelper.NIF_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.NOMBRE_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.APELLIDOUNO_GET_METHOD_NAME+"TrabajadoresParsed"
		//,TrabajadoresHelper.APELLIDODOS_GET_METHOD_NAME+"TrabajadoresParsed"
		//,TrabajadoresHelper.FECHAALTA_GET_METHOD_NAME+"TrabajadoresParsed"
		//,TrabajadoresHelper.FECHABAJA_GET_METHOD_NAME+"TrabajadoresParsed"
		//,TrabajadoresHelper.NUMEROSS_GET_METHOD_NAME+"TrabajadoresParsed"
		//,TrabajadoresHelper.DIRECCION_GET_METHOD_NAME+"TrabajadoresParsed"
		//,TrabajadoresHelper.CP_GET_METHOD_NAME+"TrabajadoresParsed"
		//,TrabajadoresHelper.IDLOCALIDAD_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.TELEFONO_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.MOVIL_GET_METHOD_NAME+"TrabajadoresParsed"
		//,TrabajadoresHelper.EMAIL_GET_METHOD_NAME+"TrabajadoresParsed"
		//,TrabajadoresHelper.OBSERVACIONES_GET_METHOD_NAME+"TrabajadoresParsed"
		,"getHijosPartesTrabajadores"
		,"getEditTrabajadores"
		,"getDeleteTrabajadores"
	};
	 
	 StringBuffer cadena=null;
	 cadena = AjaxUtils.buildXmlAjaxResponseTableContentFromListObj(cgb.getAlmacen(),methodos,TrabajadoresHelper.IDTRABAJADOR_GET_METHOD_NAME, dgb,"ISO-8859-1"); 
	 cadena.insert(cadena.indexOf("</ajax-response>"),"<response type='object' id='divPath'>" + getPathTableContentTrabajadores(request,response) + "</response>");
	 xmlResponseService(response,cadena); 
 }  

 public void serviceTrabajadoresUlContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] methodos= new String[] {
	 		"getULContentTrabajadoresParsed"
			 };
	 String param =  WebUtils.getStringParam(request, "value");
	 if(param==null || param.length() <= 0)
		 param =  WebUtils.getStringParam(request, new PartesHelper().getIdtrabajadorName());
	 	 
	 TrabajadoresGroupBean mgb = TrabajadoresManager.getTrabajadoress(TrabajadoresManager.buildSearchCriteria(param));
	 simpleResponseService(response, AjaxUtils.buildAjaxULContentFromListObj(mgb.getAlmacen(),methodos, TrabajadoresHelper.COMPLEX_ID_GET_METHOD,"Trabajadores"));
 } 



 public void serviceTrabajadoresElement(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException, TorqueException
 {
  StringBuffer cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "trabajadores.IDTRABAJADOR");
  if (claveId!=-1)
  {
	  c.add(TrabajadoresPeer.IDTRABAJADOR, claveId);
  }
  c.addAscendingOrderByColumn(TrabajadoresPeer.IDTRABAJADOR);
  TrabajadoresGroupBean trgb = TrabajadoresManager.getTrabajadoress(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  String [] parametros={
		TrabajadoresHelper.IDTRABAJADOR_GET_METHOD_NAME
		,TrabajadoresHelper.IDCATEGORIA_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.NIF_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.NOMBRE_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.APELLIDOUNO_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.APELLIDODOS_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.FECHAALTA_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.FECHABAJA_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.NUMEROSS_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.DIRECCION_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.CP_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.IDLOCALIDAD_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.TELEFONO_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.MOVIL_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.EMAIL_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.OBSERVACIONES_GET_METHOD_NAME+"TrabajadoresParsed"
	  };
	  cadena=trgb.buildXml(parametros,null,"ISO-8859-1");	
	  cadena.insert(cadena.indexOf("</result>"),getPathElementTrabajadores(request,response));  
  }
  xmlResponseService(response, cadena);
 }  
 
 

 protected StringBuffer updateIdtrabajadorResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TrabajadoresManager.getTrabajadores(Integer.parseInt(a.get(0).toString())).getIdtrabajadorTrabajadoresParsed());
 }  
 

 protected StringBuffer updateIdcategoriaResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TrabajadoresManager.getTrabajadores(Integer.parseInt(a.get(0).toString())).getIdcategoriaTrabajadoresParsed());
 }  
 

 protected StringBuffer updateNifResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TrabajadoresManager.getTrabajadores(Integer.parseInt(a.get(0).toString())).getNifTrabajadoresParsed());
 }  
 

 protected StringBuffer updateNombreResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TrabajadoresManager.getTrabajadores(Integer.parseInt(a.get(0).toString())).getNombreTrabajadoresParsed());
 }  
 

 protected StringBuffer updateApellidounoResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TrabajadoresManager.getTrabajadores(Integer.parseInt(a.get(0).toString())).getApellidounoTrabajadoresParsed());
 }  
 

 protected StringBuffer updateApellidodosResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TrabajadoresManager.getTrabajadores(Integer.parseInt(a.get(0).toString())).getApellidodosTrabajadoresParsed());
 }  
 

 protected StringBuffer updateFechaaltaResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TrabajadoresManager.getTrabajadores(Integer.parseInt(a.get(0).toString())).getFechaaltaTrabajadoresParsed());
 }  
 

 protected StringBuffer updateFechabajaResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TrabajadoresManager.getTrabajadores(Integer.parseInt(a.get(0).toString())).getFechabajaTrabajadoresParsed());
 }  
 

 protected StringBuffer updateNumerossResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TrabajadoresManager.getTrabajadores(Integer.parseInt(a.get(0).toString())).getNumerossTrabajadoresParsed());
 }  
 

 protected StringBuffer updateDireccionResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TrabajadoresManager.getTrabajadores(Integer.parseInt(a.get(0).toString())).getDireccionTrabajadoresParsed());
 }  
 

 protected StringBuffer updateCpResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TrabajadoresManager.getTrabajadores(Integer.parseInt(a.get(0).toString())).getCpTrabajadoresParsed());
 }  
 

 protected StringBuffer updateIdlocalidadResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TrabajadoresManager.getTrabajadores(Integer.parseInt(a.get(0).toString())).getIdlocalidadTrabajadoresParsed());
 }  
 

 protected StringBuffer updateTelefonoResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TrabajadoresManager.getTrabajadores(Integer.parseInt(a.get(0).toString())).getTelefonoTrabajadoresParsed());
 }  
 

 protected StringBuffer updateMovilResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TrabajadoresManager.getTrabajadores(Integer.parseInt(a.get(0).toString())).getMovilTrabajadoresParsed());
 }  
 

 protected StringBuffer updateEmailResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TrabajadoresManager.getTrabajadores(Integer.parseInt(a.get(0).toString())).getEmailTrabajadoresParsed());
 }  
 

 protected StringBuffer updateObservacionesResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
  return new StringBuffer(TrabajadoresManager.getTrabajadores(Integer.parseInt(a.get(0).toString())).getObservacionesTrabajadoresParsed());
 }  
 
 
 
 
 public void serviceTrabajadoresCategorias(HttpServletRequest request, HttpServletResponse response) throws IOException, TorqueException, ServletException
 {
  String cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "categorias.IDCATEGORIA");
  if (claveId!=-1)
  {
	  c.add(CategoriasPeer.IDCATEGORIA, claveId);
  }
  c.addAscendingOrderByColumn(CategoriasPeer.IDCATEGORIA);
  CategoriasGroupBean trgb = CategoriasManager.getCategoriass(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  cadena = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>";
	  cadena = cadena + "<result><trabajadores.IDCATEGORIA>" + trgb.getCategorias(0).getULContentCategoriasParsed()  + "</trabajadores.IDCATEGORIA></result>";
  }
  
  xmlResponseService(response, new StringBuffer(cadena));
 }  
  			

 public void serviceTrabajadoresLocalidades(HttpServletRequest request, HttpServletResponse response) throws IOException, TorqueException, ServletException
 {
  String cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "localidades.IDLOCALIDAD");
  if (claveId!=-1)
  {
	  c.add(LocalidadesPeer.IDLOCALIDAD, claveId);
  }
  c.addAscendingOrderByColumn(LocalidadesPeer.IDLOCALIDAD);
  LocalidadesGroupBean trgb = LocalidadesManager.getLocalidadess(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  cadena = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>";
	  cadena = cadena + "<result><trabajadores.IDLOCALIDAD>" + trgb.getLocalidades(0).getULContentLocalidadesParsed()  + "</trabajadores.IDLOCALIDAD></result>";
  }
  
  xmlResponseService(response, new StringBuffer(cadena));
 }  
  			

 public void serviceGetTrabajadoresDetallePdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] getMethodos= new String[] {
		TrabajadoresHelper.IDTRABAJADOR_GET_METHOD_NAME
		,TrabajadoresHelper.IDCATEGORIA_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.NIF_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.NOMBRE_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.APELLIDOUNO_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.APELLIDODOS_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.FECHAALTA_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.FECHABAJA_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.NUMEROSS_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.DIRECCION_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.CP_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.IDLOCALIDAD_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.TELEFONO_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.MOVIL_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.EMAIL_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.OBSERVACIONES_GET_METHOD_NAME+"TrabajadoresParsed"
			 };
	  
	 
	 TrabajadoresGroupBean tgb = new TrabajadoresGroupBean();
	 try
	{
		tgb.setElemento(TrabajadoresHelper.getTrabajadores(request));
	} catch (TorqueException e)
	{
		logger.severe(e.getMessage());
	}
	
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(getMethodos, null,"ISO-8859-1"),"n/a"," "), trabajadores_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=Trabajadores.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
	
 }  

 public void serviceTrabajadoresTableContentPdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
  	utf8RequestService(request);
  	Criteria c= new Criteria();
  	String paramQuery =  WebUtils.getStringParam(request, "query");
  	if ((paramQuery != null)&& (paramQuery.compareTo("")!=0) )
		c = TrabajadoresManager.buildSearchCriteria(paramQuery);   
  	c =criteriaTrabajadoresTableContent(request,c);	  
  	TrabajadoresGroupBean tgb = TrabajadoresManager.getTrabajadoress(c);
  
  	String[] methodos= new String[] {	
		TrabajadoresHelper.IDCATEGORIA_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.NIF_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.NOMBRE_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.APELLIDOUNO_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.APELLIDODOS_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.FECHAALTA_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.FECHABAJA_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.NUMEROSS_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.DIRECCION_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.CP_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.IDLOCALIDAD_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.TELEFONO_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.MOVIL_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.EMAIL_GET_METHOD_NAME+"TrabajadoresParsed"
		,TrabajadoresHelper.OBSERVACIONES_GET_METHOD_NAME+"TrabajadoresParsed"
			};
  
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(methodos, null,"ISO-8859-1"),"n/a"," "), trabajadoress_transformer,"ISO-8859-1");
	 response.addHeader("content-disposition","attachment;filename=ListaTrabajadores.pdf");
	 response.setContentType("application/pdf");
	 response.setHeader("Cache-Control", "");//para que funcione en IE
	 response.setContentLength(content.length);
	 response.getOutputStream().write(content);
	 response.getOutputStream().flush();  
	 response.getOutputStream().close();
 }

}


