package net.idtoki.instelec.manager;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

import com.workingdogs.village.Record;
import com.workingdogs.village.DataSetException;

import net.idtoki.instelec.model.CategoriasPeer;
import net.idtoki.instelec.model.TareasPeer;
import net.idtoki.instelec.model.MaterialesPeer;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Jul 26 13:47:22 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class TareasManager
    extends BaseTareasManager
{


//Borrado de un elemento
	public static boolean borraTareas(int idBorrar) {

		Criteria c=new Criteria();
		c.add(TareasPeer.IDTAREA, idBorrar);
		boolean bRet = false;
		try {
			TareasPeer.doDelete(c);
			bRet = true;
		} catch (TorqueException e) {
			logger.info("No se ha podido borrar en la tabla Tareas");
			e.printStackTrace();
			bRet = false;
		}
		return bRet;
	}
	
	public static double getImporteCalculadoTareas(int idTarea) throws TorqueException,DataSetException
	{
		Criteria c=new Criteria();
		c.add(TareasPeer.IDTAREA, idTarea);	
		c.addJoin(MaterialesPeer.IDTAREA, TareasPeer.IDTAREA);
		c.addSelectColumn("SUM(" + MaterialesPeer.IMPORTE + "*" + MaterialesPeer.CANTIDAD + ")");
		  java.util.List result = MaterialesPeer.doSelectVillageRecords(c);
		  com.workingdogs.village.Record record = (com.workingdogs.village.Record) result.get(0);
		  return record.getValue(1).asDouble();		
	}	
	
}


