package net.idtoki.instelec.helper;

import net.idtoki.instelec.model.Lineasparte;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Aug 07 12:09:17 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class LineasparteHelper
    extends net.idtoki.instelec.helper.BaseLineasparteHelper
{
		    			public LineasparteHelper()
    {
        super();
    }
    public LineasparteHelper(Lineasparte obj)
    {
        super(obj);
    }
}


