package net.idtoki.instelec.helper;

import net.idtoki.instelec.model.Localidades;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Jul 26 13:47:22 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class LocalidadesHelper
    extends net.idtoki.instelec.helper.BaseLocalidadesHelper
{
		    			public LocalidadesHelper()
    {
        super();
    }
    public LocalidadesHelper(Localidades obj)
    {
        super(obj);
    }
}


