package net.idtoki.instelec.group;

import net.idtoki.instelec.model.LineaspartePeer;
import net.idtoki.instelec.model.Lineasparte;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Aug 07 12:09:17 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class LineasparteGroupBean
    extends net.idtoki.instelec.group.BaseLineasparteGroupBean
{
  public LineasparteGroupBean(){
        this.dbField = LineaspartePeer.IDLINEAPARTE;
              
//podemos fijar el numero de elementos por pagina recogiendo el entero de un archivo de configuracion
//this.setNumeroElementosPorPagina(int);
//si no se utiliza this.setNumeroElementosPorPagina(); el numero por defecto es 10

  }
}


